docs/guide/ingest.ipynb
docs/guide/rds-bfx.ipynb
lamindb/db/_ingest.py

- Set `name` column in `pipeline_run` to `BfxRun.outdir`.
- Passed fastqs and sample output directory separately to `BfxRun`.

:memo: Update bfx ingestion demo

---

lamindb/db/_ingest.py

The whole ingestion logic needs to have proper clean-up in place if any aspect of it fails.
This will take a bit more time.
Also: FYI @bpenteado.

🚸 Test notebook integrity before doing anything else

---

.gitignore
docs/guide/link.ipynb
docs/guide/rds-bfx.ipynb
docs/guide/rds-compbio.ipynb
lamindb/_check_versions.py
lamindb/db/_ingest.py
lamindb/db/_link.py
pyproject.toml

Migrated primary key from dobject_id to (dobject_id, dobject_v)

⬆️ Upgrade pkg versions

---

docs/faq/flow.ipynb
docs/guide/introspect.ipynb
docs/guide/load-and-query.ipynb
docs/guide/rds-analyze-assay.ipynb
docs/guide/rds-dataflow.ipynb
docs/guide/share-cross-org.ipynb
lamindb/db/_ingest.py
lamindb/db/_query.py
lamindb/dev/__init__.py
lamindb/dev/_query_result.py
tests/test_db.py

- `ln.db.query.dobject(as_df).all()` → `ln.db.query.dobject().df()`
- `QueryResult` documentation

🎨 Added `.df()` as an option to return query results

---

docs/guide/schema.ipynb
lamindb/schema/__init__.py
lamindb/schema/_core.py

This PR will contains all the modifications needed to have a very basic version of lamindb-rest.

🎨 Get db metadata as a dictionary

---

docs/changelog.md
lamindb/_check_versions.py
lamindb/db/_ingest.py
pyproject.toml

- `IngestBfxRun` is now `IngestPipelineRun`, which provides compatibility with any kind of pipeline (bfx, ml, etc.).

:recycle: Generalize pipeline ingestion

---

lamindb/db/_ingest.py

:recycle: Inherit `IngestObject` and `IngestPipelineRun` from `IngestEntity`

---

docs/guide/A3-ingest.ipynb
lamindb/db/_ingest.py

- `Ingest` → `ingest`
- `IngestDobject` → `Ingest`

🎨 Make ingest a static class

---

pyproject.toml

:arrow_up: Update nbproject version to 0.5.5

---

docs/guide/A1-get-started.ipynb
docs/guide/A3-ingest.ipynb
docs/guide/A7-pipeline.ipynb
lamindb/datasets/_core.py
lamindb/db/ingest/_link_ingest.py

- Extended ingestion notebooks
- Fixed bugs in inserting linked entries
- Moved paradisi05 file to S3 to avoid download issues

📝 Improved ingest guides, fixed linked entry bugs

---

lamindb/db/_ingest.py
lamindb/db/_load.py
lamindb/dev/db/_staged.py
lamindb/dev/file/__init__.py
lamindb/dev/file/_file.py
lamindb/dev/file/_h5ad.py
lamindb/dev/file/_zarr.py
lamindb/dev/object/_core.py
pyproject.toml

upd of this
https://github.com/laminlabs/lamindb/pull/225

:sparkles: Add streaming zarr writes and streaming h5ad and zarr reads

---

lamindb/db/_ingest.py

Fix https://github.com/laminlabs/lamindb/issues/275

:adhesive_bandage: Fix out of sync db warning

---

docs/guide/A4-link.ipynb
docs/guide/A5-select-load.ipynb
lamindb/_check_versions.py
pyproject.toml

⬆️ Added bioreadout lookup to guide

---

lamindb/db/_ingest.py
lamindb/dev/db/_core.py
lamindb/dev/db/_staged.py
lamindb/dev/file/_file.py

:sparkles: Add an option to use `fsspec` for upload

---

docs/faq/ingest-bfx.ipynb
lamindb/dev/db/_core.py
lamindb/dev/db/_staged.py

Fixed linking entries via link tables.

🐛 Fixed link via link tables

---

lamindb/dev/db/_staged.py

:pencil2: Fix typo in link table entry fetching

---

docs/guide/A5-select-load.ipynb
docs/guide/B7-dataflow.ipynb
lamindb/dev/db/_core.py
lamindb/dev/db/_select.py

Refactored linked select for dobjects.

♻️ Refactor linked select

---

docs/guide/B1-setup.ipynb
docs/guide/B2-design-experiment.ipynb
docs/guide/B4-analyze-assay.ipynb
lamindb/_check_versions.py
pyproject.toml

- https://github.com/laminlabs/lnschema-core/pull/46
- https://github.com/laminlabs/lnschema-wetlab/pull/30

⬆️ Added `dset` and `project` tables to core

---

docs/faq/postgres.ipynb

:memo: Update postgres faq notebook

---

lamindb/_check_versions.py
pyproject.toml

:arrow_up: Upgrade `lnbfx` to 0.4.5

---

docs/faq/ingest-bfx.ipynb
docs/guide/7-pipeline.ipynb
docs/guide/8-view.ipynb
lamindb/__init__.py
lamindb/_delete.py
lamindb/_ingest.py
lamindb/_link.py
lamindb/_load.py
lamindb/_view.py
lamindb/dev/db/_add.py
lamindb/dev/db/_select.py
tests/test_dynamic_settings.py

Re-organize API docs.
Refactor select (@fredericenard):
old | new
--- | ---

:recycle: Refactor select

---

docs/faq/ingest-bfx.ipynb
docs/guide/7-pipeline.ipynb
lamindb/_check_versions.py
lamindb/_ingest.py
lamindb/schema/__init__.py
pyproject.toml
tests/test_dynamic_settings.py

- https://github.com/laminlabs/lnschema-core/pull/54
- https://github.com/laminlabs/lnbfx/pull/46

🚚 Rename `PipelineRun` to `Run`

---

docs/faq/index.md
docs/faq/zarr-ingest-load.ipynb

✅ Add tests for zarr ingest and load

---

docs/faq/flow.ipynb
docs/faq/ingest-bfx.ipynb
docs/faq/link-entities.ipynb
docs/faq/linked-select.ipynb
docs/faq/zarr-ingest-load.ipynb
docs/guide/1-get-started.ipynb
docs/guide/2-schema.ipynb
docs/guide/3-ingest.ipynb
docs/guide/4-link-features.ipynb
docs/guide/5-link.ipynb
docs/guide/6-select-load.ipynb
docs/guide/7-add-delete.ipynb
docs/guide/8-pipeline.ipynb
lamindb/_check_versions.py
lamindb/_delete.py
lamindb/_ingest.py
lamindb/_load.py
lamindb/dev/db/_staged.py
lamindb/schema/__init__.py
pyproject.toml
tests/test_db.py

- https://www.notion.so/laminlabs/Data-lineage-schema-review-2022-11-11-6219901addb04b368ed030bcdb06c48f
- https://github.com/laminlabs/lnschema-core/pull/56

🏗️ Aggregate `Run` and `DTransform`

---

.gitignore
docs/faq/header.ipynb
docs/faq/index.md
docs/faq/ingest-bfx.ipynb
docs/faq/ingest-same-file-twice.ipynb
docs/faq/link-entities.ipynb
docs/faq/linked-select.ipynb
docs/faq/storage.ipynb
docs/faq/zarr-ingest-load.ipynb
docs/guide/1-get-started.ipynb
docs/guide/2-schema.ipynb
docs/guide/5-link.ipynb
docs/guide/6-select-load.ipynb
docs/guide/7-add-delete.ipynb
docs/guide/8-pipeline.ipynb
docs/guide/9-view.ipynb
lamindb/__init__.py
lamindb/_check_versions.py
lamindb/_ingest.py
lamindb/_load.py
lamindb/_nb.py
lamindb/nb.py
pyproject.toml

See [design doc](https://www.notion.so/laminlabs/Ingestion-workflow-review-2022-11-12-f7a4759af3404e32af0169adb232f178).

✨ Initialize `Jupynb` `run` upon `nb.header()`

---

docs/faq/ingest-bfx.ipynb
docs/guide/05-link-features.ipynb
docs/guide/07-link-samples.ipynb
lamindb/dev/db/_select.py
lamindb/schema/__init__.py
pyproject.toml

- https://github.com/laminlabs/lnschema-wetlab/pull/39

🎨 Drop `Biometa`

---

docs/faq/adatas-subset.ipynb
docs/faq/index.md
lamindb/__init__.py
lamindb/_delete.py
lamindb/_subset.py
lamindb/dev/file/__init__.py
lamindb/dev/file/_file.py
lamindb/dev/object/__init__.py
lamindb/dev/object/_subset_anndata.py

:sparkles: Add subset function for dobjects

---

docs/faq/streaming-objects.ipynb
lamindb/dev/object/_lazy_field.py

:sparkles: Improve lazy selectors

---

lamindb/schema/__init__.py
pyproject.toml

:arrow_up: Upgrade wetlab to `0.11.4`

---

lamindb/schema/__init__.py
pyproject.toml

:arrow_up: Upgrade wetlab

---

docs/faq/acid.ipynb
docs/faq/index.md
docs/faq/streaming-objects.ipynb
docs/guide/02-select.ipynb
docs/guide/12-view-bio.ipynb
lamindb/_delete.py
lamindb/dev/db/_add.py
lamindb/dev/db/_select.py

This is the first of at least 2 PRs making improvements. Several issues are not yet fixed with this.

🚸 More encapsulated connections and ACID test 1

---

.github/workflows/build.yml
lamindb/__init__.py
lamindb/_check_versions.py
pyproject.toml

3.7 is currently not supported as sklearn doesn't support it.

👷 Extend CI to py3.8-3.10

---

docs/faq/acid.ipynb
lamindb/_check_versions.py
pyproject.toml
tests/test_db.py

Through ⬆️ `lnschema-core` to 0.25.0.

🚸 Introduce data validation on the ORM level

---

docs/faq/setup.ipynb
docs/guide/05-setup.ipynb
lamindb/_check_versions.py
pyproject.toml

🩹 Better treat edge cases upon signup, login, failed instance loading

---

docs/faq/data-validation.ipynb
docs/faq/index.md

:memo: Create data validation FAQ

---

.github/workflows/build.yml
lamindb/_delete.py
lamindb/_load.py
lamindb/dev/db/_add.py
lamindb/dev/db/_session.py

✨ Add explicit remote sqlite instance locking to write operations

---

lamindb/_check_versions.py
pyproject.toml

:arrow_up: Upgrade lnschema-core to 0.25.1

---

lamindb/_check_versions.py
pyproject.toml

🩺 Increase migrations testing robustness postgres

---

lamindb/_check_versions.py
pyproject.toml

Bringing in @bpenteado's feature!

:children_crossing: Add rich string representations to ORMs

---

lamindb/_check_versions.py
pyproject.toml

Revert ":children_crossing: Add rich string representations to ORMs"

---

lamindb/_nb.py

🐛 Correct filepath in header

---

docs/faq/existing-data.ipynb
docs/faq/index.md
docs/faq/legacy-data.ipynb
docs/faq/storage.ipynb
docs/faq/stream.ipynb
docs/guide/07-session.ipynb
lamindb/_check_versions.py
lamindb/_load.py
lamindb/_record.py
lamindb/dev/db/_add.py
lamindb/dev/file/_file.py
pyproject.toml

Together with: https://github.com/laminlabs/lnschema-core/pull/96

✨ Allow ingesting existing data in the cloud

---

lamindb/_load.py
lamindb/_record.py

:bug: Fix load

---

lamindb/dev/db/_add.py
lamindb/dev/file/_file.py

🩹 Print dobject name for zarr upload

---

docs/faq/track-runin.ipynb
lamindb/_check_versions.py
lamindb/_load.py
lamindb/schema/__init__.py
pyproject.toml

together with: https://github.com/laminlabs/lnschema-core/pull/104

✨ Added `is_run_input` param to `DObject.load()`

---

docs/faq/ingest-acid.ipynb
lamindb/dev/db/_add.py

`added_records` was not being assigned in the case of a DB error.

🚑 Fix tracking of added records during `ln.add()`

---

lamindb/_check_versions.py
pyproject.toml

Via upgrade of `lnschema-core` to 0.27.1.

🚸 Add relationship between `DFolder` and `DObject`

---

docs/faq/ingest-acid.ipynb
lamindb/__init__.py
lamindb/_check_versions.py
lamindb/_record.py
lamindb/dev/db/_add.py
lamindb/dev/file/_file.py
lamindb/dev/object/_anndata.py
lamindb/dev/object/_subset_anndata.py
pyproject.toml

Linked to https://github.com/laminlabs/lndb/pull/291

⚡️ Replace CloudPath with UPath

---

docs/faq/existing-data.ipynb
lamindb/dev/db/_add.py

- https://github.com/laminlabs/lndb/pull/294

:bug: Another occurance of local filepath

---

docs/faq/existing-data.ipynb
docs/faq/ingest-folder.ipynb
lamindb/_check_versions.py
lamindb/_folder.py
lamindb/_record.py
lamindb/dev/db/_add.py
pyproject.toml

- Write _objectkey to .dobjects from DFolder
- Implemented `DFolder.get_dobject(relpath)`

🍱 `DFolder.get_dobject`

---

lamindb/dev/file/_filesystem.py
lamindb/dev/file/_h5ad.py
lamindb/dev/file/_zarr.py
lamindb/dev/object/_subset_anndata.py

✨ Infer filesystem for anndata read and write

---

.pre-commit-config.yaml
docs/faq/index.md
docs/faq/setup.ipynb
lamindb/__init__.py
lamindb/_check_versions.py
lamindb/schema/__init__.py
lamindb/setup/__init__.py
lamindb/setup/dev.py

Depends on
- https://github.com/laminlabs/lndb/pull/312

✅ Towards a single API

---

lamindb/_record.py
lamindb/dev/db/_add.py
lamindb/dev/file/__init__.py
lamindb/dev/file/_file.py
lamindb/dev/file/_images.py

✨ Allow uploading zarr from local paths

---

docs/guide/01-setup.ipynb

Updated docs for clarity in the `Sign up and log in user` section. Just suggestions so please review and edit if needed!

:construction_worker: Update docs to clarify sign up and log in

---

pyproject.toml

➖ Remove typeguard dependency

---

README.md
docs/guide/11-scrna.ipynb

Temporary fix by specifying id, this will be the default in the next bionty release.

🚑 Fix gene id

---

lamindb/_check_versions.py
pyproject.toml

⬆️ Upgrade lndb-storage

---

lamindb/dev/db/_session.py

🐛 Remove use_fsspec from session add

---

lamindb/_check_versions.py

🩹 Remove bionty import

---

lamindb/_load.py

✨ Add stage function to synchronize a File

---

lamindb/dev/db/_add.py

✨ Clear old files on replace if needed

---

lamindb/dev/db/_add.py

🩹 Clear _clear_storagekey after delete

---

docs/guide/01-setup.ipynb
docs/guide/03-files.ipynb
docs/guide/04-memory.ipynb
docs/guide/08-add-delete.ipynb

- https://github.com/laminlabs/lnschema-core/pull/149

📝 Update docs with `File.stage()` and `File.replace()`

---

lamindb/dev/db/_add.py

🐛 Fix checks on private attributes in ln.add

---

lamindb/dev/db/_add.py

🩹 Check private attributes properly in ln.add

---

lamindb/_file.py
lamindb/dev/db/_add.py
tests/test_file.py

- https://github.com/laminlabs/lamindb/issues/620

🐛 Storage-related fixes

---

lamindb/_context.py
pyproject.toml

https://github.com/laminlabs/lamindb/issues/615

🐛 Fix initialization of new notebooks

---

lamindb/_context.py

subj
@falexwolf this is a quick fix. But `track` needs to be restructured completely, it becomes unmanageable.

🐛 Fix track for copied / renamed notebooks

---

lamindb/_context.py

@falexwolf incorrect function was used, it was saving only for jupyter lab.

🐛 Use correct _save_notebook in track

---

docs/faq/02-ingest.ipynb
docs/faq/03-notebooks.ipynb
docs/faq/04-ingest-same-file-twice.ipynb
docs/faq/05-track-runin.ipynb
docs/faq/06-select.ipynb
docs/faq/07-ingest-acid.ipynb
docs/guide/03-files.ipynb
docs/guide/05-existing.ipynb
docs/guide/07-select.ipynb
docs/guide/08-run.ipynb
docs/guide/15-query-book.ipynb
docs/guide/index.md
lamindb/_amend_doc_strings.py
lamindb/_check_versions.py
lamindb/_context.py
lamindb/_file.py
lamindb/_folder.py
lamindb/_load.py
lamindb/_nb.py
lamindb/dev/db/_select.py
pyproject.toml

- https://github.com/laminlabs/lnschema-core/pull/157
In particular:
- 🚚 Rename `File.source` to `File.run` (and `File.source_id` to `File.run_id`)
- 🚚 Rename `created_by` to `created_by_id` everywhere, add `created_by_id` to `File` and `Storage`
- 🚸 Add `created_by` back as relationship with type `User`
- 🚚 Add `transform_id` to `File`, and `transform` as a relationship
- 🚚 Rename `File.targets` to `File.input_of`
- 🚚 Rename `Transform.v` to `Transform.version`
Simplified the `select` guide and the query book.

🚚 Better names, more relationships directly on `File`

---

lamindb/_context.py

🩹 Unpack notebook_path correctly

---

tests/test_notebooks.py

✅ Use nbproject-test directly

---

docs/guide/08-run.ipynb

van -> can

---

lamindb/_amend_doc_strings.py
lamindb/_check_versions.py
pyproject.toml

- https://github.com/laminlabs/lnschema-core/pull/159

🐛 Fix population of `transform_id` in File in edge cases

---

.gitmodules
README.md
docs/guide/01-setup.ipynb
docs/guide/12-link-samples.ipynb
docs/guide/index.md
lamindb/_check_versions.py
noxfile.py
pyproject.toml

- https://github.com/laminlabs/lnbase-biolab/pull/67
- Introduced new package: https://github.com/laminlabs/lnschema-lamin1

🚚 Replace `lnschema-wetlab` with `lnbase-biolab` and `lnschema-lamin1`

---

lamindb/_file.py

✨ Inherit fsspec kwargs from root and move in root check

---

lamindb/_amend_file.py
lamindb/_check_versions.py
lamindb/_file.py
pyproject.toml

- https://github.com/laminlabs/lndb-storage/pull/26
Is tested there!

✨ Introduce `File.backed()`

---

.github/workflows/build.yml
.gitmodules
lamindb/__init__.py
lamindb/_check_versions.py
noxfile.py
pyproject.toml
tests/test_db.py

Big change!
- https://github.com/laminlabs/lnschema-core/pull/172

🏗️ Remove SQL-level schema modules

---

lamindb/_check_versions.py
pyproject.toml

➖ Do not install storage extras by default

---

lamindb/_check_versions.py
pyproject.toml

⬆️ Update lndb to 0.45.0

---

.gitmodules
lamindb/__init__.py
lamindb/_amend_file.py
lamindb/_check_versions.py
lamindb/_context.py
lamindb/_delete.py
lamindb/_file.py
lamindb/_folder.py
lamindb/_settings.py
lamindb/_view.py
lamindb/dev/db/_add.py
lamindb/dev/db/_select.py
lamindb/dev/db/_session.py
lamindb/schema/__init__.py
lamindb/schema/_core.py
lamindb/setup/__init__.py
lamindb/setup/dev/__init__.py
lamindb/setup/dev/upath.py
noxfile.py
pyproject.toml
tests/conftest.py
tests/test_db.py

- https://github.com/laminlabs/lamindb-setup/pull/389
- https://github.com/laminlabs/lndb-storage/pull/40

🚚 Rename `lndb` to `lamindb_setup`

---

lamindb/_features.py
lamindb/_file.py
lamindb/_parse.py

Converged feature parsing and ln.parse code.

♻️ Refactored feature parsing and `ln.parse`

---

docs/storage/add-replace-stage.ipynb
docs/storage/upload.ipynb

🐛 Disentangle keys in storage related test notebooks

---

pyproject.toml

➕ Pin boto3 in aws

---

lamindb/_check_versions.py
lamindb/_context.py
pyproject.toml

subj
This requires releases of https://github.com/laminlabs/lnschema-core and https://github.com/laminlabs/readfcs

➖ Move nbproject to extra dependencies

---

docs/guide/04-stream.ipynb
lamindb/dev/storage/object/_anndata_accessor.py

📝 Rework the stream notebook

---

lamindb/_delete.py

🐛 Fix delete for File

---

docs/biology/01-ontologies.ipynb
docs/guide/03-select.ipynb
docs/guide/06-configure.ipynb
docs/guide/index.md
lamindb/dev/__init__.py
noxfile.py

Moved some material from lamindb-setup into lamindb:
- https://github.com/laminlabs/lamindb-setup/pull/408

📝 Add `configure` guide instead of setup

---

lamindb/_delete.py
lamindb/_save.py

corresponds to https://github.com/laminlabs/lnschema-core/pull/196

✨ Delete storage in File.delete

---

lamindb/_context.py
lamindb/_file.py
lamindb/_folder.py
tests/test_folder.py

- https://github.com/laminlabs/lnschema-core/pull/198

♻️ Clean up core schema module

---

docs/guide/04-stream.ipynb
lamindb/_file_methods.py
lamindb/dev/storage/__init__.py
lamindb/dev/storage/object/_backed_access.py

✨ Add backed access to raw h5 and zarr objects

---

lamindb/_baseorm_methods.py
pyproject.toml

Needs https://github.com/laminlabs/lnschema-bionty/pull/130

🏷️ Change name to a required field for ontology tables

---

pyproject.toml

With https://github.com/laminlabs/lnschema-bionty/pull/133

⬆️ Allow create multiple records with .from_bionty

---

lamindb/_file_methods.py
lamindb/dev/storage/_file.py

This restores stream and adds some minor fixes for zarr adatas.
@falexwolf sorry for the dead code, i will add the tests soon.

🐛 Restore stream to fix zarr load

---

pyproject.toml

- https://laminlabs.slack.com/archives/C04FPE8V01W/p1687772196810549
- https://github.com/laminlabs/lnschema-core/pull/210

🎨 Auto-manage `RunInput` ORM

---

docs/guide/01-files-records.ipynb
lamindb/__init__.py
lamindb/_dataset.py
lamindb/_featureset_methods.py
lamindb/dev/datasets/__init__.py
lamindb/dev/datasets/_core.py

- https://github.com/laminlabs/lnschema-core/pull/212

✨ Add `Dataset` & `Feature` ORMs

---

lamindb/_file_methods.py

🐛 Fix the variable bug in File.delete

---

docs/biology/01-registries.ipynb
docs/lnschema-bionty.ipynb
lamindb/_baseorm_methods.py
lamindb/_from_values.py
pyproject.toml

With https://github.com/laminlabs/lnschema-bionty/pull/139

✨ Added self-referential parents, renamed abbr and description

---

lamindb/_file.py
tests/test_file.py

- https://github.com/laminlabs/lnschema-core/pull/214

🚚 Move `File` signatures

---

README.md
docs/faq/acid.ipynb
docs/faq/track-run-inputs.ipynb
docs/storage/add-replace-stage.ipynb
lamindb/_file.py
lamindb/_save.py
lamindb/dev/storage/_backed_access.py
tests/test_dataset.py
tests/test_file.py

- https://github.com/laminlabs/lnschema-core/pull/218

 🚚 Rename `File.name` to `File.description`

---

lamindb/dev/storage/_anndata_sizes.py

🚨 Remove warnings from zarr writing

---

lamindb/_context.py

🚸 Better error behavior when no notebook title set in `ln.track()`

---

docs/faq/setup.ipynb

- https://github.com/laminlabs/lamindb-setup/pull/434

🚸 Raise more errors in setup API when instance already setup

---

lamindb/dev/storage/_backed_access.py

🩹 Fix error on read partial when no spec is present

---

lamindb/_feature_set.py
lamindb/_save.py

- https://github.com/laminlabs/lamin-examples/pull/12

⚡️ Speed up parents creation

---

docs/biology/02-scrna.ipynb
lamindb/_file.py
tests/test_file.py

- https://github.com/laminlabs/lnschema-core/pull/222

✨ Add `from_df` and `from_anndata` to `File`

---

lamindb/_from_values.py
lamindb/_orm.py
lamindb/_queryset.py
pyproject.toml
tests/test_queryset.py

Now the django QuerySet also has all the methods

✨ Enable search, lookup, from_values, inspect, map_synonyms from QuerySet

---

docs/faq/import-schema.ipynb
docs/faq/index.md
lamindb/__init__.py
noxfile.py
pyproject.toml

- https://github.com/laminlabs/lamindb-setup/pull/436
- https://github.com/laminlabs/lnschema-bionty/pull/147

🚸 It should be possible to use a schema module prior to importing lamindb

---

docs/guide/02-data-lineage.ipynb
lamindb/_context.py
lamindb/_file.py

- https://github.com/laminlabs/lnschema-core/pull/223

✨ Track parent notebooks

---

lamindb/_save.py

https://laminlabs.slack.com/archives/C04FPE8V01W/p1688495466552269

⚡️ Copy or move files to the cache

---

lamindb/_save.py
tests/test_cache.py

✅ Add a unit test for file cache

---

lamindb/_orm.py

https://laminlabs.slack.com/archives/C04T2TQC7LL/p1688838249728879?thread_ts=1688814105.846839&cid=C04T2TQC7LL

 ⚡️ Speed up search

---

docs/faq/track-run-inputs.ipynb
docs/guide/02-data-lineage.ipynb
lamindb/_context.py
lamindb/_file.py
lamindb/_orm.py
lamindb/dev/_settings.py
lamindb/dev/_view_parents.py
lamindb/dev/datasets/_core.py

Also avoid cycles and other contrived scenarios (ln.track combinations with ln.settings.track_run_inputs).

🚸 Improve data-lineage guide, auto-track run inputs

---

pyproject.toml

🐛 Constrain urllib3 to fix incompatibility with botocore

---

lamindb/dev/_view_parents.py

Add better error msg if graphviz is not installed

---

docs/biology/01-registries.ipynb
docs/biology/04-samples.ipynb
lamindb/dev/_view_parents.py

Renames bionty to bt where applicable in the biology guides to conform with Bionty docs

Bionty naming

---

lamindb/_file.py
lamindb/dev/_settings.py
tests/test_file.py

- https://github.com/laminlabs/lamindb-benchmarks/pull/24

⚡ Speed up file creation

---

docs/guide/01-tutorial1.ipynb
lamindb/__init__.py
lamindb/_dataset.py
lamindb/_feature.py
lamindb/_feature_set.py
lamindb/_feature_value.py
lamindb/_file.py
lamindb/_view.py
lamindb/dev/datasets/_core.py
tests/test_dataset.py
tests/test_feature.py
tests/test_feature_set.py

- https://github.com/laminlabs/lnschema-core/pull/225

✨ Draft new `Feature` experience

---

.github/workflows/build.yml
docs/guide/tutorial1.ipynb
lamindb/_category.py
lamindb/_feature.py
lamindb/_from_values.py
tests/test_feature.py
tests/test_feature_set.py

- https://github.com/laminlabs/lnschema-core/pull/232

🚸 Improve categorical feature management

---

docs/faq/acid.ipynb
docs/faq/idempotency.ipynb
docs/faq/track-run-inputs.ipynb
docs/guide/tutorial1.ipynb
docs/reference.md
lamindb/__init__.py
lamindb/_file.py
lamindb/_manager.py
lamindb/_queryset.py
lamindb/_save.py
lamindb/dev/_view_parents.py
tests/test_file.py
tests/test_manager.py
tests/test_orm.py
tests/test_queryset.py

- https://github.com/laminlabs/lnschema-core/pull/233

 ♻️ Replace usage of `ln.Project` with `ln.Tag`, replace `Run.name` with `Run.reference_type` and more

---

lamindb/dev/storage/_backed_access.py

Fix backed accessor failing for adatas with dataset `obs` and `var`:
Fix for incorrect anndata file name displaying in the accessor `__repr__ `
Now works fine for s3://lamindata/srivatsan19/Srivatsan_2019_raw.h5ad:

🐛 Some fixes for backed

---

lamindb/_file.py
lamindb/dev/storage/file.py
tests/test_file.py

also `file.load()` will return `file._memory_rep` if it is present.

🐛 filepath_from_file now returns file._local_filepath if it is present

---

lamindb/_file.py
lamindb/dev/storage/__init__.py
lamindb/dev/storage/_backed_access.py

also `File.backed()` always returns `Accessor`, even when a local path exists.

✨ Disentangle File.backed() from zarr

---

lamindb/_feature.py
lamindb/_feature_set.py
tests/test_feature_set.py

- https://github.com/laminlabs/lnschema-core/pull/244

♻️ Add field `hash` to `FeatureSet`

---

lamindb/_feature.py
lamindb/_feature_manager.py
lamindb/_file.py
lamindb/_from_values.py
lamindb/_label.py
lamindb/_orm.py
lamindb/_save.py
tests/test_feature.py
tests/test_feature_manager.py

- Notion: https://www.notion.so/laminlabs/51ee0d6ac7064a7a99cc4b279d1e39f4?pvs=4
- core: https://github.com/laminlabs/lnschema-core/pull/249

🎨 Move feature foreignkey from label to link between label and file

---

lamindb/_feature_manager.py
lamindb/_feature_set.py
lamindb/_orm.py
tests/test_feature_manager.py
tests/test_feature_set.py

- https://github.com/laminlabs/lnschema-core/pull/250

♻️ Aggregate ref_field, ref_orm, ref_schema into ref_field

---

lamindb/_feature.py
lamindb/_feature_manager.py
lamindb/_orm.py
tests/test_feature_manager.py

- https://github.com/laminlabs/lnschema-core/pull/251

🚚 Rename `Feature.label_orms` to `Feature.registries`

---

lamindb/_file.py
lamindb/_save.py
lamindb/dev/storage/file.py

✨ Add a simple progress monitoring to file.load() and file.stage()

---

lamindb/dev/storage/_backed_access.py

🐛 Fix typo in backed

---

lamindb/dev/storage/_backed_access.py

fixes the problem with selection by names in backed

🐛 Make obs and var names indices

---

lamindb/_feature_manager.py

🎨 Allow passing queryset to add.labels

---

lamindb/_file.py
lamindb/dev/storage/__init__.py
lamindb/dev/storage/file.py
tests/test_file.py
tests/test_storage.py

needed due to https://github.com/fsspec/universal_pathlib/pull/125

🐛 Prepare for a new upath release

---

pyproject.toml

📌 Pin upath

---

lamindb/_feature_manager.py
lamindb/_feature_set.py
lamindb/_registry.py
tests/test_feature_manager.py
tests/test_feature_set.py

- https://github.com/laminlabs/lnschema-core/pull/256

🚚 Rename `FeatureSet.ref_field` to `FeatureSet.registry`

---

lamindb/_file.py
lamindb/dev/storage/file.py
tests/test_file.py

- https://github.com/laminlabs/lamindb/issues/1003

♻️ Better treatment of suffixes

---

lamindb/dev/_settings.py

- https://github.com/laminlabs/lamin-utils/pull/49

🚸 Increase default verbosity to hint-level

---

lamindb/_file.py
pyproject.toml
tests/test_file.py

- Ref: https://laminlabs.slack.com/archives/C046F63LJJ2/p1691664711894059?thread_ts=1691403669.946449&cid=C046F63LJJ2
- https://github.com/laminlabs/lnschema-core/pull/265

♻️ Refactor file versioning

---

docs/changelog.md
docs/guide/stream.ipynb
lamindb/_feature_set.py
lamindb/_file.py
lamindb/_validate.py
lamindb/dev/__init__.py
lamindb/dev/fields.py
pyproject.toml
tests/test_file.py

- https://github.com/laminlabs/lnschema-core/pull/262

🎉 Stage 0.50.2

---

lamindb/dev/storage/_backed_access.py
tests/test_storage.py

✅ More tests and fixes backed

---

lamindb/dev/storage/_backed_access.py
tests/test_storage.py

✅ More tests and fixes for backed

---

lamindb/_file.py
lamindb/dev/datasets/_core.py

- https://github.com/laminlabs/lamindb-dev-datasets/pull/2

🍱 Add the Iris images dev dataset

---

lamindb/_file.py
lamindb/_storage.py
lamindb/dev/storage/file.py

fixes problems with anon access.

♻️ Use principled conversion to paths with options inheritance

---

docs/bio-registries.ipynb
docs/changelog.md
docs/faq/notebooks.ipynb
docs/tutorial1.ipynb
lamindb/_dataset.py
lamindb/_feature.py
lamindb/_feature_set.py
lamindb/_file.py
lamindb/_from_values.py
lamindb/_transform.py
lamindb/_validate.py
lamindb/dev/_data.py
lamindb/dev/_run_context.py
lamindb/dev/versioning.py
pyproject.toml
tests/test_dataset.py
tests/test_delete.py
tests/test_feature.py
tests/test_feature_manager.py
tests/test_feature_set.py
tests/test_file.py
tests/test_from_values.py
tests/test_queryset.py
tests/test_registry.py
tests/test_run_context.py
tests/test_transform.py
tests/test_validate.py
tests/test_versioning.py

This currently only exists to trigger GA runs from main.
To run integration tests, rebase the `release` branch on the `main` branch.
To make a release, make a release from the `release` branch and rebase `main` on the `release` branch.

Prepare release [DON'T MERGE]

---

docs/changelog.md
docs/tutorial.ipynb
docs/tutorial1.ipynb
lamindb/_dataset.py

This currently only exists to trigger GA runs from main.
To run integration tests, rebase the release branch on the main branch (need to figure out a way that maintains this PR open though).
To make a release, make a release from the release branch and rebase main on the release branch.

Prepare release [DON'T MERGE] 

---

docs/tutorial1.ipynb
lamindb/dev/_data.py
tests/test_feature.py
tests/test_feature_manager.py

- https://github.com/laminlabs/lnschema-core/pull/287

♻️ Type features

---

lamindb/dev/_data.py
lamindb/dev/_feature_manager.py
lamindb/dev/_label_manager.py
tests/test_feature.py

- https://github.com/laminlabs/lnschema-core/pull/297

🔥 Remove add_labels & get_labels

---

pyproject.toml

subj
also closes https://github.com/laminlabs/lamindb/issues/1015

⬆️ Update fsspec to 2023.9.0

---

lamindb/_dataset.py
lamindb/_file.py
lamindb/dev/_data.py
tests/test_dataset.py

- https://github.com/laminlabs/lnschema-core/pull/299

♻️ Test dataset signatures and methods

---

lamindb/_dataset.py
lamindb/_feature_set.py
lamindb/dev/_data.py
lamindb/dev/_feature_manager.py
lamindb/dev/_label_manager.py
tests/test_feature_set.py

- https://github.com/laminlabs/lnschema-core/pull/300

🎨 Add a members property to FeatureSet

---

docs/schemas.ipynb
lamindb/dev/_data.py
lamindb/dev/_label_manager.py
lamindb/dev/_settings.py
pyproject.toml

- https://github.com/laminlabs/lamindb-setup/pull/537
- https://github.com/laminlabs/lnschema-core/pull/301

✨ Save notebook files

---

docs/transfer.ipynb
lamindb/_dataset.py
lamindb/_file.py
lamindb/_registry.py
lamindb/_storage.py
tests/conftest.py
tests/test_dataset.py
tests/test_file.py

- https://www.notion.so/laminlabs/Datasets-from-paths-storage-c3f0a3f85a1f4b108682ee7e7ffc2534
- https://github.com/laminlabs/lnschema-core/pull/303

✨ Dataset from paths aka storage

---

lamindb/dev/storage/_backed_access.py
pyproject.toml

⬆️ Make backed compatible with anndata==0.10.1

---

lamindb/dev/datasets/_core.py

♻️ Keep raw in pbmc68k_reduced and human_immune_cells

---

README.md
docs/bio-registries.ipynb
docs/faq/notebooks.ipynb
docs/features-lamindb.md
docs/storage/add-replace-stage.ipynb
lamindb/_dataset.py
lamindb/_feature_set.py
lamindb/_file.py
lamindb/_parents.py
lamindb/_registry.py
lamindb/_save.py
lamindb/_transform.py
lamindb/dev/_data.py
lamindb/dev/_feature_manager.py
lamindb/dev/_label_manager.py
lamindb/dev/_run_context.py
lamindb/dev/storage/file.py
lamindb/dev/versioning.py
pyproject.toml
tests/test_dataset.py
tests/test_db.py
tests/test_delete.py
tests/test_feature_manager.py
tests/test_feature_set.py
tests/test_file.py
tests/test_queryset.py
tests/test_run.py
tests/test_run_context.py
tests/test_transform.py

- https://github.com/laminlabs/lamindb-setup/pull/552
- https://github.com/laminlabs/lnschema-core/pull/304
- https://github.com/laminlabs/lnschema-bionty/pull/188
- https://github.com/laminlabs/lnschema-lamin1/pull/36

🚚 Migrate to integer primary keys

---

docs/bio-registries.ipynb
docs/data.ipynb
docs/faq/import-schema.ipynb
docs/introduction.ipynb
docs/transfer.ipynb
docs/tutorial2.ipynb
lamindb/_from_values.py
lamindb/_registry.py
lamindb/_validate.py
lamindb/dev/datasets/_core.py
pyproject.toml
tests/test_dataset.py
tests/test_feature_manager.py
tests/test_feature_set.py
tests/test_file.py
tests/test_from_values.py
tests/test_parents.py
tests/test_transfer.py
tests/test_validate.py

https://github.com/laminlabs/lnschema-core/pull/305
https://github.com/laminlabs/lamindb-setup/pull/559
https://github.com/laminlabs/lnschema-bionty/pull/192

🚚 Rename `Species` to `Organism`

---

pyproject.toml

- https://github.com/laminlabs/lamindb-setup/pull/561
- https://github.com/laminlabs/lnschema-core/pull/306

🔥 Do not populate user email in User registry

---

lamindb/dev/storage/_backed_access.py
pyproject.toml

➕ Allow more anndata versions

---

docs/transfer.ipynb
lamindb/_filter.py
lamindb/_registry.py
tests/test_registry.py
tests/test_transfer.py

- https://github.com/laminlabs/lnschema-core/pull/309

♻️ Turn `using` into a `Registry` method

---

.github/workflows/build.yml
.pre-commit-config.yaml
lamindb/_feature.py
lamindb/_file.py
lamindb/dev/_settings.py
lamindb/dev/datasets/_core.py
noxfile.py
pyproject.toml
sub/lamin-cli/README.md
sub/lamin-cli/lamin_cli/__init__.py
sub/lamin-cli/lamin_cli/__main__.py
sub/lamin-cli/lamin_cli/_notebook.py
sub/lamin-cli/pyproject.toml
sub/lamin-cli/tests/conftest.py
sub/lamin-cli/tests/notebooks/no-title.ipynb
sub/lamin-cli/tests/notebooks/not-initialized.ipynb
sub/lamin-cli/tests/notebooks/with-title-and-initialized-consecutive.ipynb
sub/lamin-cli/tests/notebooks/with-title-and-initialized-non-consecutive.ipynb
sub/lamin-cli/tests/test_cli.py
sub/lamin-cli/tests/test_notebooks.py
tests/test_file.py

- https://github.com/laminlabs/lamindb-setup/pull/572
- https://github.com/laminlabs/laminci/pull/26

🚚 Move CLI from lamindb-setup here

---

docs/installation.md
docs/introduction.ipynb
docs/setup.ipynb
docs/signup-login.md
noxfile.py

- https://github.com/laminlabs/lamin-docs/pull/70

📝 Harmonize setup docs, access docs and CLI docs

---

pyproject.toml

https://laminlabs.slack.com/archives/C04FPE8V01W/p1698239551460289

🚸 Improve connection stability

---

lamindb/dev/storage/_backed_access.py
tests/test_storage.py

fix to https://laminlabs.slack.com/archives/C04FPE8V01W/p1699112032817079

🐛 Backed raw subset fix

---

docs/changelog.md
lamindb/__init__.py
lamindb/_view.py
lamindb/dev/storage/__init__.py

- https://github.com/laminlabs/lamindb-setup/pull/577

♻️ Move UPath to root-level API

---

docs/tutorial.ipynb
lamindb/_file.py
lamindb/dev/storage/file.py
tests/test_file.py

- https://github.com/laminlabs/lamindb-setup/pull/578

🚚 Move `view_tree` to `UPath`

---

pyproject.toml

⬆️ Update required versions of anndata, s3fs

---

lamindb/dev/_run_context.py

https://laminlabs.slack.com/archives/C04FPE8V01W/p1699443688434429

🚸 Ensure saved notebooks aren't rerun with the same version

---

lamindb/_registry.py
tests/test_transfer.py

- https://github.com/laminlabs/lamindb/issues/1304

🐛 Fix bug in transfer files

---

lamindb/dev/_run_context.py
pyproject.toml
tests/test_run_context.py

- https://github.com/laminlabs/lamin-cli/pull/5

✨ Track Python scripts

---

docs/storage/upload.ipynb
lamindb/_file.py
lamindb/_save.py
lamindb/dev/storage/file.py

- https://github.com/laminlabs/lamindb-setup/pull/587

♻️ Centralize progressbar and convert to percentage

---

lamindb/_file.py
lamindb/dev/storage/file.py

https://github.com/laminlabs/lamindb-setup/pull/588

🔊 Turn on progress on upload and download

---

docs/guide.md
docs/public-ontologies.ipynb
noxfile.py

- https://github.com/laminlabs/bionty/pull/532

🚚 Move high-level bionty docs here

---

lamindb/_dataset.py
lamindb/dev/_mapped_dataset.py
lamindb/dev/storage/_backed_access.py
tests/test_dataset.py

✨ Do virtual inner join of variables in Dataset.mapped

---

lamindb/_artifact.py

🐛 Fix hash inference for cloud non-s3 objects and use stored gcs credentials

---

pyproject.toml

- https://github.com/laminlabs/lamindb-setup/pull/597

🚸 Silence the httpx logger

---

lamindb/dev/_data.py
lamindb/dev/_label_manager.py
tests/test_feature_manager.py
tests/test_label_manager.py

- https://github.com/laminlabs/lamindb/issues/1361

🐛 Account for length zero label lists

---

docs/changelog.md
docs/introduction.ipynb
docs/tutorial.ipynb
docs/tutorial2.ipynb
lamindb/_parents.py
lamindb/dev/_data.py
tests/test_dataset.py

https://laminlabs.slack.com/archives/C046F63LJJ2/p1693303455722409

🚚 Rename `view_flow` to `view_lineage`

---

pyproject.toml

- https://github.com/laminlabs/lamindb-setup/pull/600
- https://github.com/laminlabs/lamindb-setup/pull/601

🎨 Name `.lndb` files by instance id

---

lamindb/_artifact.py
lamindb/_dataset.py
lamindb/_transform.py
lamindb/dev/_run_context.py
lamindb/dev/versioning.py
pyproject.toml
tests/test_artifact.py
tests/test_dataset.py
tests/test_run_context.py
tests/test_transform.py

https://laminlabs.slack.com/archives/C04FPE8V01W/p1703160270853689
- https://github.com/laminlabs/lnschema-core/pull/328
- https://github.com/laminlabs/lamin-cli/pull/13

🎨 Version based on `stem_uid` instead of `initial_version_id`

---

.github/workflows/build.yml
noxfile.py

- https://github.com/laminlabs/lamin-cli/pull/14
- https://github.com/laminlabs/lamindb-setup/pull/603
- https://github.com/laminlabs/laminhub-rest/pull/347

🎨 Track migration status in hub

---

lamindb/_collection.py
lamindb/dev/_mapped_collection.py
tests/test_collection.py

- Adds virtual outer join
- Improves access speed by caching categories of labels.

✨ Add outer join and categories caching to Collection.mapped

---

lamindb/dev/_track_environment.py

- https://github.com/laminlabs/lamin-cli/pull/15

🩹 Track suffix of requirements.txt

---

lamindb/_parents.py
lamindb/dev/_data.py
lamindb/dev/_label_manager.py
lamindb/dev/_run_context.py
tests/test_feature_manager.py

- https://github.com/laminlabs/lamin-cli/pull/16

🚸 Various improvements

---

.github/workflows/build.yml
docs/installation.md
docs/introduction.ipynb
docs/signup-login.md
docs/tutorial.ipynb
noxfile.py

- https://github.com/laminlabs/lamin-cli/pull/17
- https://github.com/laminlabs/lamindb-setup/pull/610

🚸 Add anonymous access (now works without login)

---

lamindb/_collection.py
lamindb/dev/_mapped_collection.py

🔊 Log joins in Collection.mapped

---

lamindb/dev/_mapped_collection.py
tests/test_collection.py

♻️ Incorporate edge cases into inner and outer join in Collection.mapped

---

pyproject.toml

✏️ Fix lnschema-bionty uid encoding

---

noxfile.py
pyproject.toml

- https://github.com/laminlabs/lamin-cli/pull/20

✨ Enable staging notebooks & code using the CLI

---

lamindb/dev/_data.py
lamindb/dev/_run_context.py

- https://github.com/laminlabs/lamin-cli/pull/21

🚸 Account for run not yet being saved

---

lamindb/_artifact.py
lamindb/_registry.py

- https://github.com/laminlabs/lamindb-setup/pull/624
- https://github.com/laminlabs/lamindb-setup/pull/621
- https://github.com/laminlabs/lamindb-setup/commit/98e2fcbdd94e7171b2e8660601ed0b91359dfa4a

♻️ Refactor storage settings

---

docs/storage/upload.ipynb
lamindb/_artifact.py

- https://github.com/laminlabs/lamindb-setup/pull/630
- https://github.com/laminlabs/lamindb-setup/pull/626

✨ Enable to use hosted storage on S3

---

lamindb/_artifact.py
lamindb/_filter.py
lamindb/_registry.py
lamindb/dev/_settings.py
lamindb/dev/storage/file.py

- https://github.com/laminlabs/lamindb-setup/pull/633
This needs to be thoroughly refactored.

✨ Enable to change the default database

---

lamindb/_collection.py

- https://github.com/laminlabs/lamindb/issues/1409

🎨 Make `Collection.save()` ACID

---

docs/bionty-base.md
noxfile.py
pyproject.toml

- https://github.com/laminlabs/lamin-cli/pull/22

♻️ Use Click for CLI

---

lamindb/_artifact.py
lamindb/_filter.py
lamindb/_registry.py
lamindb/_save.py
lamindb/_validate.py
lamindb/dev/_feature_manager.py
lamindb/dev/_label_manager.py
lamindb/dev/_settings.py
lamindb/dev/storage/_backed_access.py
lamindb/dev/storage/file.py
lamindb/dev/versioning.py
tests/test_artifact.py
tests/test_save.py
tests/test_storage.py

https://laminlabs.slack.com/archives/C04FPE8V01W/p1706952822066209

♻️ Thread-safe multi-instance mode

---

pyproject.toml

https://github.com/laminlabs/lamindb/issues/1428

📌 Pin nbstripout for now

---

lamindb/_validate.py

:sparkles: Unique validation values

---

lamindb/dev/storage/_backed_access.py
lamindb/dev/storage/_zarr.py

https://github.com/laminlabs/lamindb/issues/1444

🐛 Fix zarr saving for hosted instances

---

lamindb/__init__.py
lamindb/dev/_run_context.py
lamindb/dev/_transform_settings.py

https://laminlabs.slack.com/archives/C04FPE8V01W/p1708628942566499

♻️ Draft transform settings

---

lamindb/_artifact.py
lamindb/_storage.py

- https://github.com/laminlabs/laminapp-ui/pull/450

♻️ Add ability to pass through access_token

---

lamindb/_transform.py
lamindb/core/_run_context.py
tests/test_notebooks.py
tests/test_run_context.py
tests/test_transfer.py

https://laminlabs.slack.com/archives/C04FPE8V01W/p1709461578252109
- https://github.com/laminlabs/lamin-cli/pull/30
- https://github.com/laminlabs/lamin-cli/pull/31

♻️ Refactor transform update dialogue, more tests

---

lamindb/core/_mapped_collection.py

📝 Improve docs and make some methods private for MappedCollection

---

lamindb/_artifact.py
lamindb/_collection.py
lamindb/core/storage/file.py
tests/test_artifact.py
tests/test_delete.py

Currently raise a warning, but maybe we want to silence it in the future.

🚸 Disable delete data from non-default storage

---

docs/data.ipynb
docs/storage/prepare-transfer-local-to-cloud.ipynb
lamindb/__init__.py
lamindb/setup/__init__.py
noxfile.py
pyproject.toml
tests/conftest.py

- https://github.com/laminlabs/lamindb-setup/pull/674
- https://github.com/laminlabs/bionty/pull/12

🚸 Restore `auto_connect=True` on `lamin init`

---

lamindb/core/_run_context.py

- https://github.com/laminlabs/lamin-cli/pull/40

🚸 Upload script source code and environment during `ln.track()`

---

lamindb/_transform.py
lamindb/core/_run_context.py
tests/test_transform.py

- https://github.com/laminlabs/lnschema-core/pull/353

🚚 Rename `transform.short_name` to `transform.key`

---

lamindb/core/_mapped_collection.py
lamindb/core/storage/file.py
tests/test_collection.py

https://github.com/laminlabs/lamindb/pull/1502

✨ Return storage_idx in MappedCollection

---

lamindb/core/_run_context.py
pyproject.toml

- https://github.com/laminlabs/lnschema-core/pull/355

♻️ Add a json field to `Run`

---

lamindb/__init__.py
lamindb/_finish.py
lamindb/_query_set.py
lamindb/_run.py
lamindb/core/_data.py
lamindb/core/_run_context.py

- https://github.com/laminlabs/laminhub/issues/30#issuecomment-2015305155
- https://github.com/laminlabs/lamin-cli/pull/41

♻️ Refactor `ln.finish` for notebooks

---

noxfile.py

I fat fingered the last PR for reasons

♻️ Simplify nox build

---

lamindb/_artifact.py
lamindb/_finish.py
lamindb/_save.py
lamindb/core/storage/file.py
tests/test_artifact.py
tests/test_cache.py
tests/test_save.py
tests/test_storage.py

https://github.com/laminlabs/lamindb-setup/pull/687

✨ Improved functionality for directory artifacts

---

lamindb/__init__.py
lamindb/core/_data.py
lamindb/integrations/__init__.py
lamindb/integrations/_vitessce.py
pyproject.toml

- https://github.com/laminlabs/lamin-spatial/pull/14

♻️ Add vitessce integration

---

docs/introduction.ipynb
docs/tutorial.ipynb
lamindb/_annotate.py
lamindb/integrations/_vitessce.py
noxfile.py
pyproject.toml
tests/test_queryset.py
tests/test_run_context.py
tests/test_versioning.py

- https://github.com/laminlabs/lnschema-core/pull/360
- https://github.com/laminlabs/lamin-cli/pull/43
- https://github.com/laminlabs/lamin-cli/pull/44

✨ Introduce `Registry.get()` and `lamin get` (replaces `lamin stage`)

---

docs/annotate.ipynb
docs/introduction.ipynb
lamindb/_annotate.py
tests/test_annotate.py

I'd wish to include the following: https://laminlabs.slack.com/archives/C04MU979KD3/p1711877946203819
But I don't know how to do it so fast.

♻️ Refactor Annotator

---

lamindb/_finish.py
pyproject.toml
tests/test_run_context.py

- https://github.com/laminlabs/lamin-cli/pull/45

✨ Add ability to upload arbitrary files or folders from CLI

---

.github/workflows/build.yml
lamindb/_artifact.py
lamindb/_collection.py
lamindb/core/_feature_manager.py
lamindb/core/storage/file.py
lamindb/core/types.py
lamindb/setup/core/__init__.py
noxfile.py
tests/test_run_context.py

- https://github.com/laminlabs/lnschema-core/pull/363
- https://github.com/laminlabs/lamindb-setup/pull/707
- https://github.com/laminlabs/lamindb-setup/pull/709

🏷️ Fix more typing issues, also test on python 3.9

---

pyproject.toml
tests/test_run_context.py

- https://github.com/laminlabs/lamin-cli/pull/46
- https://github.com/laminlabs/lamindb-setup/pull/712

🐛 Fix clashes for multi process

---

lamindb/core/storage/_backed_access.py
pyproject.toml
tests/test_storage.py

⬆️ Upgrade anndata dependency

---

docs/introduction.ipynb
docs/tutorial2.ipynb
lamindb/core/_data.py
lamindb/core/_label_manager.py

There is so much going on in our docs. So, I suggest making emojis simpler:
[♻️ Simplify emojis in describe()](https://github.com/laminlabs/lamindb/pull/1556/commits/832392e65abd90608406765ee016aa3aa71dc402)

📝 Improve introduction

---

lamindb/_annotate.py

Fixes https://github.com/laminlabs/lamin-usecases/issues/115

🐛 Fix passing organism to Annotate

---

docs/faq/idempotency.ipynb
lamindb/_artifact.py
lamindb/_collection.py

https://laminlabs.slack.com/archives/C04FPE8V01W/p1713279788956569
- https://github.com/laminlabs/lnschema-core/pull/370

🚸 Update data lineage information in case transform is re-run

---

docs/faq/track-run-inputs.ipynb
docs/introduction.ipynb
docs/storage.md
docs/storage/add-replace-stage.ipynb
docs/tutorial.ipynb
docs/tutorial2.ipynb
lamindb/_artifact.py
lamindb/_collection.py
lamindb/core/_settings.py
lamindb/core/datasets/_core.py
tests/test_artifact.py
tests/test_collection.py
tests/test_load.py

https://www.notion.so/laminlabs/Data-sharing-through-hybrid-local-remote-LaminDB-instances-e01025ed0e3e4f06948c4390894f20a8
- https://github.com/laminlabs/lamindb-setup/pull/717
- https://github.com/laminlabs/lnschema-core/pull/369
- https://github.com/laminlabs/lamin-cli/pull/48

🚚 Deprecate `stage()` in favor of `cache()`

---

lamindb/_finish.py
lamindb/core/_run_context.py
tests/notebooks/with-title-initialized-consecutive-finish-not-last-cell.ipynb
tests/test_run_context.py

Address
- https://github.com/laminlabs/lamindb/issues/1570

♻️ Simplify `ln.finish()`

---

lamindb/_artifact.py
lamindb/_collection.py
pyproject.toml

- https://github.com/laminlabs/lnschema-core/pull/371

🐛 Distinguish replicated output collections from artifacts

---

lamindb/_finish.py
tests/notebooks/with-title-initialized-consecutive-finish-not-last-cell.ipynb
tests/notebooks/with-title-initialized-consecutive-finish.ipynb

This is safer than relying on the user.

🚸 Replace `i_saved_the_notebook` with timestamp comparison

---

docs/storage.md
docs/storage/vitessce.ipynb
lamindb/core/storage/__init__.py
lamindb/core/storage/_valid_suffixes.py
lamindb/integrations/_vitessce.py
noxfile.py
pyproject.toml

See the example here:
- https://github.com/laminlabs/lamin-spatial/pull/16
Needs:
- https://github.com/laminlabs/lamindb-setup/pull/718/

♻️ Separate `VitessceConfig` from its referenced datasets

---

lamindb/_artifact.py
lamindb/_collection.py
tests/test_artifact.py
tests/test_collection.py

Address:
- https://github.com/laminlabs/lamindb/issues/1586

🚸 Update metadata like description upon re-running

---

docs/introduction.ipynb
docs/storage/vitessce.ipynb
docs/tutorial.ipynb
tests/conftest.py

- https://github.com/laminlabs/lamindb-setup/pull/725

🚸 In `.setup.delete()`, check for data deletion & delete from hub

---

lamindb/_save.py

https://github.com/laminlabs/lamindb-setup/pull/739/

✨ Proper progress bars for upload and download

---

docs/data.ipynb
docs/faq.md
docs/faq/keep-artifacts-local.ipynb
docs/introduction.ipynb
docs/storage/add-replace-stage.ipynb
docs/storage/upload.ipynb
docs/storage/vitessce.ipynb
docs/transfer.ipynb
lamindb/__init__.py
lamindb/_artifact.py
lamindb/_finish.py
lamindb/core/_run_context.py
lamindb/core/_settings.py
lamindb/core/storage/paths.py
noxfile.py
pyproject.toml
tests/conftest.py
tests/test_cache.py
tests/test_run_context.py

Also: Make it easy to keep some artifacts local.
Needs:
- https://github.com/laminlabs/lamindb-setup/pull/738
- https://github.com/laminlabs/lnschema-core/pull/374

✨ Manage multiple storage locations with integrity

---

lamindb/core/datasets/_core.py

Partially fixes #1612 
Can't test atm, will test tomorrow

 🐛Escape \ properly for anndata_mouse_sc_lymph_node dataloader

---

lamindb/core/storage/__init__.py
lamindb/core/storage/_valid_suffixes.py
pyproject.toml

Needs:
- https://github.com/laminlabs/lamindb-setup/pull/746

♻️ Extend valid suffixes to composite suffixes

---

docs/faq/keep-artifacts-local.ipynb
lamindb/_artifact.py
lamindb/_save.py
tests/conftest.py
tests/test_artifact.py

Fix:
- https://github.com/laminlabs/lamindb/issues/1616

♻️ Upon upload switch to virtual key

---

.gitignore
docs/introduction.ipynb
docs/tutorial.ipynb
docs/tutorial2.ipynb
lamindb/core/_run_context.py
pyproject.toml

Eliminate ipylab dependency:
- https://github.com/laminlabs/nbproject/pull/282
Do no longer call `nbproject.header()` just for getting pypackages. This also eliminates redundant logging messages that was visible in the tutorial.

♻️ Refactor nbproject usage & tutorials

---

lamindb/_run.py
lamindb/_transform.py
lamindb/core/_run_context.py
lamindb/core/versioning.py
pyproject.toml
tests/test_run_context.py
tests/test_transform.py

✨ Enable to add parameters to `ln.track()`

---

lamindb/_artifact.py

https://github.com/laminlabs/lamindb-setup/pull/761

⚡️ Speed-up file hash

---

lamindb/_from_values.py

Introduced in https://github.com/laminlabs/lamindb/pull/1657/files and clutters our docs

:bug: Remove debugging print statements

---

docs/changelog.md
docs/storage/prepare-transfer-local-to-cloud.ipynb
docs/tutorial2.ipynb
lamindb/__init__.py
lamindb/_annotate.py
lamindb/_feature.py
lamindb/_feature_set.py
lamindb/_registry.py
lamindb/core/_feature_manager.py
tests/conftest.py
tests/test_feature.py
tests/test_feature_manager.py
tests/test_feature_set.py

https://www.notion.so/laminlabs/Better-annotation-flow-support-non-categorical-data-bulk-annotation-programmatic-access-28e8a9e6804b42dba84f2485c22e7a1a
Needs:
- https://github.com/laminlabs/lnschema-core/pull/379

🚸 Better annotation flow: support non-categorical data, dictionary annotation & dictionary access (I)

---

.gitmodules
docs/storage/transfer-local-to-cloud.ipynb
lamindb/__init__.py
noxfile.py
tests/test_annotate.py
tests/test_feature.py
tests/test_feature_manager.py
tests/test_transfer.py

Also: This starts to protect Feature on link tables between artifact & labels.
It turned out that the migration state turned out invalid and I had to do another refactor of all old migration files:
- https://github.com/laminlabs/lnschema-core/pull/381
- https://github.com/laminlabs/lnschema-bionty/pull/243
- https://github.com/laminlabs/wetlab/pull/51
This was the initial attempt:
- https://github.com/laminlabs/wetlab/pull/49
- https://github.com/laminlabs/lnschema-core/pull/380
- https://github.com/laminlabs/lnschema-bionty/pull/241
Here is the logic for the actual link tables:
- https://github.com/laminlabs/lnschema-bionty/pull/239
We decided to no longer link collection directly against bionty, as there is some danger for confusion with links via Artifact:
- …

🏗️ Re-design link tables between `Bionty` & `Artifact` to account for `Feature`

---

lamindb/_annotate.py
lamindb/_artifact.py
lamindb/_collection.py
lamindb/_feature.py
lamindb/_feature_set.py
lamindb/_registry.py
lamindb/core/_data.py
lamindb/core/_feature_manager.py
lamindb/core/_label_manager.py
lamindb/core/datasets/_core.py
lamindb/core/schema.py
tests/test_feature.py
tests/test_feature_manager.py
tests/test_feature_set.py
tests/test_queryset.py

https://laminlabs.slack.com/archives/C046F63LJJ2/p1715940665403049

♻️ Rename `.type` to `.dtype` in `Feature` and `FeatureSet` & refactor feature types

---

docs/introduction.ipynb
docs/tutorial.ipynb
docs/tutorial2.ipynb
lamindb/_collection.py
lamindb/core/_data.py
lamindb/core/_feature_manager.py
lamindb/core/_label_manager.py
lamindb/core/schema.py
tests/test_annotate.py
tests/test_artifact.py
tests/test_can_validate.py
tests/test_collection.py
tests/test_feature.py
tests/test_feature_manager.py
tests/test_feature_set.py
tests/test_label_manager.py
tests/test_queryset.py

- https://github.com/laminlabs/lnschema-bionty/pull/246
- https://github.com/laminlabs/lnschema-core/pull/384
- https://github.com/laminlabs/lnschema-core/pull/383
- https://github.com/laminlabs/lnschema-bionty/pull/245

🏗️ Protect deletion in link tables, better names for link tables, maintain integrity upon label & feature renames

---

lamindb/_artifact.py
lamindb/_collection.py
lamindb/_run.py
lamindb/core/_feature_manager.py
lamindb/core/_run_context.py
tests/test_run_context.py

- https://github.com/laminlabs/lnschema-core/pull/385
- https://github.com/laminlabs/lnschema-bionty/pull/247

♻️ Reformulate data lineage, remove json field from run

---

docs/introduction.ipynb
tests/test_run_context.py

Stupid oversight by myself.
Shouldn't yet have announced for 0.72 -- will be in the next patch.

🐛 Actually add tracking run for entities beyond Artifact & Collection

---

docs/tutorial.ipynb
lamindb/_artifact.py
lamindb/_finish.py
lamindb/_save.py
lamindb/core/datasets/_core.py
lamindb/core/storage/paths.py
tests/test_artifact_folders.py

https://laminlabs.slack.com/archives/C04FPE8V01W/p1716465031234849
- https://github.com/laminlabs/lamindb-setup/pull/772

🚸 Make `upload_from()`, `download_to()`, and `view_tree()` more user friendly

---

lamindb/_artifact.py
lamindb/core/schema.py

https://github.com/laminlabs/lamindb-setup/pull/723

⬆️ Migrate to upath 0.2.2

---

lamindb/_registry.py

All the work done by @fredericenard here:
- https://github.com/laminlabs/lamindb-setup/pull/774

🏗️ Instantly synchronize instance schema with the hub

---

lamindb/_view.py

fixes https://github.com/laminlabs/lamindb/issues/1693

🐛 Import IPython inside view

---

lamindb/_artifact.py
tests/test_artifact.py

🐛 Fix check_path_is_child_of_root for upaths with different storage_options

---

pyproject.toml

⬆️ Upgrade anndata to 0.10.8

---

lamindb/_artifact.py
lamindb/core/storage/_backed_access.py
noxfile.py
tests/test_storage.py

✨ Artifact.backed() for tiledbsoma stores

---

.github/workflows/build.yml
noxfile.py

📝 Better CLI docs

---

lamindb/_artifact.py
lamindb/_collection.py
lamindb/_feature.py
lamindb/_feature_set.py

Thanks to @chaichontat!
https://laminlabs.slack.com/archives/C04FPE8V01W/p1721261696616179

🐛 Fix return values of `.save()` for a few classes

---

pyproject.toml

- https://github.com/laminlabs/lamindb-setup/pull/802
- https://github.com/laminlabs/nbproject/pull/284

⬆️ Upgrade to pydantic v2

---

CONTRIBUTING.md

Partially fixes https://github.com/laminlabs/lamindb/issues/1765
There can always be more detail but this was just a few minutes or work.
1. Added more details on how to work with the submodules.
2. Added more details to how the documentation is generated.

✨ Add more details to contributors guide

---

lamindb/_can_validate.py

Fix create message

---

lamindb/_can_validate.py
lamindb/_from_values.py
lamindb/_record.py
lamindb/_save.py
lamindb/_view.py
lamindb/core/_data.py
lamindb/core/schema.py

♻️ Replace ORM with Record or Registry

---

lamindb/_curate.py

✨ Allow exclude values in Curate.validate

---

docs/storage/vitessce.ipynb
lamindb/core/storage/__init__.py
lamindb/core/storage/_valid_suffixes.py
lamindb/integrations/_vitessce.py

Uses `artifact._actions` to store a reference to the Vitessce config `.json` artifact. Documented as follows [here](https://docs.lamin.ai/lamindb.integrations.save_vitessce_config):
Needed:
- https://github.com/laminlabs/lamindb-setup/pull/815
- https://github.com/laminlabs/lnschema-core/pull/416
This is how suffixes are now documented:

🚸 In Vitessce integration, enable a Vitessce button next to a dataset, also, document valid suffixes

---

lamindb/_run.py
lamindb/core/_label_manager.py

- https://github.com/laminlabs/lnschema-core/pull/417

🎨 Make some more backward accessors private and type the rest

---

lamindb/core/datasets/_core.py

Fixes https://github.com/laminlabs/lamindb/issues/1806

🎨 Adopt new MuDat push/pull interface

---

lamindb/core/datasets/_core.py
run-tests/.lamindb/_is_initialized

🐛Fix Papalexi missing hto:technique

---

lamindb/_can_validate.py
lamindb/_from_values.py
tests/test_uid.py

Allow configuring source for any entity that inherits BioRecord via `registry.add_source`

✨ Allow add source to entity

---

lamindb/_curate.py

🐛 Fix passing source to curate.add_from_validated

---

lamindb/_curate.py

Fixes https://github.com/laminlabs/lamindb/issues/1825

:memo: Add reference to cxg in from_anndata

---

lamindb/_artifact.py
lamindb/core/storage/__init__.py
lamindb/core/storage/_tiledbsoma.py
lamindb/integrations/__init__.py
tests/test_storage.py

https://github.com/laminlabs/lamindb/pull/1823
https://github.com/laminlabs/lamindb/pull/1827
https://github.com/laminlabs/lamin-usecases/pull/141

♻️ New tiledbsoma API: `save_tiledbsoma_experiment`

---

lamindb/core/_mapped_collection.py
tests/core/test_collection.py

https://github.com/laminlabs/lamindb/issues/1845

🐛 Check for csc_matrix in MappedCollection and raise error

---

lamindb/_curate.py
tests/core/test_curate.py

:bug: Fix validating no passed categoricals

---

docs/api.md
docs/laminr.md
docs/readfcs.md
docs/tutorial.ipynb
lamindb/_artifact.py
lamindb/core/_label_manager.py

Will refactor so that `HasFeatures` disappears in one of the next PRs.

📝 Link `laminr` and fix docs

---

lamindb/core/storage/_tiledbsoma.py

Read local adatas in backed mode for writing to a tiledbsoma store.

⚡️ Improvements to `save_tiledbsoma_experiment`

---

lamindb/_transform.py

This currently only affects `save_vitessce_config()`.

🐛 Fix query for latest version in manual transform constructor

---

lamindb/_artifact.py
lamindb/_collection.py
lamindb/core/__init__.py
lamindb/core/_data.py
lamindb/core/_feature_manager.py
lamindb/core/_label_manager.py
tests/core/test_feature_manager.py

- https://github.com/laminlabs/lnschema-core/pull/427

♻️ Replace inheriting from `HasFeatures` & `HasParams` with composition

---

lamindb/_artifact.py
lamindb/_collection.py
pyproject.toml

- https://github.com/laminlabs/lnschema-core/pull/430
- https://github.com/laminlabs/bionty/pull/104

📝 Fix all registry docs

---

lamindb/core/_data.py
tests/core/test_collection.py

Introduced the bug just in the PR before, was caught by integration test. Also adding test here.

🐛 Fix `collection.describe()`

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

🎨 Fix issue templates labels

---

lamindb/_curate.py

Fixes #1922 
Not sure what the best of conveying "remove broken" values is. I went for "non-existent" but uhhm not sure.

✨ Improve curation save terms msg

---

docs/storage/prepare-transfer-local-to-cloud.ipynb
docs/storage/transfer-local-to-cloud.ipynb
lamindb/core/storage/_tiledbsoma.py
tests/storage/test_storage.py

Fixes https://github.com/laminlabs/lamindb/issues/1919

✨ Add n_observations to tiledbsoma artifacts

---

lamindb/_artifact.py
lamindb/core/loaders.py

Fix https://github.com/laminlabs/lamindb/issues/1935

🎨  Remove `stream` argument from `artifact.load()`

---

lamindb/_artifact.py
lamindb/_save.py
lamindb/core/storage/_backed_access.py
lamindb/core/storage/paths.py
tests/core/test_artifact.py
tests/core/test_cache.py

Solve https://github.com/laminlabs/lamindb/issues/1949

✨ Store artifacts under their virtual keys in cache

---

tests/core/test_cache.py

💚 Fix flaky cache test

---

docs/track.ipynb

Before | After
--- | ---
Revises advice given below:
- https://github.com/laminlabs/lamindb/pull/1977

📝 Revise advice on managing notebook templates

---

lamindb/_can_validate.py
lamindb/_record.py

Addresses:
- https://github.com/laminlabs/lamindb/issues/1937
- https://github.com/laminlabs/lamindb/issues/1968

🎨 Move `.from_values()` from `Record` to `CanValidate`

---

docs/tutorial.ipynb

https://github.com/laminlabs/lamindb/issues/2014

📝 Use `anon=True` access for `UPath.view_tree()` in tutorial

---

lamindb/_query_set.py
lamindb/core/_context.py

Resolves:
- https://github.com/laminlabs/lamindb/issues/2004
Via:
- https://github.com/laminlabs/lnschema-core/pull/441
Effects a few minor changes, e.g., 
- 💄 Show `created_at` rather than `updated_at`
- 🚸 Update transform name if notebook title changes just before `finish()`
- https://github.com/laminlabs/lamin-cli/pull/85
- https://github.com/laminlabs/lamin-cli/pull/86

♻️ Some minor improvements

---

lamindb/_record.py

https://github.com/laminlabs/lamindb-setup/pull/879

♻️ Migrate to edge function in `connect()`

---

.gitmodules
docs/api.md
docs/cellregistry.md
docs/omop.md
docs/ourprojects.md
noxfile.py

Add 3 submodules: omop, cellregistry, ourprojects. Homogenize the landing page documentation across modules.

🍱 Add `omop`, `cellregistry`, `ourprojects`

---

lamindb/_artifact.py

https://github.com/laminlabs/lamindb-setup/pull/887

♻️ Move cloud_to_local to lnamindb_setup.settings

---

lamindb/_curate.py
tests/core/test_curate.py

Fixes https://github.com/laminlabs/lamindb/issues/2088

🐛 Fix TypeError

---

lamindb/_curate.py

- Proper singular/plural messages for Curator stdout

🐛 Proper numerous for Curator stdout

---

lamindb/_curate.py
tests/core/test_curate.py

Resolves: https://github.com/laminlabs/lamindb/issues/2098

🐛 Fix registering Gene columns in DataFrameCurator

---

lamindb/_record.py

Resolves: https://github.com/laminlabs/bionty/issues/137

🐛 Fix hard-coded "name" field during search

---

docs/ehrcurator.py

Maybe a better example given recent discussions on recording Curator versions

🎨 Make EHRCurator immutable

---

noxfile.py

https://github.com/laminlabs/lamindb-setup/pull/899

⬆️ Upgrade fsspec to 2024.10.0

---

lamindb/_record.py
tests/core/test_record.py

Applies an additional rule when searching for similar names on initializing `Record`.

⚡️ Additional search rule for truncated searches

---

lamindb/core/storage/paths.py
tests/core/test_artifact.py

Fix https://github.com/laminlabs/lamindb/issues/2204

🐛 Check protocol first in check_path_is_child_of_root

---

pyproject.toml

Fix [this ](https://github.com/laminlabs/lamindb/issues/2214)

🩹 Add a lower bound on nbconvert to avoid problems with lxml

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/enhancement.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/usage_question.yml

They are now modeled on the design of the GitHub issue that also leverages parallelism & minimalism where possible.

👷 Simplify issue templates

---

docs/curate-subclass.ipynb
docs/ehrcurator.py

Fixes https://github.com/laminlabs/lamindb/issues/2229

🎨 Fix EHRCurator warning & validation

---

lamindb/core/loaders.py
noxfile.py
tests/core/test_artifact.py

Builds on and extends https://github.com/laminlabs/lamindb/pull/2172

✨ Add an artifact loader for .yaml

---

pyproject.toml

https://github.com/laminlabs/lamin-utils/pull/97

⬆️ Upgrade lamin-utils to 0.13.10 (escape search string in bionty search)

---

lamindb/core/_feature_manager.py
tests/core/test_describe_df.py
tests/core/test_feature_label_manager.py

Fix typos introduced here:
- https://github.com/laminlabs/lamindb/pull/2259

✏️ Fix typos in describe sections

---

.gitmodules
docs/api.md
docs/findrefs.md
docs/includes/installation.md
docs/omop.md
noxfile.py
pyproject.toml

Before:
```bash
pip install "lamindb[aws,bionty,jupyter,ourprojects]"
```
After:
```bash
pip install "lamindb[bionty,jupyter]"
```
Before | After
--- | ---
- https://github.com/laminlabs/lamindb/issues/2301

🚸 Simplify installation & API overview

---

lamindb/_from_values.py

Resolves: https://github.com/laminlabs/lamindb/issues/2255

🐛 Fix source in from_values

---

.pre-commit-config.yaml
lamindb/_transform.py
lamindb/core/_feature_manager.py

💚 Fix downstream integration tests

---

lamindb/_finish.py
lamindb/core/_context.py

`ln.finish()` can now also be re-run in Python in case the user doesn't end up saving in the editor.
This builds on the UX that we already introduce for RStudio in the previous PR:
- https://github.com/laminlabs/lamindb/pull/2375

🚸 Enable users to re-run `ln.finish()` and better resolve multiple users attempting to edit the same notebook draft

---

lamindb/curators/_spatial.py
tests/curators/test_curator.py

Fixes https://github.com/laminlabs/lamindb/issues/2389
- Improves bad argument and error handling for the `SpatialDataCurator`

🐛 Fix sample level metadata optional

---

docs/storage/upload.ipynb
pyproject.toml

See https://github.com/laminlabs/lamindb-setup/pull/956
https://github.com/supabase/storage-py/issues/343

⬆️ Remove the bound on storage3

---

lamindb/core/_describe.py

Fixes the warning message for artifacts in trash.
Though it did sound like a cool dis before 😄

🚸 Fix warning about artifacts in trash

---

lamindb/core/storage/paths.py

Avoids resolving http paths with a request during artifact registration, also makes artifact registration safer for cloud paths.

⚡️ Safer resolve in check_path_is_child_of_root

---

noxfile.py

https://github.com/laminlabs/lamindb-setup/pull/963

⬆️ Upgrade fsspec packages (s3fs, gcsfs, universal_pathlib)

---

lamindb/curators/__init__.py
tests/core/test_context.py
tests/curators/test_cat_curators.py

Fixes https://github.com/laminlabs/lamindb/issues/2430

🐛 Fix `var_index` standardization of `SpatialDataCurator`

---

lamindb/curators/__init__.py

♻️ Prettify AnnDataCurator implementation

---

docs/arrays.ipynb

Show to to use `ln.Collection.open()` in the tutorial.

📝 Show `ln.Collection.open()` in arrays.ipynb

---

docs/arrays.ipynb
docs/setup.ipynb

Explain how to pass s3-compatible endpoint urls.

📝 Add endpoint_url option to docs

---

lamindb/curators/__init__.py
tests/curators/test_dataframe_curators_accounting_example.py

Fixes https://github.com/laminlabs/lamindb/issues/2496

🐛 Fix `.add_new_from` message

---

.github/workflows/build.yml
.pre-commit-config.yaml
lamindb/models/__init__.py
noxfile.py
tests/permissions/conftest.py
tests/permissions/jwt_utils.py
tests/permissions/scripts/setup_access.py
tests/permissions/scripts/setup_instance.py
tests/permissions/scripts/setup_models.py
tests/permissions/test_permissions.py
tests/permissions/utils.py

Test basic functionality for fine-grained permissions.

✅ Test fine-grained permissions

---

pyproject.toml

Has important fix for vs code https://github.com/laminlabs/nbproject/pull/287

⬆️  Upgrade nbproject

---

lamindb/models/query_set.py
tests/core/test_describe_and_df_calls.py

Fixes:
- https://github.com/laminlabs/lamindb/issues/2520

🚸 Do not evaluate filter on feature annotations in `.df(features=True`)

---

docs/curate-any.ipynb
pyproject.toml

Upgrades the dependencies to get the docs working again.

⬆️ Upgrade lamin-cli & bionty & lamin-utils

---

lamindb/curators/__init__.py
lamindb/models/_feature_manager.py
tests/curators/test_curators_quickstart_example.py

This PR implements a schema-based `MuDataCurator`.
Example:
```python
perturbation = ln.ULabel(name="Perturbation", is_type=True).save()
ln.ULabel(name="Perturbed", type=perturbation).save()
ln.ULabel(name="NT", type=perturbation).save()
replicate = ln.ULabel(name="Replicate", is_type=True).save()
ln.ULabel(name="rep1", type=replicate).save()
ln.ULabel(name="rep2", type=replicate).save()
ln.ULabel(name="rep3", type=replicate).save()
obs_schema = ln.Schema(
name="mudata_papalexi21_subset_obs_schema",
features=[
ln.Feature(name="perturbation", dtype="cat[ULabel[Perturbation]]").save(),
ln.Feature(name="replicate", dtype="cat[ULabel[Replicate]]").save(),
],
).save()
obs_schema_rna = ln.Schema(
name="mudata_papalexi21_subset_rna_obs_schema",
features=[
ln.Feature(name="nCount_RNA", …
```

✨ Implement MuDataCurator

---

.github/workflows/build.yml
tests/permissions/scripts/setup_access.py

https://github.com/laminlabs/laminhub/pull/2207

💚 Fix permissions test

---

.gitignore
lamindb/core/datasets/_core.py
lamindb/curators/__init__.py
tests/curators/test_curators_general.py
tests/curators/test_curators_quickstart_example.py

fixes
- https://github.com/laminlabs/lamindb/issues/2519
- https://github.com/laminlabs/lamindb/issues/2429
Adds a new Schema based SpatialDataCurator. Example:
```python
import bionty as bt
sample_schema = ln.Schema(
name="blobs_sample_level_metadata",
features=[
ln.Feature(name="assay", dtype=bt.ExperimentalFactor).save(),
ln.Feature(name="disease", dtype=bt.Disease).save(),
ln.Feature(name="development_stage", dtype=bt.DevelopmentalStage).save(),
],
coerce_dtype=True
).save()
blobs_obs_schema = ln.Schema(
name="blobs_obs_level_metadata",
features=[
ln.Feature(name="sample_region", dtype="str").save(),
],
coerce_dtype=True
).save()
blobs_var_schema = ln.Schema(
name="blobs_var_schema",
itype=bt.Gene.ensembl_gene_id,
dtype=int
).save()
spatialdata_schema = ln.Schema( …
```

✨ Add Schema based SpatialDataCurator

---

lamindb/curators/__init__.py
lamindb/curators/_cellxgene_schemas/__init__.py
lamindb/curators/_cellxgene_schemas/schema_versions.csv
tests/curators/test_cxg_curator.py

- Supports: https://github.com/chanzuckerberg/single-cell-curation/blob/main/schema/5.2.0/schema.md
- Fix column checking of `donor_id`
- Add test of `to_cellxgene_anndata`
- Removed `.adata` attribute since all operations are inplace
- Move more cxg schema related code into `_cellxgene_schemas/`

✨ Support CELLxGENE schema 5.2.0

---

tests/permissions/test_permissions.py

https://github.com/laminlabs/lamindb-setup/pull/987

⬆️ Upgrade lamind-setup (fine-grained permissions)

---

pyproject.toml

```
% lamin get https://lamin.ai/laminlabs/lamin-site-assets/artifact/e2G7k9EVul4JbfsEYAy5
Artifact .png
└── General
├── .uid = 'e2G7k9EVul4JbfsEYAy5'
├── .path = s3://lamin-site-assets/.lamindb/e2G7k9EVul4JbfsEYAy5.png
├── .created_by = falexwolf (Alex Wolf)
├── .created_at = 2022-09-24 07:37:10
└── .transform = 'Elyra pipeline'
```
```
% lamin load https://lamin.ai/laminlabs/lamindata/collection/2wUs6V1OuGzp5Ll40000
... synchronizing PO5F1.fasta: 100.0%
... synchronizing MYC.fasta: 100.0%
... synchronizing SOX2.fasta: 100.0%
... synchronizing KLF4.fasta: 100.0%
→ collection paths (4 files):
→   [1/4] /Users/falexwolf/Library/Caches/lamindb/lamindata/fasta/PO5F1.fasta
→   [2/4] /Users/falexwolf/Library/Caches/lamindb/lamindata/fasta/MYC.fasta
→   [3/4] …
```

✨ Add `lamin get` for artifacts and `lamin load` for collections

---

docs/curate-df.ipynb
lamindb/core/datasets/_small.py
lamindb/curators/__init__.py
lamindb/models/feature.py
lamindb/models/schema.py
tests/core/test_describe_and_df_calls.py
tests/core/test_record.py
tests/curators/test_cat_managers.py
tests/curators/test_curators_quickstart_example.py

Before | After
--- | ---
Before | After
--- | ---
[Postview](https://90a2e5f4.lamindb.pages.dev/curate-df). | [Preview](https://d53698ae.lamindb.pages.dev/curate-df).

📝 Clean up curators API docs & the main curator guide

---

docs/faq/key.ipynb

📝 Fix faq/key

---

lamindb/curators/__init__.py
lamindb/models/_from_values.py
tests/core/test_from_values.py
tests/curators/test_cat_managers.py

https://github.com/laminlabs/bionty/pull/215

♻️ Refactor default source configuration

---

lamindb/curators/__init__.py
lamindb/models/_from_values.py
lamindb/models/can_curate.py
tests/curators/test_cat_managers.py

- Refactored `import_source`: https://github.com/laminlabs/bionty/pull/216
- Refactored organism configuration in CatManagers
- Eliminated settings.verbosity code in curators

♻️ Refactor organism in curators

---

lamindb/models/_feature_manager.py
lamindb/models/_label_manager.py

This PR enables transferring of a label that is associated with multiple features.

🐛 Enable transferring features pointing to multiple labels

---

tests/permissions/scripts/setup_access.py

Most importantly for this https://github.com/laminlabs/lamindb-setup/pull/1008

⬆️ Upgrade lamindb-setup and adapt permissions test to laminhub refactor

---

lamindb/models/record.py

- https://github.com/laminlabs/bionty/pull/228

🐛 Fix transfer through reticulate when target instances has no schema modules

---

.github/workflows/build.yml
tests/permissions/scripts/setup_access.py
tests/permissions/test_permissions.py

https://github.com/laminlabs/laminhub/pull/2277

✅ Test allowing SELECT on space all for jwt role by default

---

lamindb/models/project.py

🏷️ Fix typing in `ULabelProject` and `PersonProject`

---

pyproject.toml
tests/storage/test_transfer.py

Close https://github.com/laminlabs/lamindb/issues/2603
Also some fixes for tests.

⬆️ Upgrade anndata to 0.11.4

---

noxfile.py

https://github.com/laminlabs/lamindb-setup/pull/1014

⬆️ Upgrade fsspec packages to 2025.3.2 

---

lamindb/curators/__init__.py

Do this same for CatManager as in https://github.com/laminlabs/lamindb/pull/2632

🎨 Skip validation if a missing cat feature is not required

---

.github/workflows/build.yml
lamindb/models/record.py
noxfile.py
tests/permissions/scripts/check_lamin_dev.py
tests/permissions/scripts/setup_access.py
tests/permissions/test_permissions.py

Paired with:
- https://github.com/laminlabs/lamindb-setup/pull/1015

🐛 Set db token only on the transaction level

---

.github/workflows/build.yml
tests/permissions/test_permissions.py

https://github.com/laminlabs/laminhub/pull/2355

✅ Test writing to the default space through team

---

lamindb/curators/__init__.py

On lamindata running:
```python
df = pd.DataFrame(
{"CD8A": [1, 2, 3], "CD4": [3, 4, 5], "CD14": [5, 6, 7], "perturbation": ["DMSO", "IFNG", "DMSO"], "cell_type_by_expert": ["B cell", "T cell", "T cell"], "cell_type_by_model": ["B cell", "T cell", "T cell"]},
index=["sample1", "sample2", "sample3"],
)
adata1 = ad.AnnData(
df[["CD8A", "CD4", "CD14"]], obs=df[["perturbation", "cell_type_by_expert", "cell_type_by_model"]]
)
curator = ln.Curator.from_anndata(adata1, var_index=bt.Gene.symbol, categoricals={"perturbation": ln.ULabel.name, "cell_type_by_expert": bt.CellType.name,  "cell_type_by_model": bt.CellType.name}, organism="human")
```
Before | After
--- | ---

🐛 Fix re-validation of `var_index`

---

.github/workflows/build.yml
docs/faq.md
docs/faq/pydantic-pandera.ipynb

New FAQ doc.
Preview: https://ee7ed2fa.lamindb.pages.dev/faq/pydantic-pandera

🍱 Compare lamindb with pydantic and pandera in an FAQ doc

---

lamindb/models/_feature_manager.py

Prevent projects being displayed as features.

🐛 Fix describe features

---

.github/workflows/build.yml
tests/permissions/test_permissions.py

https://github.com/laminlabs/laminhub/pull/2383

✅ Decrypt token inside RLS (adapt tests)

---

.github/workflows/build.yml
tests/permissions/test_permissions.py

https://github.com/laminlabs/laminhub/pull/2388

✅ Temp table based authentication (adapt tests)

---

lamindb/errors.py
lamindb/models/record.py
noxfile.py
tests/permissions/test_permissions.py

Closes https://github.com/laminlabs/pfizer-lamin-usage/issues/201
RLS error looks like this now:

🥅 Catch and clarify RLS error on `Record.save()`

---

lamindb/curators/_legacy.py
lamindb/curators/core.py

This PR is just a rename of `CatColumn` to `CatVector` and `CatColumn.labels` to `CatVector.records`.

♻️ Clearer naming conventions in the internal curator codebase

---

lamindb/models/record.py

Fix https://github.com/laminlabs/lamindb/issues/2721

🔊 Fix modules warning in `.using`

---

docs/registries.ipynb
lamindb/core/_context.py
lamindb/curators/core.py
lamindb/models/_feature_manager.py
lamindb/models/artifact.py
lamindb/models/feature.py
lamindb/models/has_parents.py
lamindb/models/query_set.py
lamindb/models/schema.py
tests/core/test_describe_and_df_calls.py
tests/core/test_feature_label_manager.py
tests/core/test_queryset.py
tests/core/test_schema.py
tests/core/test_track.py

Need to add more tests and refactor docs. But this fixes several things that we need in a release right now, so I'll merge it.

🚸 For artifacts, improve (1) bulk annotation with features + (2) queries by features

---

lamindb/models/artifact.py
lamindb/models/query_set.py
lamindb/models/sqlrecord.py

Backward compat after
- https://github.com/laminlabs/lamindb/pull/2791

🚸 Add backward compat for `_branch_code`

---

lamindb/curators/core.py

Fixes #2777 
Extracted from https://github.com/laminlabs/lamindb/pull/2769

🔈 Fix Pandera warning

---

pyproject.toml

Fix https://github.com/laminlabs/lamindb/issues/2810

⬆️ Add a lower bound on pandera

---

lamindb/models/_feature_manager.py
tests/core/test_feature_label_manager.py

🐛 Fix query feature associated labels from non-ULabel registries

---

lamindb/models/save.py
tests/core/test_save.py

Resolves https://github.com/laminlabs/lamindb/issues/2158

🎨 Batch save

---

lamindb/models/query_manager.py
lamindb/models/sqlrecord.py
pyproject.toml

See https://github.com/laminlabs/lamin-utils/pull/100

🚸 Add keep with default "first" to Lookup

---

lamindb/models/_feature_manager.py
lamindb/models/query_set.py
lamindb/models/sqlrecord.py
tests/storage/test_transfer.py

Fixes the two problems mentioned above.

🐛 Have transfer comply with `settings.annotation.n_max_records` and fix a bug related to repeated schema transfer

---

lamindb/core/_settings.py
lamindb/models/storage.py

Before | After
--- | ---
Also see:
- https://github.com/laminlabs/lamin-docs/pull/276

📝 Improve storage docs

---

lamindb/models/feature.py
tests/core/test_dtype.py

Handles nested dtypes like `cat[ULabel[Sample[BioSample]]]`.

🎨 Support nested cat dtypes

---

lamindb/models/artifact.py

Fixes problems like this one:
`FAILED tests/lambda/test_create_artifact.py::test_create_artifact_parallel - Exception: {'message': 'Artifact creation failed -- IntegrityError: duplicate key value violates unique constraint "lamindb_storage_uid_key"\nDETAIL:  Key (uid)=(u13SdUaEq6E6) already exists.\n', 'stack_trace': 'Traceback (most recent call last):\n  File "/var/lang/lib/python3.12/site-packages/django/db/backends/utils.py", line 105, in _execute\n    return self.cursor.execute(sql, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\npsycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "lamindb_storage_uid_key"\nDETAIL:  Key (uid)=(u13SdUaEq6E6) already exists.\n\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most …

🐛 Fix parallel artifact registration with hub storage

---

.github/workflows/build.yml
tests/permissions/test_permissions.py

https://github.com/laminlabs/laminhub/pull/2726

✅ Testing for cache spaces for RLS

---

.github/workflows/build.yml
tests/permissions/scripts/setup_access.py
tests/permissions/test_permissions.py

Tests for https://github.com/laminlabs/laminhub/pull/2610

✅ Test fine-grained access for single records

---

.github/workflows/build.yml
tests/permissions/test_permissions.py

Test this https://github.com/laminlabs/laminhub/pull/2779

✅ Test simplify link tables RLS

---

lamindb/models/artifact.py
lamindb/models/sqlrecord.py
lamindb/models/storage.py
tests/core/test_storage.py

Refactors this:
- https://github.com/laminlabs/lamindb/pull/2854
Makes it parallel to how deal with this for artifacts and transforms.
Also adds some comments and clarifies storage access management docs, by pointing out the "Connect S3 bucket" button.

♻️ Refactor how to deal with parallel storage creation

---

lamindb/models/artifact.py

Needed mostly for central, so i missed this at first.

🐛 Fix saving an artifact with `using`

---

lamindb/core/storage/_backed_access.py
lamindb/core/storage/_polars_lazy_df.py
tests/storage/test_streaming.py

Fix https://github.com/laminlabs/lamindb/issues/2916 https://github.com/laminlabs/pfizer-lamin-usage/issues/282

⚡️ Use native `polars` Object Store by default

---

lamindb/models/_django.py
tests/core/test_models.py

Fixes https://github.com/laminlabs/lamindb/issues/2594
| Before | After |
| ------ | ----- |
| ![Before message](https://github.com/user-attachments/assets/51944625-b8b7-45ad-9252-ee6341da3d70) | ![After message](https://github.com/user-attachments/assets/3d570ec8-cbb6-4a20-9f03-c4326335df7c) |

🚸 Improve UX for labeling unsaved records from other instances

---

lamindb/core/_settings.py

Fixes https://github.com/laminlabs/lamindb/issues/2920

🐛 Fix Settings sphinx __repr__

---

docs/faq/keep-artifacts-local.ipynb
lamindb/core/_settings.py
lamindb/models/artifact.py
lamindb/models/feature.py
lamindb/models/storage.py
tests/storage/conftest.py

Before | After
--- | ---
Before | After
--- | ---
- https://github.com/laminlabs/lamindb-setup/pull/1087

🚸 Improve the experience of working in `keep-artifacts-local` mode

---

lamindb/models/schema.py
tests/core/test_schema.py

Resolves: https://github.com/laminlabs/lamindb/issues/2918

🐛 Fix creation of a `Schema` with `is_type=True`

---

lamindb/core/storage/_polars_lazy_df.py
lamindb/core/storage/_tiledbsoma.py

https://github.com/laminlabs/lamindb-setup/pull/1093

⬆️ Upgrade lamindb-setup to fix `UPath.to_url`

---

README.md
lamindb/models/_describe.py
tests/core/test_describe_and_df_calls.py

Comes with:
- https://github.com/laminlabs/lamin-docs/pull/284

📝 Polish README and `artifact.describe()`

---

lamindb/curators/core.py
tests/curators/test_curators_general.py

Resolves: https://github.com/laminlabs/lamindb/issues/2958

🐛 Create records under subtype via `Curator.add_new_from`

---

lamindb/models/_describe.py
lamindb/models/_django.py
lamindb/models/artifact.py
lamindb/models/collection.py
tests/core/test_artifact.py
tests/core/test_collection.py
tests/core/test_describe_and_df_calls.py

Fixes https://github.com/laminlabs/lamindb/issues/2974
| Before | After |
| ------ | ----- |
| ![Before message](https://github.com/user-attachments/assets/64ec5a24-80a8-4cb2-b9c6-eda0de5230d1) | ![After message](https://github.com/user-attachments/assets/24b44206-25e4-43ed-9a1f-9826ccf632ad) |
- Adds Collection specific fetch and describe code
- Adds more thorough tests for `Artifact.describe()` and `Collection.describe()`

✨ Add Collection.describe()

---

docs/storage/vitessce.ipynb
lamindb/integrations/_vitessce.py
lamindb/models/artifact.py

Introduces artifact `kind = "__lamindb_config__"` so that we can hide these config files by default.

🚸 Hide `VitessceConfig` artifacts

---

.github/workflows/build.yml
tests/permissions/scripts/setup_access.py

https://github.com/laminlabs/laminhub/pull/3107

✅ Test yet another RLS optimization

---

docs/faq/pydantic-pandera.ipynb
docs/scripts/define_schema_spatialdata.py
lamindb/base/__init__.py
lamindb/base/dtypes.py
lamindb/curators/core.py
lamindb/models/_feature_manager.py
tests/curators/test_curators_examples.py

This PR extends `AnnDataCurator` and `MuDataCurator` to support validation of (nested) dictionaries in `.uns` slots, similar to how `SpatialDataCurator` handles `attrs`. Now, you can define schema slots targeting arbitrarily deep paths in `.uns` for both AnnData and MuData objects. It further improves error handling.
**1. Validate a nested dict in AnnData `.uns`:**
```python
adata = ln.core.datasets.small_dataset1(otype="AnnData")
adata.uns["study_metadata"] = {"temperature": 21.6, "experiment_id": "EXP001"}
uns_schema = ln.Schema(
features=[
ln.Feature(name="temperature", dtype=float).save(),
ln.Feature(name="experiment_id", dtype=str).save(),
],
).save()
anndata_schema = ln.Schema(
otype="AnnData",
slots={
"uns:study_metadata": uns_schema,
},
).save()
curator = …
```

✨ Unstructured slot validation of scverse datastructures

---

lamindb/models/query_set.py
lamindb/models/storage.py
pyproject.toml
tests/permissions/scripts/check_lamin_dev.py

Restores the test that was accidentally deleted in the second-to-last commit in the previous PR:
- https://github.com/laminlabs/lamindb/pull/3023
Makes the space-based access management test that hits `laminlabs/lamin-dev` idempotent.

♻️ Amend storage access tests

---

docs/arrays.ipynb
lamindb/models/artifact.py

Documents how to use https://github.com/laminlabs/lamindb/pull/3051 in arrays.
Addresses https://github.com/laminlabs/pfizer-lamin-usage/issues/335

📝 Add documentation on how to use `ln.Artifact.from_lazy`

---

lamindb/migrations/0120_add_record_fk_constraint.py

🐛 Fix ambiguity in `is_valid_record_type`

---

lamindb/models/_feature_manager.py
lamindb/models/artifact.py
lamindb/models/artifact_set.py
lamindb/models/query_set.py
lamindb/models/run.py
tests/core/test_queryset.py
tests/storage/test_transfer.py

This PR makes it possible to query by features across instances:
```python
ln.Artifact.using("laminlabs/cellxgene").filter(n_of_donors__gte=100)
```
Supersedes:
- https://github.com/laminlabs/lamindb/pull/3060
Fixes https://github.com/laminlabs/pfizer-lamin-usage/issues/339

✨ Query by feature across instances

---

lamindb/models/sqlrecord.py

Fix https://github.com/laminlabs/lamindb/issues/3072

🐛 Fix space warning on sqlite and local instances

---

docs/bio-registries.ipynb
docs/faq/curate-any.ipynb
docs/guide.md
docs/manage-ontologies.ipynb
lamindb/models/can_curate.py
noxfile.py

Related:
- https://github.com/laminlabs/lamin-docs/pull/312

📝 Polish bio-registries / manage-ontologies guide

---

docs/track.ipynb
lamindb/core/_context.py
tests/core/notebooks/no-title.ipynb

Needs:
- https://github.com/laminlabs/lamindb-setup/pull/1148
- https://github.com/laminlabs/lamin-cli/pull/157

✨ Introduce a `work_dir` setting and use it to auto-create a notebook or script `key` during `ln.track()`

---

lamindb/curators/_legacy.py
lamindb/models/block.py

And add `# pragma: no cover` for legacy `TiledbsomaCatManager`.

📝 Fix docstrings of block models
