laminlabs/lamindb

- lamindb/dev/db/_add.py
subj, and adds optional arguments to `ln.add` to pass `use_fsspec` if needed.
https://github.com/laminlabs/lamindb/issues/360
> 🩹 Restore default `fsspec` for upload

- docs/guide/02-schema.ipynb
- lamindb/_check_versions.py
- lamindb/schema/__init__.py
- pyproject.toml
- https://github.com/laminlabs/lamindb/issues/366
> 🎨 Simplify schema module handling

- docs/guide/07-link-samples.ipynb
- lamindb/_check_versions.py
- lamindb/_delete.py
- lamindb/_load.py
- lamindb/dev/db/_add.py
- lamindb/dev/db/_core.py
- lamindb/dev/db/_select.py
- pyproject.toml
- https://github.com/laminlabs/lndb-setup/pull/99
> 🏗️ Persist the session

- lamindb/_check_versions.py
- pyproject.toml
By upgrading lnschema_core to 0.25.3.
> 🚸 Auto-populate relationship-associated foreign key fields

- docs/guide/07-session.ipynb
- lamindb/_check_versions.py
- pyproject.toml
By upgrading `lnschema-core` to 0.25.8.
> 🔥 Disable ORM relationship preview

- docs/guide/03-add-delete.ipynb
- lamindb/_delete.py
- lamindb/dev/db/_add.py
MultipleResultsFound error will be raised with:
- `ln.add(Entity, **kwargs)`
- `ln.delete(Entity, **kwargs)`
Log whether `.add` returns an existing entry
> 🎨 Disable multiple select results for .add and .delete by fields

- docs/faq/ingest-folder.ipynb
- docs/faq/stream.ipynb
- docs/guide/03-add-delete.ipynb
- lamindb/__init__.py
- lamindb/_check_versions.py
- lamindb/_delete.py
- lamindb/_folder.py
- lamindb/_record.py
- lamindb/dev/_core.py
- lamindb/dev/db/_add.py
- lamindb/schema/__init__.py
- pyproject.toml
- Moved `lns.DFolder` to `ln.DFolder`
- Implemented `ln.DFolder(folder=...)`
- Updated the ingest-folder notebook to reflect the API change
- Implemented `DFolder.tree()` to visualize files inside a DFolder
- Added DFolder._objectkey when DFolder is a folder/directory: https://github.com/laminlabs/lnschema-core/pull/113
---
- Coming up in the next PR: `DFolder.load_dobject(relative_path)`
> 💥 Move `lns.DFolder` to `ln.DFolder`

- .github/workflows/build.yml
- .gitmodules
- docs/faq/data-validation.ipynb
- docs/faq/ingest.ipynb
- docs/faq/session.ipynb
- docs/faq/track-runin.ipynb
- docs/guide/03-files.ipynb
- docs/guide/08-run.ipynb
- docs/guide/15-query-book.ipynb
- lamindb/__init__.py
- lamindb/_check_versions.py
- lamindb/_context.py
- lamindb/_load.py
- lamindb/_nb.py
- lamindb/_record.py
- lamindb/dev/db/_add.py
- noxfile.py
- pyproject.toml
- tests/test_db.py
Instead of all the specificity for notebooks, notebooks and pipelines are now treated on an equal footing.
Along with
- https://github.com/laminlabs/lnschema-core/pull/133
Below is all gone and got replaced with `ln.Run(global_context, load_latest=True)`.
Everything is 100% backward compatible.
> 🏗️ Introduce `lamindb.context` and enable `ln.Run` to create contexts

- lamindb/_check_versions.py
- lamindb/schema/__init__.py
- pyproject.toml
- https://github.com/laminlabs/lndb/pull/340
> 🚸 Check schema version upon instance init

- docs/guide/08-run.ipynb
- lamindb/_check_versions.py
- lamindb/_context.py
- lamindb/dev/db/_add.py
- pyproject.toml
- https://github.com/laminlabs/lnschema-core/pull/154
- https://github.com/laminlabs/lnschema-core/pull/155
> 🎨 Simplify `ln.track()` and add `app` transform type

- lamindb/_check_versions.py
- lamindb/_context.py
- pyproject.toml
Also:
- 🚸 Add a is_db_setup() check after init and make it more robust
- 🚸 Enable non-owner to set storage
> 🚸 Allow registering local postgres instances on the hub

- lamindb/_context.py
> 🐛 Fix VS Code notebook reinitialization in track

- docs/faq/03-notebooks.ipynb
- docs/guide/02-provenance.ipynb
- docs/guide/03-select.ipynb
- lamindb/__init__.py
- lamindb/_amend_file.py
- lamindb/_check_versions.py
- lamindb/_context.py
- pyproject.toml
Transform was the only without a universal id for 2 days now - a relict of Django not supporting composite primary keys
This is now mitigated through introducing a stem_id that characterizes the notebook up to version
We also remove the title field and instead introduce a short_name field
- https://github.com/laminlabs/lnschema-core/pull/186
> 🏗️ Re-architect transform id

- lamindb/_folder.py
> 🔊 `folder.tree` can only be used with existing folders in storage

- docs/guide/04-stream.ipynb
- lamindb/dev/storage/object/_anndata_accessor.py
This allows to load subsets of AnnData into memory as actual AnnData objects.
This allows `File.backed()` to supersede `File.stream()`.
> ✨ Add to_adata method to AnnDataAccessor

- docs/guide/01-files-folders.ipynb
- docs/storage/add-replace-stage.ipynb
- lamindb/_amend_file.py
- lamindb/_delete.py
- lamindb/_file.py
- lamindb/_file_access.py
- lamindb/_save.py
We don't like to clutter the root of storage locations anymore, anticipating that users will use auto-storage keys together with semantic keys.
> 🚸 Prefix auto-storage-key with `lndb/`

- docs/storage/upload.ipynb
We had this with SQLAlchemy already, now we have it again:
- https://github.com/laminlabs/lamindb-setup/pull/419
> ✅ Add integrity tests for migrations back

- pyproject.toml
- https://github.com/laminlabs/lnschema-bionty/pull/127
> 🎨 Consolidate `lnschema_bionty` and upgrade to latest Bionty

- docs/guide/04-stream.ipynb
- lamindb/_file.py
- lamindb/dev/storage/_backed_access.py
More consistency across cloud-backed and disk-backed! Hope this is OK, @Koncopd!
> 🚸 Return locally backed object instead of cloud backed if available, rename `to_adata()` to `to_memory()`

- docs/faq/notebooks.ipynb
- lamindb/_context.py
subj
also includes fixes for `reinitialize_notebook` (`transform.id` was passed before instead of `transform.stem_id`).
> ✨ Detect interactive environments and other fixes for ln.track()

- docs/biology/01-registries.ipynb
- docs/biology/04-samples.ipynb
- docs/guide/02-data-lineage.ipynb
- docs/guide/03-select.ipynb
- lamindb/_orm.py
- pyproject.toml
With https://github.com/laminlabs/lamin-logger/pull/37.
Added `return_queryset` to return a queryset from `search`
> 🔥 Remove `top_hit` param from search

- lamindb/_from_values.py
- tests/test_from_values.py
As discussed, @sunnyosun, I'm pretty sure we'll have much less headache if we completely remove `map_synonyms` from any automated and validation-related functionality.
It's a great curation tool, but can make things much more complicated if it silently acts under-the-hood.
Less magic should also lead to less bugs. Testing the scenario we encountered before refactoring the below would be very complicated itself.
- https://github.com/laminlabs/lamin-usecases/pull/19
> 🚸 Ignore `synonyms` in `from_values` to incentivize explicit curation process

- lamindb/_file.py
- lamindb/dev/fields.py
- tests/test_file.py
- Ref:https://laminlabs.slack.com/archives/C046F63LJJ2/p1691411480442009?thread_ts=1691403669.946449&cid=C046F63LJJ2
- https://github.com/laminlabs/lnschema-core/pull/263
---
In a nutshell:
New tests:
> ✨ Enable versioning of files

- lamindb/_file.py
- lamindb/_storage.py
- lamindb/dev/storage/file.py
- https://github.com/laminlabs/lamindb-setup/pull/486
> ♻️ Use `create_path`

- lamindb/_save.py
- tests/test_cache.py
This is to avoid duplication for in-memory data on local instances. 
On `file = File(data) ` the in-memory `data` is saved in the cache folder and then copied to the root on `file.save()`. `data` is thus in the cache and in the root. This removes the cached file on `file.save()` to avoid this duplication.
> ⚡️ Delete cached files for local instances on File.save()

- lamindb/_file.py
- lamindb/_save.py
- lamindb/dev/storage/__init__.py
- lamindb/dev/storage/file.py
- lamindb/dev/storage/object.py
- tests/test_file.py
corresponds to https://github.com/laminlabs/lamindb-setup/pull/490
in progress
> ♻️ Refactor to use UPath everywhere

- lamindb/_file.py
- lamindb/_save.py
- lamindb/dev/storage/file.py
- lamindb/dev/storage/object.py
- tests/test_file.py
- Fixes `zarr` or `zrad` objects upload from disk and adds a test for this.
- Adds validation of `key`'s suffix for in-memory objects in `File`.
> 🎨 More validation for `File` creation, fix some aspects of zarr backend

- lamindb/_view.py
- lamindb/schema/__init__.py
This lets a series of simplifications and performance improvements in lamindb-setup go live. More to come.
> ⚡ Speed up instance loading time & refactor lamindb-setup

- lamindb/_filter.py
https://github.com/django/django/blob/679212a47ac3e22a6fbb6ee3cd4c09f29aae8b5d/django/utils/connection.py#L56
https://github.com/django/django/blob/679212a47ac3e22a6fbb6ee3cd4c09f29aae8b5d/django/db/utils.py#L191
Using a specific `DatabaseWrapper` seems to be unneeded, this might be important if we want to add support for databases other than sqlite and postgres.
> ♻️ Do not use `DatabaseWrapper` directly

- docs/storage/add-replace-stage.ipynb
- lamindb/_file.py
- lamindb/_filter.py
- lamindb/dev/_settings.py
- lamindb/dev/storage/file.py
- pyproject.toml
- tests/test_file.py
Slack: https://laminlabs.slack.com/archives/C04FPE8V01W/p1697280227050649
- https://github.com/laminlabs/lnschema-core/pull/310
TODO:
- Add corresponding test cases to https://github.com/laminlabs/lamindb/blob/7caa9c510cbb8dac283de895bb202826aa7530cf/docs/storage/add-replace-stage.ipynb or turn into parametrized test
- Adopt `File.view_tree()` to run on `key` instead of on paths depending on `settings.file_use_virtual_keys`
> 🚸 Introduce virtual keys

- docs/storage/add-replace-stage.ipynb
- lamindb/_file.py
Now forbids to replace from a `Storage`. 
We can allow to replace from the same `Storage` as tied to the `File`, but then `key` should be changed to real from virtual.
> ✨ Change replace to work with virtual keys

- lamindb/dev/_mapped_dataset.py
- lamindb/dev/storage/_backed_access.py
- tests/test_dataset.py
- tests/test_storage.py
> ✨ Add context manager to File.backed and Dataset.mapped

- lamindb/dev/_mapped_dataset.py
- tests/test_dataset.py
Fixes larger weights for larger groups. Thx @jkobject for spotting the problem.
Also adds the possibility to get joint weight from multiple label keys.
> ✨ Fix and extend get_label_weights in Dataset.mapped

- lamindb/_artifact.py
`glob("*")` only gives the first level files and folders.
> 🐛 Fix size and hash for local folders in Artifact

- lamindb/_artifact.py
Hashes were not calculated for all in-memory adatas, it is not correct as we write them to a file before uploading.
> 🐛 Only avoid hashing for in-memory zarr

- lamindb/_collection.py
- lamindb/dev/_mapped_collection.py
- pyproject.toml
- tests/test_collection.py
- https://github.com/laminlabs/lnschema-core/pull/333
> 🎨 Introduce ordered collections and simplify `.mapped()`

- lamindb/dev/_mapped_collection.py
Improves from 1.3k samples per second to 1.9k samples per second with 7 workers.
> ⚡️ A way to improve parallel sampling for Collection.mapped

- docs/faq/setup.ipynb
- docs/introduction.ipynb
- docs/storage/add-replace-stage.ipynb
- docs/storage/anndata-accessor.ipynb
- docs/storage/upload.ipynb
- docs/tutorial.ipynb
- docs/tutorial2.ipynb
- lamindb/__init__.py
- lamindb/_artifact.py
- lamindb/_collection.py
- lamindb/_feature.py
- lamindb/_feature_set.py
- lamindb/_is_versioned.py
- lamindb/_parents.py
- lamindb/_registry.py
- lamindb/_ulabel.py
- lamindb/_validate.py
- lamindb/core/_settings.py
- lamindb/setup/__init__.py
- noxfile.py
- tests/conftest.py
- tests/test_cache.py
This deprecates `lamin load` in favor of `lamin connect` and requires calling `ln.connect()` after importing lamindb unless a discouraged `auto_connect` flag is enabled (it defaults to `False`).
Hence: `lamin connect` is the successor of `lamin load` and `ln.connect()` is the successor of `ln.setup.load()`.
This is a non-breaking change. Until removal, `load` will let lamindb auto-connect to the currently configured environment default instance as it has so far.
The docs now reflect a new working model in which `ln.setup.settings.auto_connect` defaults to `False` and importing lamindb no longer connects to the environment's current default instance. Instead, one now uses `ln.connect()` to connect to any desired instance.
The CLI continues to behave as before but the following is inverted: …
> 🚸 Deprecate `lamin load` in favor of `lamin connect`, require `ln.connect()` unless `auto_connect` is enabled

- lamindb/_transform.py
- lamindb/core/_run_context.py
- lamindb/core/_settings.py
- lamindb/core/_sync_git.py
- tests/test_run_context.py
- tests/test_transform.py
WP: https://www.notion.so/laminlabs/Integrate-lamindb-with-git-e328461d4f34413bbb2b2aecda3ddb89
Upon setting `sync_git_repo`, `ln.track()` will sync the transform references to a github repo:
```
ln.settings.sync_git_repo = "https://github.com/laminlabs/laminlabs/arrayloader-benchmarks"
ln.track()
```
Essentially, you'll get:
```
assert transform.reference == "https://github.com/laminlabs/arrayloader-benchmarks/blob/8b9a73463bbde7c2923fc8f4525003d7d8106738/benchmark_merlin_mapped_census_epochs.py"
```
if the script that you run is at https://github.com/laminlabs/arrayloader-benchmarks/blob/8b9a73463bbde7c2923fc8f4525003d7d8106738/benchmark_merlin_mapped_census_epochs.py.
It works by leveraging the git blob and commit hash.
- …
> ✨ Integrate lamindb with git

- lamindb/_query_set.py
- tests/test_queryset.py
For some reason, we didn't have this before. Now this is possible:
> ✨ Allow including simple related fields in `.df()`

- docs/annotate.ipynb
- docs/faq/key.ipynb
- docs/faq/setup.ipynb
- docs/faq/track-run-inputs.ipynb
- docs/introduction.ipynb
- docs/meta.ipynb
- docs/track.ipynb
- docs/transfer.ipynb
- docs/tutorial.ipynb
- docs/tutorial2.ipynb
- lamindb/__init__.py
- lamindb/core/_run_context.py
- lamindb/core/_settings.py
- lamindb/core/_sync_git.py
- lamindb/core/_transform_settings.py
- tests/notebooks/no-title.ipynb
- tests/test_run_context.py
- https://github.com/laminlabs/lamin-cli/pull/39
> 🚚 Move transform settings into settings

- .github/workflows/build.yml
- noxfile.py
- pyproject.toml
- tests/test_run_context.py
Working on this while being in calls
> 👷 Switch to uv for CI

- lamindb/_collection.py
- lamindb/core/_mapped_collection.py
- lamindb/core/storage/_backed_access.py
- pyproject.toml
- tests/test_collection.py
Also https://github.com/laminlabs/lnschema-core/pull/367
> ✨ Add `.obsm` and  `.layers` to `MappedCollection`

- lamindb/core/storage/_backed_access.py
- tests/test_storage.py
It was broken here https://github.com/laminlabs/lamindb/pull/1577
Also adds a test.
> 🐛 Fix backed for non-adata zarr

- noxfile.py
- pyproject.toml
- https://github.com/laminlabs/lamindb-setup/pull/732
> ♻️ Refactor noxfile and move `aws` and `gcp` extras to `lamindb-setup`

- docs/introduction.ipynb
- docs/storage/transfer-local-to-cloud.ipynb
- docs/transfer.ipynb
- docs/tutorial.ipynb
- docs/tutorial2.ipynb
- lamindb/_artifact.py
- lamindb/_collection.py
- lamindb/_feature_set.py
- lamindb/_filter.py
- lamindb/_finish.py
- lamindb/_from_values.py
- lamindb/_query_set.py
- lamindb/_registry.py
- lamindb/_ulabel.py
- lamindb/core/_data.py
- lamindb/core/_feature_manager.py
- lamindb/core/_label_manager.py
- lamindb/core/_run_context.py
- lamindb/core/_sync_git.py
- lamindb/core/exceptions.py
- lamindb/core/schema.py
- tests/test_feature_manager.py
- tests/test_search.py
- `ln.track()` returns `run`
- better duplicate detection and search
- prettier `.describe()`
- feature values decoupled from feature sets
- more interactivity in `lamin save`
- `create` flag in `.from_values()`
- reorder fields in dataframe & record representations
- auto-detect feature types in dict-style assignment & raise better validation errors
> 🚸 `ln.track()` returns `run`, better duplicate detection and search, prettier `.describe()`, and more

- lamindb/_from_values.py
- lamindb/core/_feature_manager.py
Discussed here: https://laminlabs.slack.com/archives/C04FPE8V01W/p1718821216654699
* Supports `dict` in `infer_feature_type_convert_json`. We expect users to attempt to set `Run.params(dict)` which was not supported before this change.
* Adapts `_print_values` to also support dictionaries
> :sparkles: Support dict in add_values

- docs/bio-registries.ipynb
Simplifies, corrects, and adds this instruction:
```
original_values = ["gut", "gut2"]
validated_status = bt.Tissue.validate(original_values)
validated_values = [value for value, validated in zip(original_values, validated_status) if validated]
records_from_validated_values = bt.Tissue.from_values(validated_values)
ln.save(records_from_validated_values)
```
> 📝 Polish bio-registries how-to

- docs/annotate-flexible.ipynb
- docs/annotate.ipynb
- docs/api.md
- docs/arrays.ipynb
- docs/index.md
- docs/introduction.ipynb
- docs/query-search.md
- docs/records.ipynb
- docs/tutorial.ipynb
- lamindb/__init__.py
- noxfile.py
- pyproject.toml
Also: 
- Rename meta.ipynb to records.ipynb and data.ipynb to arrays.ipynb
- Expose django.db.models.Q as lamindb.Q
- Rename docs section `reference` to `API`
> 📝 Refactor docs, including annotate guide

- .github/workflows/build.yml
- CONTRIBUTING.md
- docs/includes/installation.md
- docs/setup.ipynb
- noxfile.py
It's now pleasant to use: 
```
nox -s install
```
There is a contributing guide at `CONTRIBUTING.md` at the root of the repo, linked from the installation section in the docs.
> 👷 Add a contributing guide, make installation from GitHub easier

- lamindb/_can_validate.py
- lamindb/_curate.py
- lamindb/_record.py
- tests/test_curate.py
- tests/test_transfer.py
Now raise error if the instance of `source` or `organism` record doesn't match the using instance.
> 🐛 Fix `using_key` for source and organism

- lamindb/core/__init__.py
- lamindb/core/_data.py
- lamindb/core/_feature_manager.py
This stresses that every `Record` comes with a `Registry` in form of its metaclass.
As the metaclass maps 1:1 on the corresponding SQL table, this is also what we intuitively understand as "registry".
Hence: Sub-classing `Record` defines a new registry while instantiating `Record` defines a new record.
- https://github.com/laminlabs/lnschema-core/pull/414
- https://github.com/laminlabs/lamindb-setup/pull/814
> 🚚 Rename `RecordMeta` to `Registry`

- docs/api.md
- docs/bio-registries.ipynb
- docs/introduction.ipynb
- lamindb/_curate.py
1. Fixes @falexwolf requests concerning bioregistry
2. Fixes #1793 
To be merged after https://github.com/laminlabs/lamindb/pull/1790 because it references not yet merged attributes.
> 📝 Improve curate docs

- .github/workflows/build.yml
- lamindb/__init__.py
- lamindb/_artifact.py
- lamindb/_collection.py
- lamindb/_query_set.py
- lamindb/_record.py
- lamindb/_transform.py
- lamindb/core/versioning.py
- tests/test_artifact.py
- tests/test_versioning.py
- https://github.com/laminlabs/lnschema-core/pull/419
Note: This is part of this [work package](https://www.notion.so/laminlabs/Simplify-versioning-in-LaminDB-8ef6fc7bfbdc44aca7c8dc672d611dc2).
> ⚡️ Add boolean field `IsVersioned.is_latest` to speed up queries for latest versions

- lamindb/core/_mapped_collection.py
- lamindb/core/storage/_valid_suffixes.py
- tests/test_collection.py
https://github.com/laminlabs/lamindb/pull/1809
This add the features requested by @jkobject 
>checking variables are aligned across datasets
I have added a function `check_vars_non_aligned` that returns a list of objects' indices that are not aligned with the provided variables list.
```
mapped = MappedCollection(...)
mapped.check_vars_non_aligned(var_list) # returns a list of indices of objects with non-aligned variables
```
I haven't added this check by default because in general it is not needed when `join="inner"` or `"outer"` is used, but i think it is fine to have as a separate function.
>checking that variables are sorted across datasets
I have added `check_vars_sorted`
```
mapped.check_vars_sorted(ascending=True) # returns True if sorted in ascending order …
```
> ✨ New features for MappedCollection

- .github/workflows/build.yml
- docs/introduction.ipynb
- docs/tutorial.ipynb
- lamindb/_artifact.py
- lamindb/_collection.py
- lamindb/_finish.py
- lamindb/_is_versioned.py
- lamindb/_record.py
- lamindb/_transform.py
- lamindb/core/_context.py
- lamindb/core/storage/_tiledbsoma.py
- lamindb/core/versioning.py
- tests/test_artifact.py
- tests/test_artifact_folders.py
- tests/test_collection.py
- tests/test_storage.py
- tests/test_transform.py
- tests/test_versioning.py
For `Artifact`, you can now also create revisions by passing the `key` argument.
We're no longer auto-creating "semantic versions", but make labeling with the semantic version optional.
Technical changes:
- 🚚 Deprecate the `is_new_version_of` argument in favor of `revises`
- Deprecate passing `version` to constructors; rather set `.version` after creating records
- [♻️ Remove auto-incrementing the semantic `version` tag, auto-increment the `ruid` instead](https://github.com/laminlabs/lamindb/pull/1839/commits/91576e78c58ae1224ac851c2b8895b33ac829746)
- https://github.com/laminlabs/lnschema-core/pull/423
> 🚸 Enable versioning artifacts based on `key` akin to the AWS S3 behavior

- docs/curate-df.ipynb
- lamindb/__init__.py
- lamindb/_curate.py
- lamindb/core/__init__.py
Addresses:
- https://github.com/laminlabs/lamindb/issues/1861
A follow-up PR will address below issue:
- https://github.com/laminlabs/lamindb/issues/1860
> 🚚 Deprecate `Curate` in favor of `Curator` and make `CuratorBase` the base class of `DataFrameCurator`

- lamindb/__init__.py
- lamindb/_query_set.py
- lamindb/core/__init__.py
While it's more verbose to document inherited class members, it turned out that users get confused if they don't see all available members.
Also, it reminds developers to be as careful as possible with using inheritance: the docs immediately give feedback if an API becomes bloated.
See also:
- https://github.com/laminlabs/lndocs/pull/99
> 📝 Document inherited class members

- lamindb/_curate.py
- tests/core/test_curate.py
Fixes https://github.com/laminlabs/lamindb/issues/1833
- Now raising a `ValueError` when categoricals or sources are passed that do not exist in the columns of the DataFrame.
- We could have added this to the `BaseCurator` but since all implementations currently use the `DataFrameCurator` it's fine like this.
> 🐛 Fix categoricals and sources being checked

- lamindb/_finish.py
- lamindb/core/_context.py
- noxfile.py
- pyproject.toml
- tests/core/test_context.py
This change enables searchability of source code both on the hub and in lamindb by treating source code in the same way as metadata (say ontology descriptions). `transform.source_code` gets stored in a `Text` column in Postgres/SQLite. By all realistic calculations, this will never lead to scalability issues.
Also, we're now
- using the `jupytext` format for notebooks for a cleaner representation of `transform.source_code`
- stripping the notebook title both from run reports and source code to de-duplicate with the `transform.name` field, so that these can no longer get out-of-sync
Adjacent PRs:
- https://github.com/laminlabs/lamin-cli/pull/64
- https://github.com/laminlabs/laminhub/pull/1138
Internal [Slack discussion](https://laminlabs.slack.com/archives/C046F63LJJ2/p1721135617920409).
> 🚸 Make source code searchable

- lamindb/_transform.py
- lamindb/core/_context.py
- tests/core/test_context.py
The bug was introduced 2 weeks ago: https://docs.lamin.ai/changelog/2024#db-0-76-2
It leads to all previous transform revisions to be displayed in the UI.
> 🐛 Fix marking latest transform as `is_latest`

- lamindb/__init__.py
- lamindb/_finish.py
- lamindb/core/_context.py
- noxfile.py
- tests/core/notebooks/with-title-initialized-consecutive-finish-not-last-cell.ipynb
- tests/core/notebooks/with-title-initialized-consecutive-finish.ipynb
- https://github.com/laminlabs/lamin-cli/pull/66
- https://github.com/laminlabs/lamin-cli/pull/67
Also: unify the `LAMIN_TESTING` env variable with the `ln.setup._TESTING`.
- https://github.com/laminlabs/lamindb-setup/pull/843
Resolves: 
- https://github.com/laminlabs/lamindb/issues/1848
`Context()` docs:
before | after
--- | ---
`.finish()` docs:
before | after
--- | ---
`.track()` docs:
before | after
--- | ---
> ✅ Test user input for CLI & improve `Context` docs

- lamindb/_collection.py
- lamindb/_curate.py
- lamindb/core/_feature_manager.py
- tests/core/test_collection.py
- tests/core/test_curate.py
This simplifies the schema enough without sacrificing important use cases.
One can still query the union of the underlying artifact feature sets with `collection.features.get_feature_sets()`, but the result is no longer stored in the database.
- https://github.com/laminlabs/lnschema-core/pull/428
> 🎨 Replace relation of `Collection` to `FeatureSet` with indirect relation through `Artifact`

- lamindb/_artifact.py
- lamindb/core/_settings.py
- tests/storage/test_storage.py
Was deprecated in favor of `open()` here: https://docs.lamin.ai/changelog/2024#db-0-74-2
> 🔥 Remove deprecated `artifact.backed()`

- docs/transfer.ipynb
- lamindb/_record.py
- lamindb/core/_context.py
- lamindb/core/_data.py
- lamindb/core/_feature_manager.py
- lamindb/core/_label_manager.py
- tests/core/conftest.py
- tests/core/test_context.py
- tests/storage/conftest.py
- 🚸 Now raises an error if `is_latest=False` in the to-be-transferred record.
- 📝 Polished the transfer guide.
before | after
--- | ---
before | after
--- | ---
before | after
--- | ---
> 🚸 Better logging during transfer, describe, track() and raise an error if transferring outdated artifact

- docs/arrays.ipynb
- docs/registries.ipynb
- docs/tutorial.ipynb
- lamindb/_artifact.py
- lamindb/_collection.py
- lamindb/_record.py
- lamindb/_transform.py
- lamindb/integrations/_vitessce.py
- tests/core/test_transform.py
For `Transform`, we want to be able to pass a `uid`. If this uid exists, we want to reload the existing record from the database.
We might want to also allow this behavior for other records, but so far we haven't needed it.
> 🐛 Reload transform upon passing same uid

- docs/signup-login.md
- noxfile.py
- Integrate `close` as `--unload` into `load`
- Integrate `logout` as `--logout` into `login`
- Integrate `schema view` as `info view` into `info`
Before | After
--- | ---
Before | After
--- | ---
In `lamin-cli`
- https://github.com/laminlabs/lamin-cli/pull/72
> 🚸 Simplify CLI commands

- lamindb/_artifact.py
- lamindb/core/exceptions.py
- tests/core/test_artifact.py
- tests/core/test_artifact_folders.py
Before | After
--- | ---
Slack discussion: This could be [refined](https://laminlabs.slack.com/archives/C04A0RMA0SC/p1726856875597489).
> 🚸 No traceback for invalid arguments

- docs/track.ipynb
This PR enables storing notebook & script templates in a simple way without the need to build new features or learn more concepts.
Save the template:
```bash
lamin save template1.ipynb --key templates/template1.ipynb --description "Template for analysis type 1" --registry artifact
```
Load the template:
```bash
lamin get https://lamin.ai/account/instance/artifact/Akd7gx7Y9oVOJlei0001
```
Without the `--registry` argument, the save command assumes that `template1.ipynb` is a data transformation with at least one run and errors.
Needs:
- https://github.com/laminlabs/lamin-cli/pull/75
Slack discussion: [here](https://laminlabs.slack.com/archives/C046F63LJJ2/p1723649501286669)
> ✨ Enable notebook and script templates

- lamindb/core/_context.py
- lamindb/core/versioning.py
- tests/core/test_context.py
Before:
```
% python myscript.py  
→ connected lamindb: laminlabs/lamindata
Script filename changed.
Either init a new transform family by setting:
ln.context.uid = "BIck2BoL1HmT0000"
Or update key "mcfarland_2020_preparation.ipynb" in your existing family:
ln.Transform.filter(uid__startswith="13VINnFk89PE").update(key="myscript.py")
```
After:
```
% python myscript.py
→ connected lamindb: laminlabs/lamindata
✗ Filename "myscript.py" clashes with the existing key "mcfarland_2020_preparation.ipynb" for uid "13VINnFk89PE...."
Either init a new transform with a new uid:
ln.context.uid = "IEgwQyRtgI3o0000"
Or update key "mcfarland_2020_preparation.ipynb" to "myscript.py":
ln.Transform.filter(uid__startswith="13VINnFk89PE").update(key="myscript.py")
```
Addresses: 
- …
> 🚸 Better dialogue upon clashing transform keys

- lamindb/_finish.py
- lamindb/core/_context.py
- tests/core/notebooks/not-initialized.ipynb
- tests/core/test_context.py
Main contribution: The new test & example in the PR below:
- https://github.com/laminlabs/lamin-cli/pull/80
Logging:
I meanwhile think that adopting the hub’s truncated 8-char uids in LaminDB can work by omitting the `uid=` prefix in record representations like so:
```
Transform('JjRF4mAC')
Run('DWqJ1af7')
```
This makes the logs much less noisy in parts, makes it easier to talk about a transform or a run, and can be used in `Record.get(truncated_uid)`.
Compare this with the below:
```
Transform(uid='JjRF4mACd9m00000')
Run(uid='DWqJ1af7W8q4tFz5pxQd')
```
> ✅ Add another test for running with tracked params, logging cosmetics

- docs/transfer.ipynb
- lamindb/_record.py
- lamindb/_run.py
- lamindb/core/_data.py
- lamindb/core/_feature_manager.py
- lamindb/core/_label_manager.py
Any transferred artifact now has a special "Transfer" transform as its data source which identifies the source LaminDB instance and the fact that the artifact is transferred.
Before | After
--- | ---
The PR also enables tracking transferred artifacts as inputs without explicitly saving them in a given transform run. This means the following call will now lead to a trace in data lineage:
```
input_artifact = ln.Artifact.using("laminlabs/lamindata").get(description="exemplar-001")
input_artifact.load()
```
Before this PR, it was silently ignored.
> ✨ Track transfers as transforms

- docs/faq/setup.ipynb
- docs/setup.ipynb
- docs/signup-login.md
- docs/storage/prepare-transfer-local-to-cloud.ipynb
- docs/track.ipynb
- docs/tutorial.ipynb
- lamindb/_artifact.py
- lamindb/_collection.py
- lamindb/_curate.py
- lamindb/_feature_set.py
- lamindb/_from_values.py
- lamindb/_query_set.py
- lamindb/_record.py
- lamindb/_save.py
- lamindb/core/_data.py
- lamindb/core/_django.py
- lamindb/core/_label_manager.py
- lamindb/core/_mapped_collection.py
- lamindb/core/_settings.py
- lamindb/core/storage/_anndata_accessor.py
- noxfile.py
- pyproject.toml
This PR implements @ap--'s suggestions to improve the command name consistency of the CLI.
It's backward compatible.
Before | After
--- | ---
Based on the below issue:
- https://github.com/laminlabs/pfizer-lamin-usage/issues/25
Needs:
- https://github.com/laminlabs/lamin-cli/pull/79
> 🚸 `lamin load` → `lamin connect` & `lamin get` → `lamin load`

- docs/scripts/run-track-with-params.py
- docs/scripts/synced-with-git.py
- docs/scripts/synched-script.py
- docs/track.ipynb
- lamindb/_finish.py
- lamindb/core/_context.py
- lamindb/core/_feature_manager.py
- tests/core/test_context.py
This adds two new sections about tracking and querying run parameters to https://docs.lamin.ai/track
Before: 
```bash
→ created Transform(uid='JjRF4mAC8qbE0000') & created Run(started_at='2024-09-26 19:51:58 UTC')`
```
After:
```bash
→ created Transform('JjRF4mAC'), started new Run('O45bXStj') at 2024-09-28 14:26:31 UTC
→ params: input_dir='./mydataset' learning_rate='0.01' downsample='True'
→ finished Run('O45bXStj') after 0:00:00.709727 at 2024-09-28 14:26:31 UTC
```
Before | After
--- | ---
Tracking run parameters has been supported since https://docs.lamin.ai/changelog/2024#db-0-72-0 but has never properly documented.
Needs:
- https://github.com/laminlabs/lamin-cli/pull/82
> 📝 Document how to work with run parameters

- docs/bio-registries.ipynb
- lamindb/_record.py
- lamindb/core/_label_manager.py
- tests/core/test_record.py
This PR adds warnings about:
- inconsistent lamindb versions (greater than minor)
- missing schema modules in the target instance
- in-ability of transferring given labels who don't have a registry in the target instance
Check for version inconsistency was added here:
- https://github.com/laminlabs/lamindb-setup/pull/869
A previous PR silently excepted errors when target registries didn't exist.
- https://github.com/laminlabs/lamindb/pull/1654
Addresses:
- https://github.com/laminlabs/lamindb/issues/1990
> 🚸 Transfer: Warn about inconsistencies between source & target instances

- lamindb/_finish.py
- lamindb/_transform.py
- lamindb/core/_context.py
- lamindb/core/exceptions.py
- lamindb/core/versioning.py
- noxfile.py
Adds a user prompt in case the target file exists to avoid accidental overwrites.
```
! demo.ipynb exists: replace? (y/n)
```
Upon revising a notebook a user so far runs into an error that tells them to manually update the `uid`. To avoid this, the `uid` is now automatically updated upon `lamin load`.
Before:
```
% lamin load https://lamin.ai/laminlabs/lamindata/transform/3qIZOmDUVBwc0000
→ demo.ipynb
```
After:
```
% lamin load https://lamin.ai/laminlabs/lamindata/transform/3qIZOmDUVBwc0000
! demo.ipynb exists: replace? (y/n)y
→ updated uid: 3qIZOmDUVBwc0000 → 3qIZOmDUVBwc0001
→ notebook is here: demo.ipynb
```
The `uid` is only updated for notebooks, not for other transform types and not for artifacts. Only notebooks are essentially guaranteed to be revised once a user loads them. A …
> 🚸 Improve `lamin load` UX for notebooks & scripts

- lamindb/__init__.py
- lamindb/_finish.py
- lamindb/core/versioning.py
- pyproject.toml
- tests/core/test_versioning.py
These numbers are all for querying/connecting `laminlabs/lamindata` (us-east-1) from a laptop in Munich.
Task | Before | After
--- | --- | ---
`lamin load` notebook | ~4.7s | ~2.2s
`lamin connect` (no lamindb reload) | ~4.3s | ~1.0s
`ln.connect()` (with lamindb reload) | ~4.3s | ~2s
The key idea for the speed-up was to lazily reload schema modules and avoid a lamindb import for `lamin load` of a notebook (instead purely relying on Django).
All profiling was done here:
- https://github.com/laminlabs/lamin-cli/pull/84
In addition, needs:
- https://github.com/laminlabs/lamindb-setup/pull/871
- https://github.com/laminlabs/bionty/pull/123
- https://github.com/laminlabs/wetlab/pull/71
> ⚡ Improve performance of `ln.connect()`, `lamin connect`, and `lamin load` for a notebook

- docs/setup.ipynb
- docs/storage/prepare-transfer-local-to-cloud.ipynb
- lamindb/_artifact.py
- lamindb/_finish.py
- lamindb/_record.py
- lamindb/_save.py
- lamindb/core/_settings.py
- lamindb/core/_sync_git.py
- lamindb/core/_track_environment.py
- lamindb/integrations/_vitessce.py
- noxfile.py
- tests/core/test_cache.py
https://github.com/laminlabs/lamindb-setup/pull/875
> ♻️ Move lamindb_setup.settings.storage.cache_dir to lamindb_setup.settings.cache_dir

- lamindb/_artifact.py
- lamindb/_filter.py
Fixes https://github.com/laminlabs/lamindb/issues/2012
Also removes unused imports.
> 🎨 Remove creates one artifact per file in the directory warning

- lamindb/core/_feature_manager.py
- tests/core/test_feature_manager.py
**Before**
You could only query categorical features with string representations of `ULabel`, e.g.,:
```python
ln.Artifact.features.filter(scientist="Barbara McClintock")
```
**After**
Given a categorical feature `"cell_type_by_expert"` with type `cat[bionty.CellType]`, you can now do:
```python
tcell = bt.CellType.get(name="T cell")
artifacts = ln.Artifact.features.filter(cell_type_by_expert=t_cell)
```
Note: The above is a shortcut for the equivalent query:
```python
artifacts = ln.Artifact.filter(links_cell_type__feature__name="cell_type_by_expert", links_cell_type__celltype=t_cell)
```
> 🚸 Query with typed labels through `.features`

- docs/scripts/run-track-with-params.py
- docs/track.ipynb
Before, we didn't have documentation on how to query dictionary-like parameters. Now it's part of the `track` guide: 
The `lamindb.Run` page cross-links this section: https://github.com/laminlabs/lnschema-core/commit/7d14d949f6b295c900bd4a161f4e0794356b7ae4
We also show how run params look on the hub: https://lamin.ai/laminlabs/lamindata/transform/JjRF4mACd9m00001
> 📝 Document how to query by nested run parameters

- lamindb/_query_set.py
Print warning for no-value columns in df include:
> 🐛 Return include fields when one of them is empty

- lamindb/_record.py
- lamindb/core/_data.py
- lamindb/core/_feature_manager.py
- lamindb/core/_label_manager.py
- lamindb/core/exceptions.py
- tests/core/test_data.py
When to error:
1. If a feature is an internal feature, aka it is a member of a featureset.
2. If a label is an internal label, aka it is associated with an internal feature.
To bypass the renaming error:
1. `artifact.features.make_external(feature)`: remove feature from all featuresets.
2. `artifact.labels.make_external(label)`: keep the label associated with artifacts, but remove set `feature=None` in the link tables. This label will no longer associated with any internal faetures.
Full renaming UX:
https://lamin.ai/laminlabs/lamindata/transform/u1s4bAB3sliY0000
> ✨ Error when renaming internal features and labels

- lamindb/_curate.py
Fixes https://github.com/laminlabs/lamindb/issues/1965
- Limits stdout for the respective messages to only 10 max values
- Ensures that values are correctly single quoted
> ✨ Restrict stdout of validation messages of Curator to max 10 terms

- lamindb/_parents.py
- tests/core/test_parents.py
This PR adds `query_parents` and `query_children` methods to `HasParents` class. This allows to query all parents and parents of parents etc. recursively  for all records that have `parents` (instances of subclasses of `HasParents`).
Example:
```
label1 = ln.ULabel(name="label1")
label2 = ln.ULabel(name="label2")
label3 = ln.ULabel(name="label3")
label1.save()
label2.save()
label3.save()
label1.children.add(label2)
label2.children.add(label3)
label3.query_parents() # returns a QuerySet with label1 and label2
label1.query_children() # returns a QuerySet with label2 and label3
```
Closes https://github.com/laminlabs/lamindb/issues/2060
> ✨ Recursively query parents and children

- lamindb/_artifact.py
- lamindb/core/storage/_backed_access.py
- lamindb/core/storage/_pyarrow_dataset.py
- tests/core/test_artifact.py
- tests/storage/test_storage.py
This PR adds functionality to create `pyarrow.dataset.Dataset` from `".parquet", ".csv", ".json", ".orc", ".arrow", ".feather"` files or folders containing these files (partitioned datasets). See [pyarrow.dataset.dataset](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.dataset.html) and [pyarrow.dataset.Dataset](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.Dataset.html).
Example:
```
df = pd.DataFrame({"feat1": [0, 0, 1, 1], "feat2": [6, 7, 8, 9]})
df.to_parquet("save_df", engine="pyarrow", partition_cols=["feat1"])
artifact_folder = ln.Artifact("save_df", description="Partitioned parquet").save()
ds = artifact_folder.open() # get pyarrow.dataset.Dataset
batches = ds.to_batches() # get a streaming iterator over batches
ds.to_table().to_pandas() # read into …
```
> ✨ Stream pyarrow.dataset.dataset supported formats in Artifact.open()

- .github/workflows/build.yml
- pyproject.toml
- Uses 3.12 instead of 3.11 in the CI
- Specifies 3.12 support in our classifiers
- Removes support for Python 3.13
Docs don't build with 3.12:
```
Extension error:
Could not import extension ablog (exception: No module named 'pkg_resources')
```
See https://github.com/laminlabs/lndocs/issues/105
> ✨ Python 3.12 support

- lamindb/_curate.py
> 🐛 Fix list validation in Curator

- pyproject.toml
Context: https://laminlabs.slack.com/archives/C04FPE8V01W/p1729586056058489
We have seen repeatedly that users and developers were trying to install lamindb with additional schemas as extras. This PR adds all lamin schemas as extra dependency groups. This enables the installation of the schemas like:
```pip install lamindb[wetlab]``` just it works for bionty.
> ✨ Add extra groups for all schemas

- lamindb/_can_validate.py
- tests/core/test_can_validate.py
- Limits output of standardized and unsaved values to max 10 values in line with other print limits
- Fixes an intendation issue of the warning output
> ✨ Truncate standardization output

- lamindb/core/_label_manager.py
- tests/storage/test_transfer.py
Resolves: https://github.com/laminlabs/lamindb/issues/2117
> 🐛 Fix transfering artifacts from a source instance with fewer schema modules

- lamindb/_artifact.py
- noxfile.py
- tests/core/test_artifact.py
This PR enables to register paths in Hugging Face repos as Artifacts similar to s3 or gs paths.
Example:
```
artifact = ln.Artifact("hf://datasets/Koncopd/lamindb-test/sharded_parquet").save()
artifact.open()
artifact.cache()
...
```
> ✨ Support Hugging Face paths

- lamindb/_curate.py
Fixes #2110 
- Moves the logging to a more scoped internal function to ensure that only if there's validated values a logging message is printed
- More consistent logging with quotes
- Now always logging "saving record" instead of "saving term". Not sure whether we need to differentiate here?
| Before | After |
| ------ | ------ |
| ![Before Image](https://github.com/user-attachments/assets/c58f8bf1-b818-498c-98f0-f6d6a49c9f61) | ![After Image](https://github.com/user-attachments/assets/e5364974-20c6-4fbe-a0bc-449c55381f1f) |
> 🎨 Improve saving validated output

- lamindb/_curate.py
Fixes https://github.com/laminlabs/bionty/issues/143
- Adds a warning if the `var_index` is `bt.Gene.symbol` to check out the FAQ for more details on why this is bad
- I decided against hard coding a URL because it can change.
- I decided against adding this warning in `curate()` because it would get triggered repeatedly which can be annoying
> ✨ Warn if curating against gene symbols

- docs/arrays.ipynb
Fixes https://github.com/laminlabs/lamindb/issues/2150
- Adds hide-output to cells that emit the "run input was not tracked" warning. At this point, `ln.track()` has not been introduced so we are not using it in the tutorials
- Adds hyperlinks to storage engines that have not been introduced at this point. I am convinced that most users have no idea what they are and just dropping them doesn't work and leaves readers confused. Maybe we need to introduce them in a drop down in 1-2 sentences each while also explaining what a storage engine in general is. For now, I've added hyperlinks that come at the risk of being outdated. However, these URLs should be fairly stable.
> 📝 Add hide-output for some cells & links to storage engines

- lamindb/_finish.py
Before:
`→ finished Run('7xgSkdkp') after 0:10:06.762290 at 2024-11-12 12:14:24 UTC`
After:
`→ finished Run('7xgSkdkp') after 0h 10m 06s at 2024-11-12 12:14:24 UTC`
We can hyperoptimize this by removing leading 0s but I think this is fine.
> ✨ Improve runtime formatting

- lamindb/_record.py
It turned out that in some use cases, it's meaningful to populate the `uid` field with an external id; e.g. from an ELN system.
Hence, we're only validating the internal ids.
Storage and users are exceptions because we might want to change the length at some point in the future (we changed the Storage uid length about 1 year ago from 8 to 12 chars).
> ♻️ Only apply exact length uid constraint for internal entities

- lamindb/_finish.py
- pyproject.toml
You can now run any of
- `lamin save myscript.R`
- `lamin save myanalsyis.qmd`
- `lamin save myanalsyis.Rmd`
The latter two calls will error if the `lamin` CLI doesn't find a file `myanalysis.html` that the user manually created. If the `.html` file is present it will be saved & linked as the latest run report.
Even before this PR, lamindb worked fine with reticulate.
Executing the following script:
```R
library(reticulate)
ln <- import("lamindb")
ln$track("EPnfDtJz8qbE0000", path="test-laminr.R")   # <-- unique id for the script, script path
r_df <- data.frame(
id = 1:5,
value = c(10.5, 20.3, 15.7, 25.1, 30.2),
category = c("A", "B", "A", "C", "B")
)
storage_path <- "example_data.rds"
saveRDS(r_df, storage_path)
ln$Artifact(storage_path, description="Example dataframe")$save()  # save an …
```
> ✨ Support saving R code including `.qmd` and `.Rmd`

- lamindb/core/_context.py
- tests/core/notebooks/not-initialized.ipynb
Before:
```python
>>> ln.track()
→ notebook imports: lamindb==0.76.13
→ to track this notebook, copy & paste `ln.track("TSGPgRifmwuX0000")` and re-run
```
After:
```python
>>> ln.track()
→ to track this notebook, run: ln.track("TSGPgRifmwuX0000")
```
Before:
```python
>>> ln.track()
→ notebook imports: lamindb==0.76.13
→ you already have a transform with key 'test-cross-instance.ipynb' ('Szhz8MJz9g4J0000')
- to make a revision, call `ln.track('Szhz8MJz9g4J0001')`
- to create a new transform, rename your file and run: `ln.track()`
```
After:
```python
>>> ln.track()
→ you already have a transform with key 'test-cross-instance.ipynb': Transform('Szhz8MJz')
(1) to make a revision, run: ln.track("Szhz8MJz9g4J0001")
(2) to create a new transform, rename your notebook file and re-run: …
```
> 🚸 Refactor `ln.track()` to improve logging and method signature

- lamindb/core/loaders.py
- tests/core/test_artifact.py
Warns a user to use `laminr` if the user calls `artifact.load()` which is an `.rds` file
> 🔊 Prompt to use laminr on trying to load .rds files

- lamindb/_record.py
Use the same rule for startswith rank across all packages (`hub`, `lamindb`, `bionty`). Needed due to differences in `pd.Series.str.match`, `sqlalchemy` `regexp_match` and `django` `Regex`.
https://github.com/laminlabs/lamin-utils/pull/95
https://github.com/laminlabs/bionty/pull/170
https://github.com/laminlabs/laminhub/pull/1604
> 🩹 Make search rules the same across all systems

- docs/faq/search.ipynb
- pyproject.toml
https://github.com/laminlabs/bionty/pull/170
https://github.com/laminlabs/lamin-utils/pull/95
Make search in public ontologies via `bionty` consistent with the search in `laminhub` and `lamindb`.
> 🎨 Make search in bionty consistent with the lamindb implementation

- noxfile.py
Problems with `uv` resolver again.
Also `tiledbsoma==1.15.0rc4` seems to be problematic (appending to an existing `tiledbsoma` store fails), i won't try to figure out the problem for now because it is an rc release.
> 💚 Fix tiledbsoma installation in CI

- docs/faq/symbol-mapping.ipynb
- lamindb/_curate.py
Before:
```
! Curating gene symbols is discouraged. See FAQ for more details.
```
After:
```
! indexing datasets with gene symbols can be problematic: https://docs.lamin.ai/faq/symbol-mapping
```
I have a case where I consciously want to use gene symbols for the sake of illustrating something; not for the sake of curating a large body of data.
Hearing some feedback from some users this seems to be very common. So, I'd not make the warning as harsh.
I was missing the URL so that I could read up on this.
Made the warning lowercase consistent with all other logging messages (including warnings).
Replace hanging indentation with vertically aligned indendation.
See: 
- https://github.com/laminlabs/lamindb/issues/2211
> 📝 Prettify gene symbols guide & logging

- lamindb/_feature.py
- lamindb/core/_feature_manager.py
- tests/core/test_feature_manager.py
Note: More comprehensive examples will be added in a follow up PR that will prettify visualizations of features. This PR and the following will be announced together.
Improved annotating artifacts with feature values:
1. support date- and datetime-like feature values with new `dtype` for `Feature`: `"date"` and `"datetime"`
2. clearer feature overview that separates internal from external features
3. enable removing feature value annotations via `artifact.features.remove_values()`
4. consistent handling of annotated values via sets as they come from aggregations, before they were treated as lists
5. refactor the code to simplify and make more maintainable, performance issue still persists though
On the last 3rd point, see https://lamin.ai/laminlabs/lamindata/transform/BblTiuKxsb2g0002 …
> ✨ Improve annotating with, retrieving & removing feature values

- docs/curate-df.ipynb
- lamindb/_curate.py
- lamindb/_feature.py
- lamindb/_feature_set.py
- lamindb/_query_set.py
- lamindb/core/_data.py
- lamindb/core/_django.py
- lamindb/core/_feature_manager.py
- lamindb/core/_label_manager.py
- lamindb/core/types.py
- noxfile.py
- tests/core/test_collection.py
- tests/core/test_context.py
- tests/core/test_curate_annotate_df.py
- tests/core/test_feature.py
- tests/core/test_feature_manager.py
- tests/core/test_feature_set.py
- It's now possible to define features of `dtype="str"`
- Feature `dtype="number"` got renamed to `dtype="num"`
The valid feature dtypes are now:
```
FeatureDtype = Literal[
"cat",  # categorical variables
"num",  # numerical variables
"str",  # string variables
"int",  # integer variables
"float",  # float variables
"bool",  # boolean variables
"date",  # date variables
"datetime",  # datetime variables
"object",  # this is a pandas type, we're only using it for complicated types, not for strings
]
```
In addition, specifications like `cat[ULabel]` or `cat[bionty.CellType]` continue to be valid.
Annotate a dataset with feature values via `features.add_values()` as with all other dtypes.
```python
>>> import lamindb as ln
>>> import pandas as pd
>>> df = pd.DataFrame({"sample_note": ["was …
```
> ✨ Enable features with `dtype = 'str'`

- lamindb/_can_curate.py
- lamindb/_feature.py
- lamindb/_from_values.py
- lamindb/_query_set.py
- lamindb/core/__init__.py
- lamindb/core/_feature_manager.py
- tests/core/test_context.py
- tests/core/test_curate_annotate_df.py
- tests/core/test_feature_manager.py
Before: `.from_values()` returns a `list[Record]`
```python
ln.save(ln.ULabel.from_values(["DMSO", "IFNG"], create=True))
```
After: Because it now returns a `RecordList`, these all work:
```python
ln.ULabel.from_values(["DMSO", "IFNG"], create=True).save()
ln.ULabel.from_values(["DMSO", "IFNG"], create=True).df()
ln.ULabel.from_values(["DMSO", "IFNG"], create=True).one()
```
Dedicated for support for `pd.Categorical` and better logging message for user to decided on `str` vs. `cat` dtype.
Needs:
- https://github.com/laminlabs/lnschema-core/pull/461
> 🎨 Let `.from_values()` return `RecordList` and better treat categorical

- .gitignore
- docs/arrays.ipynb
- docs/faq/search.ipynb
- docs/registries.ipynb
- lamindb/_artifact.py
- lamindb/_feature.py
- lamindb/_query_set.py
- lamindb/_record.py
- lamindb/_save.py
- lamindb/_view.py
- lamindb/core/_context.py
- lamindb/core/datasets/__init__.py
- lamindb/core/datasets/_small.py
- tests/core/test_queryset.py
You can now easily join features onto the `Artifact` registry.
We find the features from the schema definition, independent of whether they are used as observation-level or dataset-level metadata.
```python
ln.Feature(name="cell_medium", dtype="cat[ULabel]").save()
ln.Feature(name="cell_type_by_expert", dtype="cat[bionty.CellType]").save()
ln.Feature(name="cell_type_by_model", dtype="cat[bionty.CellType]").save()
ln.Feature(name="temperature", dtype="float").save()
ln.Feature(name="study", dtype="cat[ULabel]").save()
ln.Feature(name="date_of_study", dtype="date").save()
ln.Feature(name="study_note", dtype="str").save()
```
Here is another screenshot, scrolling the table further to the right.
More changes.
- `QuerySet.df(include=[...])` now relies on `.annotate()` instead of `pandas` for …
> ✨ Enable to include features in `Artifact.df()`

- pyproject.toml
Fix https://github.com/laminlabs/lamindb/issues/2227
this is needed because `.infer_objects` doesnt have the `copy` argument before `pandas==2.0.0`, and it is used [here](https://github.com/laminlabs/lamin-utils/blob/2b9d4fcc865c8241752f10860411d516079f16a0/lamin_utils/_map_synonyms.py#L159).
> ⬆️ Add a lower bound for pandas

- lamindb/_save.py
Fixes a problem when `Artifact.save()` is called on a cloud instance but cache with the same path already exists, happens when an `Artifact` is deleted and then created again.
> 🐛 Fix the error on existing cache on copy to cache in Artifact.save

- lamindb/core/_feature_manager.py
- lamindb/core/_label_manager.py
- tests/core/test_describe_df.py
- tests/core/test_feature_label_manager.py
- `Dataset` → `Internal features`
- `Annotations` → `External features`
before | after
--- | ---
> 🎨 Update describe layout

- lamindb/_view.py
Do not import `IPython` directly in `.view.py`
> 🐛 Fix IPython import error

- lamindb/core/_feature_manager.py
- lamindb/core/_label_manager.py
- tests/core/test_describe_df.py
- tests/core/test_feature_label_manager.py
`Internal features` → `Dataset features`
`External features` → `Linked features`
Before | After
--- | ---
> 🎨 Remove quotes and rename sessions in describe

- docs/faq/search.ipynb
- lamindb/_record.py
`ln.Feature.search("cat[")` errors without this fix because unclosed `"["` is considered an incorrect regex.
> 🐛 Fix the error on special chars in search strings

- .github/workflows/build.yml
- lamindb/_can_curate.py
- lamindb/_curate.py
- lamindb/_from_values.py
- lamindb/core/_feature_manager.py
- lamindb/core/_label_manager.py
- tests/core/test_curator.py
Fixes #2262 
`KeyError: '\"cell_line\" is not a valid key, available keys are: \\'well\\', \\'sirna\\'!'"`
`KeyError: "'cell_line' is not a valid key, available keys are: 'well', 'sirna'!"`
```python
curator.standardize("disease")
curator.standardize("disease")
```
led to a traceback with 'KeyError: 'disease' is not a valid key.
`• No unstandardized values found for 'disease'`
Before this PR, the deprecated `add_new_from_columns` method was still listed in our documentation. It is now hidden.
> 🐛 Better error behavior for repeated calls of `standardize`

- lamindb/core/_django.py
- lamindb/core/_feature_manager.py
- Identified a few bottlenecks with a profiler and fixed them.
Now 
```
ln.Artifact.get("NiaMP8YQMbmkdOgnAa1T").describe()
ln.Artifact.get("LmlgCMQRhSEHtcbG0000").describe()
```
runs around 10 sec each instead of several minutes.
- Fixed describe when artifact is queried with `using`.
`ln.Artifact.using("laminlabs/cellxgene").get("g0RcSSYe5vQKzSWYkhMc").describe()` was failing before.
4-10 sec depending on annotations still feels pretty slow though, so it is probably not the final iteration.
> 🐛 Fix very long runtimes for Artifact.describe

- docs/faq/delete.ipynb
- docs/faq/keep-artifacts-local.ipynb
- docs/faq/key.ipynb
- docs/faq/search.ipynb
- docs/faq/symbol-mapping.ipynb
- docs/faq/track-run-inputs.ipynb
- docs/faq/validate-fields.ipynb
- docs/faq/visibility.ipynb
- docs/storage/prepare-transfer-local-to-cloud.ipynb
- noxfile.py
Earlier all genes that could not be mapped were simply set to `nan`. Now, the implementation will retain all unmapped symbols and users can decide what to do with them.
Internal context: https://laminlabs.slack.com/archives/C04MU979KD3/p1734345498957699
This PR also formats some notebooks and replaces `findrefs` with `ourprojects`
> ✨ Safer gene mapping

- lamindb/_record.py
Amends https://github.com/laminlabs/lamindb/pull/2288
FeatureSet should be allowed to rename without checking, since the dataset itself will not contain the name.
> 🎨 Proper type check of FeatureSet rename

- lamindb/_curate.py
- tests/core/test_curator.py
Fixes:
- https://github.com/laminlabs/lamindb/issues/2285
> 🐛 Let `Curator.from_tiledbsoma()` validate and annotate all `.obs` columns

- lamindb/core/storage/paths.py
- tests/core/test_artifact.py
Related https://github.com/laminlabs/lamindb-setup/pull/913
This PR enables to register http and https links as artifacts.
```python
secondary_analysis = ln.Artifact(
"https://assets.hubmapconsortium.org/1d91e74d48a309724ede35bdb33b5eb2/secondary_analysis.h5ad",
description = "Normalized gene expression with additional metadata, in HDF5 format, readable with the 'anndata' Python package (Format: EDAM_1.24.format_3590)"
).save()
secondary_analysis.load()
secondary_analysis.open()
```
See also https://lamin.ai/laminlabs/lamindata/transform/Wa7Fep0r3Hwp0000
> ✨ Allow to register artifacts with http urls

- lamindb/_record.py
- tests/core/test_search.py
Fixes https://github.com/laminlabs/lamindb/issues/2292
Like @Koncopd pointed out, search assumes a string. However, in practice I sometimes ran into cases where earlier pieces of (lamindb) code returned None which led to this error. I'm not a fan of too defensive programming in general but I think that this one is fine.
> 🎨 Raise ValueError when trying to search a None value

- lamindb/_curate.py
- tests/core/test_curator.py
Fixes https://github.com/laminlabs/lamindb/issues/2293
Now ensuring that people don't pass `Organism` to `organism` of any `Curator` but an actual str (the `Organism` name)
I am generally pretty unhappy about the fact that the `Curator` takes organism str but some other functions require an actual `Organism` and do not take str. It's inconsistent.
> 🎨 Add defensive organism check

- lamindb/core/storage/_tiledbsoma.py
- noxfile.py
Fix https://github.com/laminlabs/lamindb/issues/2296
> ⬆️ Make tiledbsoma integration compatible with tiledbsoma==1.15.0

- .github/workflows/build.yml
- noxfile.py
Exploratory PR to isolate curator tests completely
Observation: codecov goes crazy and might need some love:
```
Failing after 1s — 85.07% (-7.76%) compared to 2a17099 
```
> 👷 Isolate curator tests

- lamindb/_can_curate.py
- lamindb/_from_values.py
- tests/core/test_can_validate.py
- tests/core/test_from_values.py
Prevents mistakes like: https://github.com/laminlabs/lamindb/issues/2137
This PR makes sure that standardize only performs on name field.
> 🎨 Standardize name

- docs/arrays.ipynb
- docs/scripts/run-track-with-params.py
- docs/track.ipynb
- lamindb/_record.py
- lamindb/core/_data.py
- lamindb/models.py
- tests/core/test_feature_set.py
- tests/core/test_record.py
Before | After
--- | --- 
We're currently using the `._name_field` not only as display field, but also to govern auto-search when creating new records.
This isn't meaningful for registries like `ParamValue`, `FeatureValue`, `Run`, `Transform`, `Artifact` and others.
Hence, from now on, we only perform the search on sub-classes of `CanCurate`.
There is a bigger question on when a name field should imply uniqueness (hard on the SQL level or soft via auto-search on the Python level). See more in this internal [Slack ref](https://laminlabs.slack.com/archives/C04FPE8V01W/p1735944223599129) and this issue:
- https://github.com/laminlabs/lamindb/issues/2269
> 🚸 Only auto-search `._name_field` on sub-classes of `CanCurate`

- docs/arrays.ipynb
- pyproject.toml
subj
maybe fixed here https://github.com/scverse/anndata/pull/1806
> ⬇️ Upper bound scipy because 1.15.0 is incompatible with anndata backed sparse

- lamindb/_finish.py
- lamindb/core/_context.py
- lamindb/core/exceptions.py
- tests/core/notebooks/no-title.ipynb
- tests/core/test_context.py
Standard stream logs are now captured in `run.report` for scripts & functions (i.e. transforms that aren't notebooks).
See the illustration via he hub screenshots below.
Behavior when an error occurs | Behavior when killed through signal
--- | ---
Note: In LaminDB 1.0, these logs will also be available for notebooks through a `_logfile` M2M with artifact. The `.report` field isn't the canonical location for these.
> ✨ Capture logs of scripts during `ln.track()`

- lamindb/models.py
Fixes https://github.com/laminlabs/lamindb/issues/2201
- Removes underscore attributes from `__repr__`
Before:
`Artifact(uid='G9jm2669OchVQkEh0000', is_latest=True, description='bla', suffix='.parquet', type='dataset', size=1586, hash='Qu8wlxNlRjNPk9X-VJ1Slw', _hash_type='md5', _accessor='DataFrame', visibility=1, _key_is_virtual=True, storage_id=1, created_by_id=1, created_at=2025-01-07 14:52:36 UTC)`
After: 
`Artifact(uid='G9jm2669OchVQkEh0000', is_latest=True, description='bla', suffix='.parquet', type='dataset', size=1586, hash='Qu8wlxNlRjNPk9X-VJ1Slw', visibility=1, storage_id=1, created_by_id=1, created_at=2025-01-07 14:52:36 UTC)`
> ✨ Hide underscore attributes in __repr__

- tests/core/test_artifact.py
MD5-hash etag from headers and use it as a hash for http and https `Artifact`s.
https://github.com/laminlabs/lamindb-setup/commit/944168a3e4adc049317fb5075a06586c3eb0c081 (pushed directly to main by mistake)
https://github.com/laminlabs/lamindb-setup/pull/926
> ✨ Use etag as hash for http Artifacts

- lamindb/_finish.py
- lamindb/core/_context.py
Fixes `ValueError: signal only works in main thread of the main interpreter` from redun.
> 🐛 Fix signal outside main thread

- lamindb/core/_sync_git.py
Fixes #2331 
**Before:**
Errors when the code blob was not on the default branch.
**After:**
```
code blob hash 313ce3a4116476f1e83a14c17d8d2dcb6138e141 was found in non-default branch(es): origin/feature/ruff
```
> ✨ Also search git blob hash in remote branches

- lamindb/core/_context.py
- pyproject.toml
Fix https://github.com/laminlabs/pfizer-lamin-usage/issues/109
Also upper bound `zarr`.
> 🥅 Clear error on running track in an interactive session

- lamindb/_artifact.py
- lamindb/_query_set.py
- lamindb/_transform.py
- lamindb/base/__init__.py
- lamindb/models.py
Bring back `n_objects` but deprecate it with `@deprecated` which now hides the deprecated function from the docs.
See here:
Internal [Slack thread](https://laminlabs.slack.com/archives/C03Q5TXF797/p1736628804406989?thread_ts=1730810395.555979&cid=C03Q5TXF797).
> 🎨 Deprecate `n_objects`, introduce better `deprecated` decorator

- lamindb/_artifact.py
- lamindb/models.py
- tests/storage/test_storage.py
Now by default, if not explicitly specified with `.delete(storage=True)`, deleting a non-latest version of a mutable `Artifact` (such as `tiledbsoma`) does not delete an underlying storage.
```python
artifact = ln.Artifact.filter(key="some.tiledbsoma", is_latest=False).first()
artifact.delete() # deletes only this specific version and doesn't delete artifact.path
```
Deleting the latest version now deletes all versions so that no artifact records without underlying data survive.
```python
artifact = ln.Artifact.filter(key="some.tiledbsoma", is_latest=True).one() # virtual key
artifact.delete() # deletes all versions and the data in storage
```
Internal [Slack thread](https://laminlabs.slack.com/archives/C07DB677JF6/p1736783041648239).
> 🐛 Skip deleting storage when deleting outdated versions of folder-like artifacts

- lamindb/_finish.py
- lamindb/core/_context.py
- pyproject.toml
Also, pro-actively make new transform versions in RStudio if running an `Rmd` or `qmd` file in exact analogy to how a Jupyter Notebook is treated.
> 🚸 In `ln.track()`, do not update transform `description` if it is `None` and improve logging in RStudio sessions

- .github/workflows/build.yml
- docs/faq/idempotency.ipynb
- lamindb/core/datasets/_core.py
- noxfile.py
- pyproject.toml
- tests/core/test_artifact.py
Fixes https://github.com/laminlabs/lamindb/issues/2346#issuecomment-2603361418
- Adds official support for Python 3.13
- Replace 3.12 with 3.13 in the test matrix
- Require `readfcs>=2.0.1`
We stick to Python 3.12 for the docs for now because they fail https://github.com/laminlabs/lamindb/pull/2366#issuecomment-2607526154
> ✨ Support Python 3.13

- docs/storage/add-replace-cache.ipynb
- docs/storage/upload.ipynb
Also adds a proper cleanup to some storage CI group notebooks.
Related https://github.com/laminlabs/lamindb-setup/pull/951 with explanation of the problem.
Fix https://github.com/laminlabs/lamindb/issues/2356
> 🐛 Fix init (when the instance exists) and connect with migration for cloud sqlite instances

- lamindb/_finish.py
- lamindb/core/_context.py
- pyproject.toml
- tests/core/notebooks/basic-r-notebook.Rmd.html
- tests/core/test_context.py
Before this PR, `finish()` used to raise a `NotebookNotSaved` exception asking the user to save the notebook within 2 seconds before running `finish()`.
Now, it behaves more gracefully across Jupyter & RStudio.
Tested the following behavior in VSCode and Jupyter Lab. It works if event loop of editor frontend and kernel execution of the notebook cell are decoupled. This should be true for most editors. If it's not true the user won't be able to save while the cell runs and will see the second behavior below.
```bash
• please save the notebook in your editor (shortcut CMD + s) .... ✓
→ finished Run('vxl76EUB') after 9s at 2025-01-23 13:58:26 UTC
→ go to: https://lamin.ai/laminlabs/lamin-dev/transform/UcRrvg5YuNgC0009
→ to update your notebook from the CLI, run: lamin save …
```
> 🚸 No longer throw a `NotebookNotSaved` error in `ln.finish()` but wait for the user or gracefully exit

- docs/storage/add-replace-cache.ipynb
- lamindb/_artifact.py
- lamindb/core/loaders.py
- lamindb/core/storage/_backed_access.py
- lamindb/core/storage/paths.py
Delete an existing folder in a remote destination on upload of a new folder.
Also see comments in https://github.com/laminlabs/lamindb/pull/2374
> 🐛 Further fixes and tests for Artifact.replace

- lamindb/_finish.py
- lamindb/core/_context.py
- tests/core/notebooks/basic-r-notebook.Rmd.html
- tests/core/notebooks/no-title.ipynb
Attempts to improve on:
- https://github.com/laminlabs/lamindb/pull/2378
Compared to:
- https://github.com/laminlabs/lamindb/pull/2375
the new experience here adds a "still waiting" after 4 seconds of waiting and extends the maximal waiting period to 30 seconds to account for notebooks that might be very large and take very long to save.
```bash
• please hit CMD + s to save the notebook in your editor .... still waiting .................. ✓
```
> 🚸 In `ln.finish()` enhance experience of waiting for editor flush (attempt 2)

- docs/storage/add-replace-cache.ipynb
It wasn't testing the replacement of the folder in the same remote path because the replacement has a different suffix.
> ✅ Test folder replacement correctly

- lamindb/_artifact.py
- tests/core/test_cache.py
If the first attempt to load from the cache in `Artifact.load` fails, it attempts to re-download the cache and load into memory again.
> ✨ Check for corrupted cache in Artifact.load

- lamindb/_artifact.py
- tests/core/test_cache.py
`Artifact.open` uses cached files if they exist. This PR adds a check of `.open`, if it is unsuccessful, it tries to bypass the cache, open directly and delete the corrupted cache if the remote store has been opened successfully.
Related https://github.com/laminlabs/lamindb/pull/2386
Closes https://github.com/laminlabs/lamindb/issues/2392
> ✨ Check for corrupted cache in Artifact.open

- docs/faq/track-run-inputs.ipynb
- lamindb/_artifact.py
- lamindb/_save.py
- lamindb/models.py
- tests/core/test_collection.py
- tests/core/test_context.py
- tests/core/test_db.py
- tests/core/test_parents.py
- tests/core/test_record.py
- tests/core/test_run.py
- tests/core/test_schema.py
- tests/core/test_transform.py
- tests/curators/test_curator.py
- tests/storage/test_storage.py
Fixes https://github.com/laminlabs/lamindb/issues/2394
- Adds `*` to function signatures of `from_x` methods
- Fixes many deprecated `name` parameter args for `Transform` and `Collection`
> ✨ Require keyword parameters for `Artifact.from_x` methods

- lamindb/models.py
It is unclear from the docs that `Collection.append` doesn't modify the original collection but returns a new version which has to be saved.
> 📝 Clarify Collection.append

- lamindb/core/_mapped_collection.py
- tests/core/test_collection.py
MappedCollection was giving incorrect categorical labels for observations with `NaN` labels.
> 🐛 Fix NaN in categorical columns for MappedCollection

- lamindb/core/datasets/_small.py
- lamindb/curators/__init__.py
- lamindb/models.py
- tests/core/test_record.py
- tests/core/test_ulabel.py
- tests/curators/test_cat_curators.py
- tests/curators/test_cxg_curator.py
---
This PR simplifies the definition of constraints to validate against the CxG schema:
Before | After
--- | ---
It was implicitly defined by the state of another database instance passed via the `using_key` parameter to `AnnDataCurator`. |  It is now self-contained in the `CellxGeneAnnDataCurator` class.
It also brings down the run time of the CxG test further down [from 50s](https://github.com/laminlabs/lamindb/pull/2408#issuecomment-2628796391) to 20s:
```
============================= slowest 50 durations =============================
37.28s call …
```
> 🎨 Self-contained definition of `CellxGene` schema / validation constraints

- lamindb/core/__init__.py
- lamindb/curators/__init__.py
- noxfile.py
- tests/curators/test_cxg_curator.py
- tests/curators/test_pert_curator.py
---
This PR establishes the `Cat`-prefixed naming convention for all old-style curators that was adopted in the PR:
This will make it easier to re-use the existing code in the background, ensuring backward compat, while launching the new-style curators for users.
> 🚚 Bulk-rename old-style curators to `CatCurator`

- lamindb/curators/__init__.py
- tests/curators/test_cat_curators.py
- https://github.com/laminlabs/lamindb/pull/2413
--- 
Removing all logic related to `using_key` in curators is desirable because:
1. it gives rise to a leaner definition of a "valid category" that no longer involves the state of another database, but is restricted to the state of the current database & well-defined public ontology versions
2. it eliminates much code that makes refactoring easier
This is possible because PR 2412 eliminated the need for passing `using_key` for validating against the CellxGene schema, whose non-ontology based …
> 🔥 Eliminate all logic related to `using_key` in curators

- docs/ehrcurator.py
- lamindb/curators/__init__.py
- https://github.com/laminlabs/lamindb/pull/2415
- https://github.com/laminlabs/lamindb/pull/2413
---
Replace `self._kwargs` with explicit organism passing; remove ability to pass an organism ad-hoc in `.validate()` etc.
- goal is to define an organism as part of a feature dtype in cases in which it is needed -- e.g., `Gene.ensembl_gene_id` does not need it, whereas `Gene.symbol` needs it
- there should and can't be no need to pass an `organism` at any later stages of the workflow; it both opens up the door for integrity errors and makes …
> ♻️ Refactor `organism` handling in curators

- docs/curate-df.ipynb
- lamindb/_artifact.py
- lamindb/core/__init__.py
- lamindb/curators/__init__.py
- lamindb/models.py
- https://github.com/laminlabs/lamindb/pull/2415
- https://github.com/laminlabs/lamindb/pull/2413
Rename `BaseCurator` to `Curator` and eliminate the previous `Curator` https://github.com/laminlabs/lamindb/pull/2416/commits/1080aedb9d12c419bba8322f21ec117470847c95
The private attributes of `Curator` enable the most basic curation functionality.
```python
class Curator:
def __init__(self, dataset: Any):
self._dataset: Any = dataset  # pass the dataset as a UPathStr or data object
self._artifact: Artifact = None  # pass the dataset as a …
```
> ♻️ Re-purpose `BaseCurator` as `Curator`, introduce `CatCurator` and consolidate shared logic under `CatCurator`

- docs/registries.ipynb
- lamindb/__init__.py
- lamindb/_artifact.py
- lamindb/_collection.py
- lamindb/_feature.py
- lamindb/_record.py
- lamindb/_schema.py
- lamindb/core/__init__.py
- lamindb/core/_data.py
- lamindb/core/_feature_manager.py
- lamindb/core/datasets/_small.py
- lamindb/core/relations.py
- lamindb/curators/__init__.py
- lamindb/models.py
- tests/core/test_collection.py
- tests/core/test_describe_and_df_calls.py
- tests/core/test_feature_label_manager.py
- tests/curators/test_curators_quickstart_example.py
- tests/curators/test_dataframe_curators_accounting_example.py
- https://github.com/laminlabs/lamindb/pull/2417
- https://github.com/laminlabs/lamindb/pull/2416
- https://github.com/laminlabs/lamindb/pull/2415
- https://github.com/laminlabs/lamindb/pull/2413
---
This PR introduces the counterpart to the schema-based `DataFrameCurator` introduced in:
-  https://github.com/laminlabs/lamindb/pull/2388
```python
import bionty as bt
cell_medium = ln.ULabel(name="CellMedium", is_type=True).save()
ln.ULabel(name="DMSO", type=cell_medium).save()
ln.ULabel(name="IFNG", …
```
> ✨ Schema-based curators: `AnnDataCurator`

- lamindb/_artifact.py
- lamindb/core/storage/paths.py
- lamindb/models.py
- tests/core/test_artifact.py
- tests/storage/test_storage.py
https://github.com/laminlabs/lamindb-setup/pull/958
Adds initial support for s3-compatible endpoint urls.
Now it is possible to register an instance with an endpoint like this:
`lamin init --storage s3://bucket/folder?endpoint_url=http://some/url`
And also register an `Artifact`:
`ln.Artifact("s3://bucket/key.h5ad?endpoint_url=http://some/url")`
Thanks @ap-- for showing how to create and register a subclass of `S3Path`.
> ✨ Support s3-compatible endpoint urls

- docs/track.ipynb
- lamindb/_query_set.py
- lamindb/_tracked.py
- lamindb/core/_data.py
- lamindb/models.py
- tests/core/test_versioning.py
Iterates on the `ln.tracked()` decorator introduced below:
- https://github.com/laminlabs/lamindb/pull/2422
Eliminate the need to handle `run` manually by the user for consistency with tracking runs on the global scope.
```python
@ln.tracked()
def subset_dataframe(
input_artifact_key: str,  # all arguments tracked as parameters of the function run
output_artifact_key: str,
subset_rows: int = 2,
subset_cols: int = 2,
run: ln.Run | None = None,  # keyword argument is managed by decorator
) -> None:
artifact = ln.Artifact.get(artifact_key)
df = artifact.load(is_run_input=run)  # pass run to mark as input
new_df = df.iloc[:subset_rows, :subset_cols]
new_key = artifact.key.replace(".parquet", "_subsetted.parquet")
ln.Artifact.from_df(new_df, key=new_key, run=run).save()  # pass run to mark as …
```
> 🚸 Improve `ln.tracked()` user experience

- lamindb/models.py
Otherwise very confusing, as lamindb imported inside `_check_instance_setup` this is why this code block doesn't error.
> ♻️ Explicitly import lamindb in current_run

- lamindb/_artifact.py
- lamindb/core/storage/_tiledbsoma.py
- lamindb/models.py
- tests/core/test_artifact.py
- tests/storage/test_storage.py
Adds `Artifact.from_tiledbsoma` for registering `tiledbsoma` stores. Infers `n_observations`.
Example:
`ln.Artifact.from_tiledbsoma("s3://bucket/store.tiledbsoma")`
> ✨ Add Artifact.from_tiledbsoma with n_observations

- lamindb/curators/__init__.py
- tests/curators/test_cat_curators.py
This PR enables passing an `Artifact` object to `Curator`.
If an `artifact` is passed, `.save_artifact` will not re-upload the artifact, but merely link all metadata records to it.
Calling `standardize()` errors when an artifact is passed, because this will mutate the dataset and therefore no longer matches the saved artifact.
(Note: passing `artifact` was already possible for `TiledbsomaCatCurator` before this PR).
> ✨ Allow passing `artifact` to `Curator`

- lamindb/models.py
```
tests/test_ingest.py::test_individual_ingest
/home/lukas/code/lamindb/lamindb/models.py:3683: RemovedInDjango60Warning: CheckConstraint.check is deprecated in favor of `.condition`.
models.CheckConstraint(
tests/test_ingest.py::test_individual_ingest
/home/lukas/code/lamindb/lamindb/models.py:3733: RemovedInDjango60Warning: CheckConstraint.check is deprecated in favor of `.condition`.
models.CheckConstraint(
```
should be gone
> 🚸 Fix RemovedInDjango60Warning: CheckConstraint.check is deprecated

- docs/storage/add-replace-cache.ipynb
- lamindb/_artifact.py
Before this fix `Artifact.open` opened a cached store even if it was outdated. Now it opens the original cloud path in this case.
Fixes https://github.com/laminlabs/lamindb/issues/2452
> 🐛 Fix caching logic in `Artifact.open()`

- lamindb/_artifact.py
- lamindb/_collection.py
- lamindb/core/storage/_backed_access.py
- lamindb/core/storage/_pyarrow_dataset.py
- lamindb/models.py
- tests/storage/test_storage.py
Adds `Collection.open()` that can open a collection of files supported by `pyarrow` via `pyarrow.dataset.dataset()`.
See also [here](https://arrow.apache.org/docs/python/generated/pyarrow.dataset.dataset.html).
Example:
```python
import pandas as pd
df = pd.DataFrame({"feat1": [0, 0, 1, 1], "feat2": [6, 7, 8, 9]})
df[:2].to_parquet("df1.parquet", engine="pyarrow")
df[2:].to_parquet("df2.parquet", engine="pyarrow")
artifact1 = ln.Artifact(shard1, key="df1.parquet").save()
artifact2 = ln.Artifact(shard2, key="df2.parquet").save()
collection = ln.Collection([artifact1, artifact2], key="parquet_col")
dataset = collection.open() # backed by files in the cloud storage
dataset.to_table().to_pandas().head()
```
> ✨ Add `Collection.open()` that returns `pyarrow` dataset

- docs/curate-subclass.ipynb
- docs/ehrcurator.py
- lamindb/__init__.py
- lamindb/core/__init__.py
- lamindb/curators/__init__.py
- noxfile.py
- tests/curators/test_cxg_curator.py
- tests/curators/test_pert_curator.py
The `CatCurator` aka `CatManager` has a different concern from the `Curator`. The latter lets users curate a dataset given a schema. The former enables the user to conveniently update the content of registries to define new valid categories.
In a well-managed lakehouse, this need for "convenient updates" of registries should arise only rarely. If it does, the user finds it under the `.cat` accessor, which is inspired from `pandas`.
```python
class Curator:
@property
def cat(self) -> CatManager:
return self._cat_manager
```
This way the `add_new_from()`-et-al-API is only a finger tip away, but doesn't clutter the `Curator` namespace.
> 🚚 Rename `CatCurator` to `CatManager`

- lamindb/migrations/0087_squashed.py
- lamindb/models.py
A key property of the curation-based lakehouse is that a validated dataset needs to remain valid.
This means that once a `Schema` is defined and a dataset has been curated with it, the decisive `Schema` fields that determine the "validation state" of the dataset should not be changed anymore.
There is more work to be done towards ensuring such consistency, but this PR starts it by marking these fields as non-editable.
This is a pure Python-level operation, the changes in the migration file have (to date) no effect on the database state.
> ♻️ Mark `Schema` fields as non-editable

- docs/ehrcuration.ipynb
- lamindb/_feature.py
- lamindb/curators/__init__.py
- lamindb/models.py
- tests/core/test_record.py
- tests/curators/test_curators_general.py
One can now set features to be non-nullable:
```python
ln.Feature(name="disease", dtype=ln.ULabel, nullable=False)
```
By default, features are `nullable`, given the abundance of datasets with missing data. This is the opposite choice compared to `pandera`, where `nullable=False` by default.
If attempting to validate it, one will get this behavior:
```python
import pandas as pd
schema = ln.Schema(features=[ln.Feature(name="disease", dtype=ln.ULabel, nullable=False).save()]).save()
dataset = {"disease": pd.Categorical([pd.NA, "asthma"])}
df = pd.DataFrame(dataset)
curator = ln.curators.DataFrameCurator(df, schema)
curator.validate()
except ln.errors.ValidationError as e:
assert str(e).startswith("non-nullable series 'disease' contains null values")
```
Example for the …
> ✨ Add auxiliary field `nullable` to `Feature`

- lamindb/core/storage/_tiledbsoma.py
- tests/storage/test_storage.py
Add support of custom s3 endpoints for `save_tiledbsoma_experiment` `tiledbsoma` `Artifact.open` and all other operations with `tiledbsoma` in `lamindb`.
> ✨ Support endpoint_url in operations with tiledbsoma

- lamindb/_query_set.py
Passing a name of a model class property to `.filter` resulted in an ambiguous error.
> 🐛 Fix related model field check in .filter

- lamindb/_artifact.py
- tests/core/test_artifact.py
Populates `artifact.n_observations` when the `artifact` is created through `Artifact.from_df`.
Example:
```python
artifact = ln.Artifact.from_df(df, key="df.parquet").save()
artifact.n_observations # has len(df)
```
> ✨ Write `Artifact.n_observations` in `Artifact.from_df()`

- lamindb/_artifact.py
- lamindb/_save.py
- lamindb/core/storage/paths.py
This is needed in some edge cases like uploading large files in an unstable network or uploading a very large folder.
Example:
```python
Artifact.save(store_kwargs={"batch_size": 64}) 
```
> ✨ Allow to specify `fsspec` upload options in `Artifact.save`

- lamindb/_feature.py
- lamindb/_tracked.py
- lamindb/curators/__init__.py
- lamindb/models.py
- tests/core/test_schema.py
- tests/curators/test_curators_quickstart_example.py
After | Before
--- | ---
`DataFrameCurator.standardize()` failed saying: "feature doesn't have a default value". | If the `feature` is `nullable`, `.standardize()` will add columns and fill them with `pd.NA`.
This PR adds a few more other tests of edge cases and makes fixes in the docs.
> 🐛 Automatically add missing columns upon `.standardize()` if `nullable` is `True`

- lamindb/_finish.py
- lamindb/_query_set.py
- lamindb/base/users.py
- tests/core/test_notebooks.py
- tests/core/test_record.py
Since the below PR, we disallow hash duplications in `Transform`, `Artifact` & `Collection`:
- https://github.com/laminlabs/lamindb/pull/2432
While the clashing of hashes was resolved, for versioned entities like `Transform`, it was possible that the hash look up would fail because a record with the same hash might not have been marked as the latest version.
This opens the question whether a transform without `source_code` yet attached should act as `is_latest`, but we'll not resolve it in this PR.
> 🐛 Fix notebook re-run with same hash

- lamindb/core/_track_environment.py
Hey Lamins,
The way you gather a `requirements.txt` can return incorrect results under some edge cases. _(I just ran into one)_
https://github.com/laminlabs/lamindb/blob/f576cd12f8357fa6a7b8fe0abbcde5c74403f2dd/lamindb/core/_track_environment.py#L18-L22
When running with a python interpreter in a virtual env without activating the venv, (and under other edge cases like a user-site pip install, or nested activated conda envs) this can lead to requirements gathered from the wrong env.
This PR uses the correct interpreter in the subprocess run call to fix the issue.
Cheers,
Andreas 😃
> 🐛 Run pip freeze with current python interpreter

- docs/registries.ipynb
- docs/storage/add-replace-cache.ipynb
- lamindb/_artifact.py
- tests/core/conftest.py
- tests/core/test_artifact.py
- tests/core/test_cache.py
We've so far supported the case in which source path and target key in `Artifact()` have different suffixes.
While all functionality worked as expected there are two risks:
1. A user might provide an erroneous suffix either through the passed filepath or the passed key and because the suffix gets persisted as part of the S3 key it can't be easily changed
2. The user might get confused because the storage suffix and the suffix of the virtual path don't agree
Hence we're now throwing this error:
```python
try:
artifact = ln.Artifact("my_source_file.suffix1", key="my_target_file.suffix2")
except InvalidArgument as error:
assert str(error).startswith(
"The suffix '.inconsistent' of the provided key is incorrect, it should be '.md'."
)
```
Before this PR, the above silently passed.
What …
> 🚸 Raise consistency error if a source path suffix doesn't match the artifact `key` suffix

- lamindb/_artifact.py
- lamindb/_collection.py
- lamindb/core/loaders.py
- lamindb/core/storage/_anndata_accessor.py
- lamindb/core/storage/_backed_access.py
- lamindb/core/storage/_pyarrow_dataset.py
- lamindb/models.py
- tests/storage/test_storage.py
Allows to read gzipped `anndata` and `h5` files
Example:
```python
artifact = ln.Artifact.from_anndata("./adata.h5ad.gz", description="gzipped adata").save()
artifact.open()
artifact.load()
```
> ✨ Allow to use `Artifact.open()` and `Artifact.load()` for `.gz` files

- lamindb/core/_mapped_collection.py
Not nice, but i don't see any other way now.
We don't have any properly (externally) compressed `.gz` files anyways. But this is a mess.
> 🩹 Force no compression in `Collection.mapped` even for files with `.gz` extension

- docs/faq/key.ipynb
- lamindb/_artifact.py
- lamindb/core/loaders.py
- tests/core/test_artifact.py
- tests/core/test_load.py
Fix https://github.com/laminlabs/lamindb/issues/2504
Raise `NotImplementedError` on `artifact.load()` call when no loader is registered for the suffix.
> 🚸 Raise `NotImplementedError` in `Artifact.load()` if there is no loader

- lamindb/core/_context.py
Manual passing of path to `ln.track` was broken, i.e. `ln.track(path="path/to/nb.ipynb")` raised an error if no path was found by `nbproject` automatically.
> 🐛 Fix passing a path manually when no path found by `nbproject`

- lamindb/core/datasets/__init__.py
- lamindb/core/datasets/_core.py
- lamindb/curators/__init__.py
- lamindb/models/_feature_manager.py
Another step towards first class support for SpatialData and the harmonization of the ScverseDataStructuresCurators code
This PR
- Adds a datasetloader for a SpatialData blobs object that I will use for the SDC docstring example
- Moves the `_add_set_from_spatialdata` code of the old SDC to `FeatureManager`
- Moves the SDC code up so that it's below the MuDataCurator as the evolution of the curators will be DF -> AnnData -> MuData -> SpatialData in the future. SpatialData will use MuData soon
> ✨ Add `FeatureManager._add_set_from_spatialdata`

- lamindb/models/artifact.py
- tests/core/test_cache.py
Allow to propagate `kwargs` from `Artifact.cache()` to `UPath.synchronize()`. 
In particular, to avoid printing progress:
```python
artifact.cache(print_progress=False)
```
> ✨ Allow to pass synchronization arguments in `Artifact.cache()`

- lamindb/models/_from_values.py
- lamindb/models/artifact.py
- lamindb/models/can_curate.py
- lamindb/models/record.py
- tests/core/test_can_curate.py
- tests/storage/test_transfer.py
Before | After
--- | ---
Passing `organism` was required in cases in which it didn't make sense. | Passing `organism` is only required in few cases.
Changes:
- Passing `organism` to `CanCurate.validate()` is now only required if:
1. registry has a REQUIRED `organism` FK (e.g. won't check nullable [wetlab.Biosample.organism](https://github.com/laminlabs/wetlab/blob/main/wetlab/models.py#L746))
2. AND `field` used for validating and creating records is NOT unique (won't check for `ontology_id`, `ensembl_gene_id`, `uid`, ...)
- Robust mapping of ensembl prefix to organism via: [curated mapper](https://lamin.ai/laminlabs/bionty-assets/transform/iySVjI9UouaX).
- Removed all `using_key` logic in `CanCurate`, since users can call curate functions from `QuerySet`
> 🚸 Refactor `organism` constraints during validation

- lamindb/models/artifact.py
- lamindb/models/project.py
- lamindb/models/record.py
- lamindb/models/run.py
- tests/permissions/scripts/setup_access.py
Before | After
--- | ---
Before | After
--- | ---
Now returns the inherited type for all registries and thereby we have auto-complete right away:
Claude [helped](https://claude.ai/share/338cc542-8d19-43c6-935b-df598783cc9e).
We'll add similar typing improvements for other functionality in the future. Here is what we could add for `filter()`.
```python
from typing import TypeVar, Type, Optional, Union, Any, Generic
from django.db.models.base import ModelBase
T = TypeVar('T', bound='Record')
class QuerySet(Generic[T]):
pass
class Registry(ModelBase):
def filter(
cls: Type[T], 
*queries: Any, 
**expressions: Any
) -> QuerySet[T]:
"""Query records.
Args:
queries: One or multiple `Q` objects.
expressions: Fields and values passed as Django query expressions.
Returns:
A …
```
> 🚸 Add more constructor signatures and specific inherited types

- docs/faq/key.ipynb
- lamindb/base/types.py
- lamindb/curators/__init__.py
- lamindb/models/_feature_manager.py
- lamindb/models/schema.py
- tests/core/test_describe_and_df_calls.py
- tests/curators/test_curators_quickstart_example.py
`uint` one is now a valid `dtype`.
The `AnnDataCurator` now understands validation with composite schemas that contain a slot `uns`.
```python
var_schema = ln.Schema(
name="scRNA_seq_var_schema",
itype=bt.Gene.ensembl_gene_id,
dtype="num",
).save()
uns_schema = ln.Schema(
name="flexible_uns_schema",
itype=ln.Feature,
).save()
anndata_schema = ln.Schema(
name="small_dataset1_anndata_schema",
otype="AnnData",
components={"var": var_schema, "uns": uns_schema},
).save()
```
Providing an "obs" schema is no longer required.
> 🚸 Add `uint` as a valid `dtype`, in `AnnDataCurator`, make `'obs'` schema optional and allow `'uns'` schema

- docs/curate.ipynb
- lamindb/_view.py
- lamindb/base/types.py
- lamindb/core/types.py
- lamindb/curators/__init__.py
- lamindb/models/_feature_manager.py
- lamindb/models/feature.py
- lamindb/models/record.py
- lamindb/models/run.py
- lamindb/models/schema.py
- tests/core/test_dtype.py
- tests/core/test_feature.py
- tests/core/test_record.py
- tests/curators/test_curators_quickstart_example.py
To avoid requiring `coerce_dtype` for `"int"` and `"float"` in case an integer or float `pd.Series.dtype` only deviates by numerical precision/range, we now interpret `"int"` / `"float"` / `"num"` dtypes as unions of their underlying numerical `dtype` families as documented below.
Before | After
--- | ---
According to the sources and AI I consulted, it is known behavior that pandera doesn't have a built-in way to express an `AnyInt` dtype. pandera interprets `int` as `np.int64`, _not_ as `np.integer`. `np.integer` would provide the correct behavior but doesn't have a counterpart in a validation library or another context where it'd be serialized.
Specifically, I've found this [related comment](https://github.com/unionai-oss/pandera/issues/726#issuecomment-1511391725) on the pandera repo, …
> 🚸 Avoid requiring `coerce_dtype` for `"int"` and `"float"` in case an integer or float `pd.Series.dtype` only deviates by numerical precision/range

- noxfile.py
The more strict setuptools version got yanked and a new version without the requirement that broke pims was published.
> ➖ Remove pims pin

- lamindb/models/_is_versioned.py
- lamindb/models/record.py
All of the following will now return an ordered query set representing the version history of the record.
```python
artifact.versions
transform.versions
collection.versions
```
> ♻️ Order `IsVersioned.versions` query set

- lamindb/models/has_parents.py
- lamindb/models/transform.py
The below is now printed.
```python
artifact.view_lineage()
#> → explore at: https://lamin.ai/laminlabs/lamindata/artifact/qQ6DCPnSKWMvA5GC0000
```
When running the code in the regular python shell or in a script, a pdf plot is displayed and a file is written into the current working directory.
> 🚸 Show link to hub in `view_lineage()` and render lineage through graphviz also in scripts

- lamindb/curators/__init__.py
- lamindb/models/artifact.py
- tests/core/test_artifact.py
We were previously loading both mudata and spatialdata if they were installed and users were trying to create ANY Artifact. With this PR we check for types using class names instead of instance checks so that we do no longer need these imports.
To test:
```python
import sys
from types import ModuleType
def get_loaded_packages() -> list[str]:
modules = []
for name, module in sys.modules.items():
if isinstance(module, ModuleType) and not name.startswith('_'):
if '.' not in name:
modules.append(name)
return sorted(modules)
ln.Artifact("LICENSE").save()
loaded_packages = get_loaded_packages()
assert not "mudata" in loaded_packages
assert not "spatialdata" in loaded_packages
```
> 🐛 Fix SpatialData and MuData check

- lamindb/models/has_parents.py
Add a `return_graph` argument to `view_lineage()` that returns the graph object.
Related to https://github.com/laminlabs/laminr/pull/178, https://github.com/laminlabs/laminr/pull/180, https://github.com/laminlabs/laminr/issues/177.
> ♻️ Add `return_graph` argument to `view_lineage()`

- lamindb/curators/__init__.py
- tests/curators/test_curators_general.py
This PR adds validation of features in `DataFrameCurator` based on `schema.minimal_set`, `schema.maximal_set`, `schema.ordered_set`.
* If `minimal_set` is `False`, missing columns in a dataframe will not lead to an error (default is unchanged and `True`)
* If `maximal_set` is `True`, additional columns in a dataframe will lead to an error (default is unchanged and `False`)
* If `ordered_set` is `True`, columns in the wrong order in a dataframe lead to an error (default is unchanged and `False`)
```python
df_missing_column = pd.DataFrame(
{
"sample_id": ["sample1", "sample2"],
"sample_name": ["Sample 1", "Sample 2"],
}
)
schema_minimal_set = ln.Schema(
name = "my_schema_minimal_set",
features = [
ln.Feature(name="sample_id", dtype = str).save(),
ln.Feature(name="sample_name", dtype = …
```
> ✨ Support `minimal_set`, `maximal_set`, `ordered_set` in curators

- docs/track.ipynb
- lamindb/__init__.py
- lamindb/core/_context.py
- lamindb/models/query_set.py
- lamindb/models/record.py
- tests/core/test_track.py
- tests/permissions/scripts/example_script.py
- tests/permissions/test_permissions.py
Assigning spaces to records was possible before, but to conveniently add all entities written during a run to a desired space, you can now pass `space` to `ln.track()`.
```python
ln.track(space="My space")
```
This parallels what we do for labeling entities with projects with `ln.track(project="My project")`.
Note that `bionty` entities are -- for now -- excluded from this because in most use cases they should be saved in the`"All"` space of an instance and be accessible to all instance collaborators.
> 🚸 Add space management to `ln.track()`

- docs/curate.ipynb
- lamindb/curators/__init__.py
- lamindb/models/can_curate.py
- tests/curators/test_cat_managers.py
- tests/curators/test_curators_general.py
- tests/curators/test_curators_quickstart_example.py
- tests/curators/test_dataframe_curators_accounting_example.py
- tests/curators/test_pert_curator.py
- Add `CatColumn` to handle `validate`, `add_new` for each categorical
- Deprecate `MuDataCatManager` and `SpatialDataCatManager` with refactors
- Deprecated passing `all` to `standardize` and `add_new_from` in favor of using `.non_validated.keys()`
- Remove deprecated method `add_new_from_columns`
@falexwolf What's still not great is the transformation of var matrix because it messes up object synchronization, I think we should introduce curating index instead.
> ♻️ Organize categorical curation code with `CatColumn`

- lamindb/core/_context.py
- lamindb/models/run.py
- noxfile.py
- tests/core/test_track.py
*Author:* @ragyhaddad
This PR introduces the ability to run a script on Modal through the new CLI command `lamin run`. It is documented as experimental, not meant for production usage at this point, and will not yet appear in the changelog.
Needs:
- https://github.com/laminlabs/lamin-cli/pull/123 <-- see for details and follow-up TODOs
- https://github.com/laminlabs/lamindb-setup/pull/1016
> ✨ Introduce `lamin run` with a Modal backend

- lamindb/curators/__init__.py
- tests/curators/test_cat_managers.py
- tests/curators/test_cxg_curator.py
Organisms should be defined on the `dtype` or `itype` level, not on the curator level. Eliminating all this legacy code enables downstream simplifications.
A user of the _legacy_ curators, all of which still have the `organism` argument, will now see that this argument is no longer respected. They can use `bt.settinigs.organism` instead.
Requires:
- https://github.com/laminlabs/bionty/pull/242
> ♻️ Remove `organism` argument on `CatManager` level

- lamindb/curators/__init__.py
This is legacy logic that merely complicates the code and clutters the logging output for users.
> ♻️ Remove `verbosity` argument on `CatManager` level

- lamindb/curators/__init__.py
- lamindb/models/__init__.py
- lamindb/models/feature.py
- lamindb/models/schema.py
- tests/curators/test_curators_general.py
This PR adds `Feature.with_config(optional: bool)` to define schema-specific optional features.
It also updates the hash calculation for the schema hash to account for the schema configuration in all cases. Previously, if features were defined, the hash calculation disregarded the schema configuration.
Interacting with optionals:
- Get optional features via `schema.optionals.get()`
- Set optional features via `schema.optionals.set()`
- Add an additional optional feature via `schema.optionals.add()`
Internal [Notion page](https://www.notion.so/laminlabs/Overhaul-the-Schema-design-1ca2aeaa55e1803cb3fed41f955fcc7c).
> ✨ Define optional features on a per-schema level & improve schema hash calculation

- docs/faq/pydantic-pandera.ipynb
- lamindb/curators/__init__.py
- lamindb/models/schema.py
- tests/curators/test_curators_quickstart_example.py
This PR introduces a simple way to validate & annotate datasets without having to spell out all involved features. A schema with `flexible == True` will validate all known features matching the `itype` and automatically annotate categoricals. Before this PR, in such cases, only the feature identifiers themselves were validated and no annotation with labels took place.
```python
schema = ln.Schema(itype=ln.Feature).save()  # <-- if you're just defining the itype, this sets flexible = True
curator = ln.curators.DataFrameCurator(df, schema)
curator.save_artifact(key="my_dataset.parquet")
```
You can also validate & annotate features in addition to those that you're explicitly defining:
```python
schema = ln.Schema(
features=[ln.Feature(name="my_required_feature", dtype=int).save()], …
```
> 🚸 Enable to validate & annotate features *without* passing them to a schema

- lamindb/curators/__init__.py
- lamindb/models/artifact.py
- lamindb/models/schema.py
- tests/curators/test_curators_quickstart_example.py
To ingest a validated and annotated artifact, one can now run:
```python
artifact = ln.Artifact.from_df(df, key="my_dataset.parquet", schema=schema).save()
```
The is useful if one expects standardized datasets. If one expects "messy data" or one wants to update registries during curation, one can continue to use the more explicit flow that leverages a `Curator` object.
```python
curator = ln.curators.DataFrameCurator(df, schema)
artifact = curator.save_artifact(key="my_dataset.parquet")
```
> ♻️ Add `schema` as an argument to `Artifact.from_X()`

- lamindb/models/record.py
Before | After
--- | ---
Upon updating a schema with a given name, we threw a hard error. | We merely print a warning.
In the future, we'll print a detailed report about which datasets might be implicated by the change similar to what we're doing for label renames.
> 🚸 No longer throw an error but merely print a warning when updating a schema

- .github/workflows/build.yml
- lamindb/models/record.py
- tests/permissions/test_permissions.py
- https://github.com/laminlabs/lamindb-setup/pull/1020
For instances with fine-grained access a db token (jwt) is set on every transaction. This token grants access to database operations. The token is received from central and has an expiration date, this PR adds a check of the expiration and requests a new token if the current one is expired.
> ✨ Refresh db token on expiration

- lamindb/core/loaders.py
This PR fixes the installation instruction for `zarr` by adding quotes around the package and version specifier. The installation command without quotes caused shell interpretation issues.
> ✏️ Improve installation hint for zarr

- lamindb/models/artifact.py
In case `artifact._overwrite_versions` was `True`, before this PR, the following call deleted all records of the version family:
```python
artifact.delete(storage=False)
```
Now it only deletes the selected record.
> 🐛 Do not delete version family if user wants to retain store by passing `storage=False` to `artifact.delete()`

- pyproject.toml
Enables `ln.track()` without passing the notebook path when run through `nbconvert`:
```
jupyter nbconvert --to notebook --execute test-nbconvert.ipynb
```
Resolves:
- https://github.com/laminlabs/lamindb/issues/1625
Needs:
- https://github.com/laminlabs/nbproject/pull/288
- https://github.com/laminlabs/lamin-cli/pull/128
> ✨ Enable executing notebooks via `jupyter nbconvert --execute`

- lamindb/models/artifact.py
After discussion there, mostly reverts:
- https://github.com/laminlabs/lamindb/pull/2683
> 🐛 Delete version family if user wants to retain store by passing `storage=False` to `artifact.delete()`, but retain warning

- lamindb/curators/__init__.py
- lamindb/models/schema.py
- tests/core/test_schema.py
- tests/curators/test_curators_quickstart_example.py
You can now pass `index` to the `Schema` constructor to validate an index in a `DataFrame` in complete analogy to validating columns.
In particular, if you use a categorical `dtype`, the dataset will be annotated by the labels found in the index. If you use `int` or `str`, it will merely be validated.
Note that the "index feature" will appear among `schema.features` despite the constructor passing it to the new argument `index`. This is for UX and consistency with other dataframe frameworks like polars or even parquet files themselves (who don't have an index) and the `pandera` constructor (who lists the `index` argument).
As seen in the below example, the `index` feature isn't yet marked as such in `describe()` and isn't yet part of the feature set that belongs to the `DataFrame`. Rather …
> ✨ Enable curating the index of a dataframe

- lamindb/integrations/_vitessce.py
Previously, the function only accepted `description` parameter, which resulted in multiple Artifacts not being grouped by key.
> ♻️ Allow passing `key` to `save_vitessce_config()`

- lamindb/core/storage/objects.py
- lamindb/curators/__init__.py
- tests/curators/test_dataframe_curators_accounting_example.py
This PR passes `format=".csv"` to `Artifact.from_df` in `DataFrameCurator` to allow saving samplesheets as csv files. Previously only `.parquet` was possible.
Example:
```python
curator = ln.curators.DataFrameCurator(df, schema)
curator.save_artifact("forms/samplesheet.csv")
```
> ✨ Can save csv artifacts in `DataFrameCurator`

- lamindb/models/save.py
I have a ton of problems with moving cached files when running `lamin-cli` tests locally on Windows. 
It looks like something holds cached run logs open and this causes problems with moving them within `copy_or_move_to_cache` on Windows.
As `copy_or_move_to_cache` happens after successful saving, there is no need to fail at the end of the process, copying the cache is not absolutely necessary, it will work without it anyways. This prevents failing of `Artifact.save`  if errors inside `copy_or_move_to_cache` happen.
Also runs `lamin-cli` tests for https://github.com/laminlabs/lamin-cli/pull/129, as running locally on Windows is problematic.
> 🥅 Do not raise exceptions on problems with `copy_or_move_to_cache` within `Artifact.save`

- lamindb/curators/__init__.py
- tests/curators/test_curators_general.py
The order should be determined based on the list that passed to `Schema` constructor. Under the hood, the correct order should be retrieved via `schema.members`.
> 🐛 Fix `ordered_set` in curators

- lamindb/core/_settings.py
Do not load `lamindb_setup.settings.instance.git_repo` on import from `lamindb.models`. This was problematic if `lamindb` is used only as a `django` app.
> ♻️ Avoid non-lazy loads of settngs on import of `lamindb.models`

- docs/curate.ipynb
- docs/scripts/curate-anndata.py
- docs/scripts/curate-dataframe.py
- docs/scripts/curate-mudata.py
- docs/scripts/curate-spatialdata.py
- lamindb/curators/__init__.py
- lamindb/models/schema.py
- noxfile.py
Before this PR, the very extensive examples for curators were neither executed nor shown in the context of the curation guide.
Now they are.
Before | After
--- | ---
Exemplarily shown for `SpatialData`. Same changes for all other data structures.
Before | After
--- | ---
> ♻️ Execute curator examples and also show them in the curation guide

- lamindb/core/datasets/_small.py
- lamindb/curators/core.py
- lamindb/models/schema.py
- tests/core/test_collection.py
- tests/curators/conftest.py
- tests/curators/test_curators_examples.py
In preparation to refactoring the `.var` treatment, I realized that the information about both slot and `.cat` attribute was absent in the logging messages.
Also, there are no tests for these messages and they did were not appear as _error messages_ (in addition to being logged).
These issues are addressed with the exemplary test below.
```python
def test_anndata_curator_var_curation_legacy_convention():
var_schema = ln.Schema(
itype=bt.Gene.ensembl_gene_id,
dtype="num",
).save()
components = {"var": var_schema}
anndata_schema = ln.Schema(
otype="AnnData",
components=components,
).save()
for with_gene_typo in [True, False]:
adata = datasets.small_dataset1(otype="AnnData", with_gene_typo=with_gene_typo)
if with_gene_typo:
with pytest.raises(ValidationError) as error:
artifact = …
```
> 🚸 Restore validation error messages, add their fine-grained testing, and prepare `var` refactor in curators

- lamindb/core/datasets/mini_immuno.py
- lamindb/curators/core.py
- lamindb/models/feature.py
- tests/curators/test_curators_examples.py
One can now do:
```python
perturbation = ln.ULabel(name="Perturbation", is_type=True).save()
ln.ULabel(name="DMSO", type=perturbation).save()
ln.ULabel(name="IFNG", type=perturbation).save()
ln.ULabel(name="ulabel_but_not_perturbation").save()
ln.Feature(name="perturbation", dtype=perturbation).save()
```
A dataframe containing `"ulabel_but_not_perturbation"` in column `"perturbation"` now fails validation:
```python
df = datasets.small_dataset1(otype="DataFrame", with_wrong_subtype=True)
curator = ln.curators.DataFrameCurator(df, small_dataset1_schema)
with pytest.raises(ln.errors.ValidationError) as error:
curator.validate()
assert (
error.exconly()
== """lamindb.errors.ValidationError: 1 term not validated in feature 'perturbation': 'ulabel_but_not_perturbation'
→ fix typos, remove …
```
> 🚸 Fully functional `ULabel` subtype validation, better syntax for it

- lamindb/models/feature.py
- lamindb/models/record.py
- lamindb/models/schema.py
- tests/curators/test_curators_examples.py
If a user attempts to update a schema, e.g., by adding or removing a feature from `schema.features` or by changing a setting, the API will now provide better feedback.
More specifically, upon `schema.save()` it'll print a warning that lists all datasets that were previously validated with this schema, which might now no longer be valid.
```python
class Schema:
def save(self):
...
if validated_kwargs["hash"] != self.hash:
from .artifact import Artifact
datasets = Artifact.filter(schema=self).all()
if datasets.exists():
logger.warning(
f"you updated the schema hash and might invalidate datasets that were previously validated with this schema: {datasets.list('uid')}"
)
self.hash = validated_kwargs["hash"]
self.n = validated_kwargs["n"]
```
If we monitor in detail what kind of updates a user …
> 🚸 Handle schema updates decently

- docs/arrays.ipynb
- lamindb/core/storage/_backed_access.py
- lamindb/core/storage/_polars_lazy_df.py
- lamindb/core/storage/_pyarrow_dataset.py
- lamindb/models/artifact.py
- lamindb/models/collection.py
- noxfile.py
- tests/storage/test_storage.py
Closes https://github.com/laminlabs/lamindb/issues/2725
This PR adds `polars` support to `Artifact.open()` and `Collection.open()`.
Examples:
```python
...
with artifact.open(df_engine="polars") as lazy_df: # lazy_df is polars.LazyFrame
df = lazy_df.collect().to_pandas() # here just loads into memory, but can be anything
with collection.open(df_engine="polars") as lazy_df: # lazy_df is polars.LazyFrame
df = lazy_df.collect().to_pandas()
```
> ✨ Allow to use `polars` in `Artifact.open()` and `Collection.open()`

- docs/arrays.ipynb
- docs/storage/anndata-accessor.ipynb
- tests/core/conftest.py
More rigid storage constraints in LaminCentral led to tests failing. This PR fixes them by separating test datasets in a way that the different auto-created test lamindb instances don't clash anymore.
I also ran these two sets of commands in Python and on the CLI:
```python
ln.UPath("s3://lamindb-ci/lndb-storage/pbmc68k.h5ad").rename("s3://lamindb-ci/test-arrays/pbmc68k.h5ad")
ln.UPath("s3://lamindb-ci/lndb-storage/testfile.hdf5").rename("s3://lamindb-ci/test-arrays/testfile.hdf5")
```
```bash
% aws s3 cp s3://lamindb-ci/test-arrays/pbmc68k.h5ad s3://lamindb-ci/test-anndata/pbmc68k.h5ad
% aws s3 cp s3://lamindb-ci/test-arrays/testfile.hdf5 s3://lamindb-ci/test-lamin-cli/testfile.hdf5
```
Needs:
- https://github.com/laminlabs/lamin-cli/pull/133
> 👷 Refactor storage management during CI runs

- lamindb/_finish.py
- lamindb/models/_describe.py
Presently, these are only run reports and environments.
Marking them with `_branch_code=0` was not a good choice because we want to represent lamindb-produced artifacts independent of the branch.
> ♻️ Mark internal lamindb-produced artifacts with `kind="__lamindb__"` instead of `_branch_code=0`

- tests/writelog/conftest.py
To avoid any chance of confusion.
> ♻️ Rename instance and paths for writelog tests

- lamindb/models/schema.py
Credits go to @Koncopd and @falexwolf 
- fixes a case where the to-be-transferred record likely has `state record._state.adding` is False and so the Schema management thinks it’s an already-existing record and it tries to re-calculate the hash. But in fact it’s a new record.
More context: https://laminlabs.slack.com/archives/C046F63LJJ2/p1747141050444589?thread_ts=1743600829.515319&cid=C046F63LJJ2
> 🐛 Fix schema transfer

- lamindb/models/feature.py
If dtype is `cat[bionty.CellType]`, for example, and `bionty` is not installed, a very obscure import error appears.
See also https://laminlabs.slack.com/archives/C07H7FQT9DH/p1747150860447589?thread_ts=1747148431.902579&cid=C07H7FQT9DH
> 🚸 Clearer error in `parse_cat_dtype` if cat dtype contains a module name and the module is not found

- lamindb/models/dbrecord.py
- tests/storage/test_transfer.py
On records transfer between instances, the space of the transferred records is set to the current space instead of the source space.
> 🗃️ Set current space when transferring records

- lamindb/models/artifact.py
Import errors most probably don't indicate that something is wrong with the cache file or folder itself, so there is no need for re-synchronization.
> 🩹 Do not re-synchronize on `ImportError` in `Artifact.load()`

- lamindb/models/artifact.py
- lamindb/models/transform.py
So far, we've added entries to `transform.predecessors` upon tracking them as run inputs. The rationale was to provide a more convenient query.
This was rarely used and led to confusion. It also prevents building a dedicated experience around "manually tracked transforms".
> ♻️ Do no longer duplicate tracking of predecessors through the corresponding link table on `Transform`

- lamindb/core/writelog/_db_metadata_wrapper.py
- lamindb/core/writelog/_replayer.py
- lamindb/core/writelog/_trigger_installer.py
- tests/writelog/test_postgres_trigger_installer.py
- tests/writelog_sqlite/test_replayer.py
`lamindb_featurevalue` is unique among our current tables because its UID is composed of both its own fields and the fields of one of its foreign-keyed tables. This requires some special handling both in cursor installation and replay.
> ♻️ Support combined UID format for `lamindb_featurevalue` in `WriteLog`

- lamindb/migrations/0096_remove_artifact__param_values_and_more.py
- lamindb/migrations/0103_remove_writelog_migration_state_and_more.py
- pyproject.toml
We don't want the `sub/` directory within `sdist` on pypi because it contains pypi packages itself.
> 👷 Exclude sub directory from source distribution on pypi

- docs/registries.ipynb
- lamindb/models/_feature_manager.py
- tests/core/test_feature_label_manager.py
Bug was introduced in a refactor after 1.5.3. Got never released.
FeatureManager has to be overall-refactored, will happen in another PR.
> 🐛 Fix comparisons to `__isnull` for feature-based queries

- lamindb/core/storage/_tiledbsoma.py
- lamindb/core/storage/paths.py
- lamindb/models/artifact.py
- tests/core/test_artifact_folders.py
You can now avoid overwriting versions of folder-like artifacts by passing `overwrite_versions=False`.
```python
ln.Artifact("./my_folder", key="my_folder", overwrite_versions=False)
```
We can perform de-duplication by tracking shared files across versions in case it ever becomes relevant. Some notes on this here: https://claude.ai/share/7cec66cd-edcc-4ae6-9b01-b1bf9610dd31
> 🚸 Expose `overwrite_versions`

- lamindb/models/_feature_manager.py
- lamindb/models/artifact.py
- lamindb/models/feature.py
- lamindb/models/run.py
- lamindb/models/schema.py
- lamindb/models/sqlrecord.py
- tests/core/test_feature_label_manager.py
This eliminates all monkey-patching and unconventional code organization that dates back to using the deprecated `Artifact.features.filter()` access pattern.
Meanwhile, there was a transition to filtering by features as we filter by fields, through `Artifact.filter()` and there is no longer a need for the complexity.
This refactor prepares a refactor for the transfer flow.
> ♻️ Refactor `FeatureManager`

- lamindb/base/types.py
- lamindb/core/_context.py
- lamindb/core/_mapped_collection.py
- lamindb/core/_settings.py
- lamindb/core/loaders.py
- lamindb/core/storage/_anndata_accessor.py
- lamindb/core/storage/_tiledbsoma.py
- lamindb/core/storage/_zarr.py
- lamindb/core/storage/objects.py
- lamindb/core/storage/paths.py
- lamindb/core/types.py
- lamindb/curators/_legacy.py
- lamindb/models/artifact.py
- lamindb/models/storage.py
- lamindb/models/ulabel.py
- lamindb/setup/__init__.py
- lamindb/setup/errors/__init__.py
- lamindb/setup/types/__init__.py
- pyproject.toml
- tests/core/test_storage.py
- tests/storage/test_storage_lifecycle.py
- tests/storage/test_switch_delete_storage_location.py
Freeing up the `storage_uid.txt` that marks that a storage location is managed with a LaminDB instance is pivotal. This was forgotten in the PR below and is added in this PR.
- https://github.com/laminlabs/lamindb/pull/2839
If working with instances that are not registered on LaminHub, there was an insufficient mechanism to identify whether storage locations are already managed by other instances or still free to be managed. This PR and the changes in lamindb-setup both introduce the mechanisms that allow this, and provide clear user feedback.
For instance, the following path is part of a storage location that's managed by `laminlabs/lamindata`. When registering an artifact from another instance (also one that's not on the hub), the storage location is now correctly classified as …
> 🐛 Clean delete of storage locations, transparent referencing of storage locations

- lamindb/core/_context.py
Fix https://github.com/laminlabs/lamindb/issues/2606
This PR fixes logging strings with carriage returns, it only writes the last non-empty text segment so that carriage return is obeyed.
> 🔊 Correct treatment of carriage returns in logs

- lamindb/models/artifact.py
- lamindb/models/storage.py
`select_storage_or_parent` already checks for the hub record, no need to do the same request again.
> 🩹 Avoid `init_storage` call in `check_path_in_existing_storage`

- tests/permissions/test_permissions.py
`lamindb_setup.connect()` doesn't write any settings by default now.
`lamin connect ...` (CLI) still does.
https://github.com/laminlabs/lamindb-setup/pull/1056
https://github.com/laminlabs/lamin-cli/pull/135
https://github.com/laminlabs/lamin-cli/pull/136
> 🚸 Do not write instance settings on connect by default

- docs/faq/acid.ipynb
- lamindb/models/artifact.py
- lamindb/models/save.py
- tests/storage/conftest.py
- tests/storage/test_artifact_zarr.py
Now artifacts have `._is_saved_to_storage_location` property which is `True` only if upload or local saving was completed successfully. 
`artifact._is_saved_to_storage_location` is meaningful only after calling `.save()`. `None` means no writing was necessary, `True` - that it was written correctly. `False` shows that there was a problem with writing.
```python
artifact.save() # or ln.save([artifact])
assert artifact._is_saved_to_storage_location
```
> 🚸 Mark failed upload of artifacts via `artifact._is_saved_to_storage_location`

- lamindb/models/artifact.py
- lamindb/models/query_set.py
- tests/curators/test_records.py
What has already worked for artifacts now also works for records:
```python
ln.Record.df(features=True)
```
In particular, given a record type `my_sheet`, one can export the sheet as a dataframe:
```python
ln.Record.filter(type=my_sheet).df(features=True)
```
For example, from the unit tests:
```python
dictionary = (
ln.Record.filter(type=sheet1)
.df(features=["cell_line", "treatment"])[["name", "cell_line", "treatment"]]
.to_dict(orient="list")
)
assert dictionary == {
"name": [
"sample1",
"sample2",
],
"cell_line": [
"HEK293T cell",
"HEK293T cell",
],
"treatment": [
"treatment1",
"treatment2",
],
}
```
> ✨ Enable converting records to dataframes

- lamindb/models/_describe.py
- tests/core/test_describe_and_df_calls.py
- tests/core/test_feature_label_manager.py
Before | After
--- | ---
Partially supersedes:
- https://github.com/laminlabs/lamindb/pull/2764
Fixes
- https://github.com/laminlabs/lamindb/issues/2662
- https://github.com/laminlabs/pfizer-lamin-usage/issues/202
> 🚸 Introduce two-column layout in `Artifact.describe()` and add information like `space`, `branch`, and `kind`

- docs/storage/transfer-local-to-cloud.ipynb
- docs/transfer.ipynb
- lamindb/models/artifact.py
- lamindb/models/sqlrecord.py
- tests/storage/test_transfer.py
While the original idea was that it'd be highly convenient to transfer all features & labels together with a dataset, practical experience shows that the source instance of a dataset often uses slightly different conventions.
A more robust strategy is to transfer the dataset without features & labels and then either run a curator in the target instance or transfer desired features & labels in isolation.
If the user wants to _also_ tranfer annotations they can now pass:
```python
artifact.save(transfer="annotations")
```
> 🚸 Simplify default transfer mode: no longer transfer annotations

- lamindb/curators/core.py
- tests/curators/test_curators_examples.py
Before this PR, the `CatManager` errored if zero valid categories were found, even if `maximal_set=False`, which should allow arbitrarily many invalid categories.
This previous behavior causes issues in cases in which users have datasets that are annotated by draft metadata.
If a user wants the error, they should instead set `maximal_set=True` for that schema. For example, if you are validating gene ids, you want to make sure at least one ID is validated, otherwise you might be validating against a wrong field.
Removed this hard erroring and replaced it with a warning instead.
> 🎨 Warn when no values are validated

- lamindb/curators/core.py
- tests/curators/test_curators_general.py
Fixes https://github.com/laminlabs/lamindb/issues/2551
Not my favorite solution but I tried a few:
1. Fully circumventing the Pandera error is possible but it might be helpful. Especially when users don't want to use `coerce_dtype`, I don't think that we should swallow it.
2. Instead of modifying the traceback, we could omit a logger message. However, the traceback is so long, I don't think that people will even see the logger message
3. Instead of appending to the same line, I had used a few new lines. The issue is that the vscode renderer then moves the essential error lines up and they're hidden.
| Before | After |
| ------ | ----- |
| ![Before message](https://github.com/user-attachments/assets/170f065b-9f6b-4abf-bb89-aef666e9d362) | ![After …
> 🚸 Improve data type issue errors

- lamindb/core/_context.py
- lamindb/core/_settings.py
- lamindb/models/artifact.py
Fix https://github.com/laminlabs/lamindb/issues/2931
> 🐛 Properly ignore `ln.track()` and tracking warnings on read-only connections

- .gitignore
- docs/arrays.ipynb
- lamindb/core/storage/paths.py
- lamindb/models/_describe.py
- lamindb/models/_django.py
- lamindb/models/_feature_manager.py
- lamindb/models/artifact.py
- lamindb/models/sqlrecord.py
- tests/core/test_describe_and_df_calls.py
- tests/storage/test_artifact_storage.py
- tests/storage/test_transfer.py
Testing for a rather heavily annotated artifact on the other side of the Atlantic.
```
LINE_PROFILE=1 lamin describe --key example_datasets/mini_immuno/dataset1.h5ad
```
Before | After
--- | ---
8.1 sec | 1.3 sec
https://github.com/laminlabs/lamindb/pull/2953/commits/32fac74915be857ae71dd4f02385e6477487f86c
Before | After
--- | ---
2.3 sec | 0 sec
https://github.com/laminlabs/lamindb/pull/2953/commits/82c5f8d5e8380199b67ae9d43e3a1e23989b4535
Before | After
--- | ---
4 sec (93% of pre-fetching) | 0 sec
https://github.com/laminlabs/lamindb/pull/2953/commits/a8943173607ae9f51cafc21e27a9d64ca36f3db5
Before | After
--- | ---
0.66 sec | 0 sec
> ⚡️ Speed up `describe()` by 6x

- lamindb/_finish.py
- lamindb/core/_context.py
Instead of erroring if the notebook file isn't found in the kernel environment, lamindb now prints a warning.
This allows users to save notebooks after a remote compute session from their local environment.
> 🚸 Enable `ln.track()` and `ln.finish()` for notebooks running on remote servers

- docs/curate.ipynb
Minor wording & style fixes.
- Markdown sentences should always be on their own line for easier diffs and reviews
- `feature` is such an overloaded term. Sometimes a sphinx ref might help. It's not always obvious when to add it and when not. I conservatively added one more which I think helps.
- Fixed casing of some words
> 🎨 Polish curate guide

- docs/arrays.ipynb
- lamindb/core/storage/__init__.py
- lamindb/core/storage/_anndata_accessor.py
- lamindb/core/storage/_backed_access.py
- lamindb/core/storage/_spatialdata_accessor.py
- lamindb/models/artifact.py
This PR allows calling `artifact.open()` for `SpatialData` objects for lazy loading of `tables`.
Example:
```python
artifact = ln.Artifact.using("laminlabs/lamindata").get(key="visium_aligned_guide_min.zarr")
access = artifact.open() # SpatialDataAccessor
access.tables["table"] # get AnnDataAccessor for table
```
> ✨ Implement backed access to `tables` of `SpatialData` 

- lamindb/core/storage/_anndata_accessor.py
- lamindb/core/storage/_backed_access.py
- lamindb/core/storage/_spatialdata_accessor.py
- lamindb/core/storage/_zarr.py
- lamindb/models/artifact.py
- tests/storage/test_streaming.py
Allows to add columns to `.obs` and `.var` of cloud `zarr` `AnnData` objects.
Example:
```python
with artifact.open(mode="r+"):
n_obs, n_var = access.shape
access.add_column("obs", "ones_obs", np.ones(n_obs))
access.add_column("var", "ones_var", np.ones(n_var))
```
`artifact` version is updated after the modification.
> ✨ Write mode for `zarr` backed `AnnDataAccessor`

- lamindb/models/artifact.py
- lamindb/models/artifact_set.py
- lamindb/models/query_set.py
- tests/core/test_artifact.py
- tests/storage/test_artifact_storage.py
- tests/storage/test_artifact_zarr.py
Example:
```python
artifact = ln.Artifact.get(path="s3://bucket/folder/file.h5ad")
artifact = ln.Artifact.using("laminlabs/cellxgene").get(path="s3://bucket/folder/file.h5ad")
```
Internal [Slack discussion](https://laminlabs.slack.com/archives/C04FPE8V01W/p1746009345011899).
> ✨ Allow getting artifacts by path via `Artifact.get(path="...")`

- lamindb/models/query_set.py
Fix https://github.com/laminlabs/pfizer-lamin-usage/issues/369
The function makes an additional query during building the dataframe and it is done to the default database even if the queryset is from another database.
> 🐛 Fix `queryset.to_dataframe(include=...)` with `using` and annotations

- lamindb/models/__init__.py
- lamindb/models/artifact.py
- tests/storage/test_streaming.py
For https://github.com/laminlabs/pfizer-lamin-usage/issues/335
so this should work like this:
```python
lazy_artifact = ln.Artifact.from_lazy(suffix=".zarr", overwrite_versions=True, key="myzarr.zarr")
lazy_artifact.path # has the path in root/.lamindb/
... # stream into the path
artifact= lazy_artifact.save() # get the actual artifact
```
> ✨ Implement lazy artifact saving for streaming data

- lamindb/examples/fixtures/sheets.py
- lamindb/models/query_set.py
- tests/curators/test_records.py
Due to two link tables relating `Project` and `Record`, this case contained a bug since:
- https://github.com/laminlabs/lamindb/pull/3014
Now it has a dedicated test & fix.
> 🐛 Include a project feature in a sheet and test it

- lamindb/examples/croissant/__init__.py
- lamindb/integrations/_croissant.py
- lamindb/models/artifact.py
- tests/curators/test_curate_from_croissant.py
Prior to this PR an implicitly inferred artifact key did _not_ lead to mapping artifacts into the same version family, and hence presented inconsistent and unintuitive behavior.
The bug is fixed in the current PR along with adding more comprehensive tests in the context of croissant-file-based ingestion, covering re-ingestion (which is how the bug was surfaced).
> 🐛 Fix version family mapping when registering existing files and add more extensive tests for Croissant file parameterization

- lamindb/models/artifact.py
Fixes a bug in which the version lookup did not happen due to access of `ln.settings.local_storage` as opposed to `ln.settings.storage` in `keep_artifacts_local` mode.
> 🐛 Enable version lookup in `keep_artifacts_local` mode

- lamindb/models/query_set.py
- tests/core/test_queryset.py
This PR enables to query via `.filter()` and `.get()` on the current branch by adding the branch to the branches list on which the querying is done.
This means that instead of only the main branch queries are performed on the main and current branches if no branch is specified in the query expressions.
> 🚸 Add the current branch by default for filtering

- lamindb/models/collection.py
We don't duplicate the lineage information for `Collection.cache()` anymore.
Before | After
--- | ---
https://lamin.ai/laminlabs/lamindata/transform/67YwGo1PrjRp0000/nMKuBkPSVRS1jjVv | https://lamin.ai/laminlabs/lamindata/transform/67YwGo1PrjRp0000/4grVSj6U665AvKTJ
> :children_crossing: Better docs & single data lineage in `Collection.cache()`

- docs/clinicore.md
- lamindb/curators/core.py
- tests/curators/test_curators_examples.py
- tests/curators/test_curators_general.py
The frequency at which the warning is issued is excessive. It's annoying and a user will start ignoring it. For instance, here:
https://lamin.ai/laminlabs/lamindata/transform/M0BgdFXT7Az7
Instead, a targeted mention of the wrong organism being the reason for a validation error makes more sense IMO.
Hence this PR with the corresponding PR in bionty setting the warning to a debug level logging:
- https://github.com/laminlabs/bionty/pull/320
> 🚸 Replace organism warning with targeted message during validation error

- lamindb/core/_mapped_collection.py
Docs don't show static methods now for some reason.
> 📝 Make `MappedCollection.torch_worker_init_fn` a `classmethod` to show in docs
